(function(g){var window=this;var VY=function(a){a.g||(a.g=new g.np,g.G(a,a.g));return a.g},WY=function(a){a.M("cardstatechange",a.md()&&a.qe()?1:0)},XY=function(a){var b=g.qi(a);
a=g.xi(a);return new g.Th(b.x,b.y,a.width,a.height)},YY=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},ZY=function(a){return"none"!=a.style.display},fma=function(a){var b=g.ki(a,"fontSize");
var c=(c=b.match(cma))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.qe){if(String(c)in dma)return g.zi(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in ema)return a=a.parentNode,c=g.ki(a,"fontSize"),g.zi(a,b==c?"1em":b,"left","pixelLeft")}c=g.we("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.De(c);return b},gma=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ml&&a.dataset){if(g.xc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Kc("pollChoiceIndex"))},bZ=function(a){a=g.Sa(a);
delete $Y[a];g.lc($Y)&&aZ&&aZ.stop()},cZ=function(){aZ||(aZ=new g.L(function(){hma()},20));
var a=aZ;a.isActive()||a.start()},hma=function(){var a=(0,g.B)();
g.Zb($Y,function(b){dZ(b,a)});
g.lc($Y)||cZ()},eZ=function(a,b){g.Zf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},fZ=function(a,b,c,d){g.Mo.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},dZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;gZ(a,a.progress);1==a.progress?(a.g=0,bZ(a),a.Rc(),a.l()):1==a.g&&a.ir()},gZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},hZ=function(a,b,c,d,e){fZ.call(this,b,c,d,e);
this.element=a},iZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
hZ.apply(this,arguments)},jma=function(a){return Math.pow(a,3)},kma=function(a){return 3*a*a-2*a*a*a},jZ=function(a){g.F.call(this);
this.i=a||window;this.g=[]},lma=function(a,b,c,d){c=(0,g.y)(c,d||a.i);
b=g.qs(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},kZ=function(a,b){(0,g.A)(b,function(b){g.dt("visualElementShown",{csn:a,
ve:g.mt(b),eventType:4},g.it,void 0,void 0)})},lZ=function(a,b){(0,g.A)(b,function(b){g.dt("visualElementHidden",{csn:a,
ve:g.mt(b),eventType:8},g.it,void 0,void 0)})},mZ=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Sc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={OC:a.impression,click:a.click,close:a.close,sL:a.teaser_impression,hs:a.teaser_click};b=b.tracking_params||{};this.A=g.lt(b.card);this.D=g.lt(b.teaser);this.u=g.lt(b.icon)},nZ=function(a,b){g.xg.call(this);
this.rj=a;this.pp=b;this[g.bg]=!1},sZ=function(a,b,c,d){nZ.call(this,a,b);
a=this.pp;b=this.ha();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.t(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/mma(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.pp;a=this.ha();if(d instanceof oZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof pZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=qZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=qZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=qZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=rZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},tZ=function(){},uZ=function(a,b){nZ.call(this,a,b)},vZ=function(){this.Ua=[];
this.ya=[];this.Hd=[]},wZ=function(a,b,c,d){var e=a.pd[0]-b*Math.cos(g.Yd(d))+b*Math.cos(g.Yd(d+90)),f=a.pd[1]-c*Math.sin(g.Yd(d))+c*Math.sin(g.Yd(d+90));
a.Ua.push(3);a.ya.push(1);a.Hd.push(b,c,d,90,e,f);a.mk=!1;a.pd=[e,f]},oma=function(a,b){for(var c=a.Hd,d=0,e=0,f=a.Ua.length;e<f;e++){var k=a.Ua[e],l=nma[k]*a.ya[e];
b(k,c.slice(d,d+l));d+=l}},xZ=function(a,b,c,d){sZ.call(this,a,b,c,d)},yZ=function(a,b){this.g=a;
this.i=b},zZ=function(a,b,c,d,e){g.Xo.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.N=d||null},mma=function(a){var b=a.hj();
return b?b.width/(a.l?new g.be(a.l,a.N):a.hj()).width:0},pZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Fa(k)?k:null;this.o=g.Fa(l)?l:null},oZ=function(a,b){this.F=a;
this.H=null==b?1:b},AZ=function(a,b){nZ.call(this,a,b)},BZ=function(a,b,c,d){sZ.call(this,a,b,c,d)},CZ=function(a,b,c,d,e){zZ.call(this,a,b,c,d,e);
this.g={};this.R=g.se&&!g.Vc(526);this.K=new g.Qn(this)},qZ=function(a,b,c){a=a.O.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},DZ=function(a,b,c,d){b=qZ(a,"path",{d:pma(b)});
c=new BZ(b,a,c,d);a.o.ha().appendChild(c.ha())},pma=function(a){var b=[];
oma(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},rZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+qma++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},rma=function(){EZ||(EZ=new g.jh(400),EZ.start());
return EZ},FZ=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.D)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.D)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;f.visualElement=g.lt(a.trackingParams);var k=(0,g.D)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,x=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.Cu=k.image;l.left=parseFloat(k.left);l.width=parseFloat(k.width);l.top=parseFloat(k.top);l.aspectRatio=parseFloat(k.aspectRatio);
l.startMs=parseInt(k.startMs,10);l.endMs=parseInt(k.endMs,10);l.clickUrls=(0,g.D)(x.loggingUrls||[],c);l.Ik=g.gc(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.D)(k.impressionUrls||[],c);l.MC=(0,g.D)(k.hovercardShowUrls||[],c);l.Sc={itct:k.trackingParams};l.visualElement=g.lt(k.trackingParams);if("VIDEO"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:e(x.watchEndpoint),l.Gl=!1,l.pn=b,l.videoDuration=d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:
e(x.watchEndpoint),l.Gl=!1,l.pn=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.gc(x,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.Gl=!1;l.pn="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){x=d(m.unsubscribedButtonText);var C=d(m.subscribedButtonText);if(m.subscribed){var E=d(m.subscriberCountWithUnsubscribeText);var H=d(m.subscriberCountText)}else E=d(m.subscriberCountText),H=d(m.subscriberCountWithSubscribeText);
var R=null;if(k.signinEndpoint&&(R=g.gc(k,"signinEndpoint","webNavigationEndpointData","url"),!R)){k=void 0;break a}if(x&&(C||R)){k={subscribed:m.subscribed,subscribeText:x,subscribeCount:E,unsubscribeText:C,unsubscribeCount:H,enabled:m.enabled,signinUrl:R,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=g.gc(x,"urlEndpoint","url"),l.Gl=!0,l.pn="new",l.iconUrl=k.icon.thumbnails[0].url);return l});
f.elements=(0,g.Fe)(k,function(a){return!!a});
return f},GZ=function(a){g.sK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.N=[];a=g.V(a);this.K=g.dz(a)||g.ez(a);this.Kz=!0;this.D=0;this.F=new g.Co;this.u=new g.vs(this);g.G(this,this.u);this.u.J(this.player,g.WD("creatorendscreen"),this.LD);this.u.J(this.player,"crx_creatorendscreen",this.MD);this.u.J(this.player,"resize",this.ob);this.u.J(window,"focus",this.yK);this.load();var b=g.ye("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Wf(this,function(){g.De(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},HZ=function(a){return a.player.getVideoData().Yb?"current":a.K?"new":"current"},IZ=function(a){return"creator-endscreen-editor"===a},JZ=function(a,b){g.cK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.N.length&&(a.N.forEach(function(a){a.dispose()}),a.N.length=0);
a.D=0;if((a.i=b)&&b.elements){sma(a);c=[];var d=new g.TD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.V(a.player).g||(a.l=new g.T({B:"div",G:"ytp-ce-shadow"}),g.gK(a.player,a.l.element,4),a.A=new g.EP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=tma(a,e);a.g[e.id]=f;a.C[e.id]=e;g.gK(a.player,f.element,4);var k=new g.TD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);uma(a,f,e)}g.$J(a.player,
c);a.ob()}},sma=function(a){var b=g.Ft(),c=g.Gt();
c&&b&&g.nt(c,b,[a.i.visualElement])},tma=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",V:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Ik||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:KZ(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{B:"div",V:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Do(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={B:"div",V:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Ik||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:KZ(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{B:"div",V:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Do(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-playlist-count",I:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={B:"div",V:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Ik||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",I:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
I:[{B:"div",G:"ytp-ce-expanding-overlay-body",I:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",I:[{B:"a",V:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.Do(a.F,b.title||"")},U:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",I:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{B:"div",V:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:KZ(b)}]};c=new g.T(c);var d=g.ie(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.V(a.player).g){var e=null;var f=b.Sc.itct}else e="endscreen",f=null;e=new g.rV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":c={B:"div",V:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Ik||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",I:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",I:[{B:"div",G:"ytp-ce-expanding-overlay-body",I:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",
I:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Do(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-website-metadata",U:b.metadata},{B:"a",V:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:KZ(b)},{B:"div",G:"ytp-ce-expanding-icon",L:LZ(b.iconUrl)}]},c=new g.T(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},KZ=function(a){if(a.Cu)var b=a.Cu.thumbnails;
return LZ(b?b[b.length-1].url:null)},LZ=function(a){return a?{style:"background-image: url("+a+")"}:{}},uma=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.y)(a.xq,a,b,c));b.ca("mouseleave",(0,g.y)(a.tr,a,b,c));g.V(a.player).g||b.ca("click",(0,g.y)(function(a){g.J(a.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.y)(a.Tx,a,c));b.ca("keypress",(0,g.y)(a.Tx,a,c));b.ca("focus",(0,g.y)(function(a,b){this.xq(a,b)},a,b,c));
b.ca("blur",(0,g.y)(function(a,b){this.tr(a,b)},a,b,c));
b.ca("touchstart",(0,g.y)(a.xq,a,b,c));var f=g.ke("ytp-ce-expanding-overlay-hider",b.element);f&&b.J(f,"touchstart",function(a){g.ms(a);g.Jo(b.element,"ytp-ce-element-hover");g.Jo(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.y)(function(a,b){this.Kz=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.y)(function(a,b,c){this.D+=c;0<this.D?(g.J(a.element,"ytp-ce-force-expand"),MZ(this,b.id,!0)):(g.Jo(a.element,"ytp-ce-force-expand"),g.Jo(a.element,"ytp-ce-element-hover"),MZ(this,b.id,!1))},a,b,c);
a=(0,g.y)(function(a,b){b&&(a.ca("blur",function(){ZY(b)&&this.Kz&&b.focus()}),a.J(b,"focus",d),a.J(b,"blur",e))},a,b);
a(g.ke("ytp-sb-subscribe",b.element));a(g.ke("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},MZ=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},NZ=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||IZ(g.V(a.player).playerStyle))c&&c();else{b=vma(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Dr(b[a],d)}},OZ=function(a,b,c){NZ(a,b.clickUrls,c);
(a=g.Gt())&&b.Gl&&g.pt(a,b.visualElement)},vma=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(wma(b[e],c));return d},wma=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=unescape(a);
c=c.substring(1,c.length-1);return b[c]?escape(b[c]):a})},PZ=function(a){return g.Ma(a)&&a.length?a[0]:a},QZ=function(a){var b=/.+/;
return g.t(a)&&null!=b&&null!=a&&a.match(b)?a:""},RZ=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},SZ=function(a){return g.t(a)?a:""},TZ=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},UZ=function(a,b){return"true"==a||"false"==a?"true"==a:b},VZ=function(a,b){return g.t(a)?parseFloat(a):b},WZ=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Ud(a,b,c);if(a>=b&&a<=c)return a}return e},xma=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(a){a=parseFloat(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},XZ=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.A)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},yma=function(a){function b(a){return null!=a&&!isNaN(a)}
return(a=a?new g.Qh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},zma=function(a){function b(a){return(0,g.Fe)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},Ama=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},YZ=function(a){if(!a)return null;
var b=g.ud(SZ(a.value));b=g.rd(b);if(!b)return null;var c=TZ(a.target,Bma,"current");return null==c?null:new Ama(b,c,UZ(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},ZZ=function(a){return a.value?a.value:null},Cma=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Fma=function(a){if(!a)return null;
var b=TZ(a.type,Dma),c=TZ(a.trigger,Ema),d=PZ(a.url);d=YZ(d?d:null);PZ(a.subscribeData);return b?new Cma(b,c,d):null},$Z=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},a_=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},b_=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.ti=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},c_=function(a,b){if(!a)return null;
var c=VZ(a.x,0),d=VZ(a.y,0),e=VZ(a.w,0),f=VZ(a.h,0),k=xma(a.t),l=VZ(a.d,0),m=VZ(a.px,0),n=VZ(a.py,0),p=VZ(a.scaleSlope,1),u=VZ(a.scaleSlopeX,p);p=VZ(a.scaleSlopeY,p);var x=TZ(a.scaleDimension,Gma,"xy");return b(c,d,e,f,k,l,m,n,u,p,x)},f_=function(a,b){var c=d_(b,e_(a,new g.Th(a.x,a.y,a.ti,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Ud(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Ud(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},e_=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=$Z(c,a.o,f);
a=a_(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.Th(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},g_=function(a){return a?c_(a,function(a,c,d,e,f,k,l,m,n,p,u){return new b_(a,c,d,e,f,k,l,m,n,p,u)}):null},h_=function(a,b){this.g=a;
this.i=b||null},d_=function(a,b){var c=a.i?f_(a.i,new h_(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.$d?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},i_=function(a,b,c,d,e,f,k,l,m,n,p,u,x){b_.call(this,a,b,c,d,e,l,m,n,p,u,x);
this.D=f;this.F=k},Hma=function(a){if(!a)return null;
var b=VZ(a.sx,0),c=VZ(a.sy,0);return c_(a,function(a,e,f,k,l,m,n,p,u,x,C){return new i_(a,e,f,k,l,b,c,m,n,p,u,x,C)})},Ima=function(a,b,c,d,e,f,k,l,m,n,p,u,x,C){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=u;this.cornerRadius=x;this.u=C},j_=function(a){if(!a)return null;
var b=RZ(a.fgColor,"#1A1A1A"),c=RZ(a.bgColor,"#FFF"),d=RZ(a.borderColor,"#000"),e=WZ(a.borderWidth,0,5,!1,0),f=WZ(a.bgAlpha,0,1,!1,.8),k=RZ(a.highlightFontColor,"#F2F2F2"),l=WZ(a.highlightWidth,0,5,!1,3),m=SZ(a.textAlign),n=WZ(a.textSize,3.3,30.1,!0,3.6107),p=SZ(a.fontWeight),u=yma(a.padding),x=zma(a.effects),C=WZ(a.cornerRadius,0,10,!0,0);a=PZ(a.gradient);if(a=a?a:null){var E=WZ(a.x1,0,100,!0,0),H=WZ(a.y1,0,100,!0,0),R=WZ(a.x2,0,100,!0,100),W=WZ(a.y2,0,100,!0,100),ra=RZ(a.color1,"#FFF"),wb=RZ(a.color2,
"#000");a=new Jma(E,H,R,W,ra,wb,WZ(a.opacity1,0,100,!0,100),WZ(a.opacity2,0,100,!0,0))}else a=null;return new Ima(b,c,d,e,f,k,l,m,n,p,u,x,C,a)},Jma=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},Kma=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},Mma=function(a){if(!a)return null;
var b=TZ(a.type,Lma,"rect"),c=XZ(a.rectRegion,g_),d=XZ(a.anchoredRegion,Hma);a=XZ(a.shapelessRegion,g_);return new Kma(b,c,d,a)},k_=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},Nma=function(a,b){this.i=a;
this.g=b},Oma=function(a,b){this.state=a;
this.ref=b},l_=function(a){if(!a)return null;
var b=TZ(a.state,Pma);a=QZ(a.ref);return b?new Oma(b,a):null},Qma=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},Rma=function(a){if(!a)return null;
var b=XZ(a.condition,l_),c=XZ(a.notCondition,l_),d=UZ(a.show_delay,!1);a=UZ(a.hide_delay,!1);return b||c?new Qma(b,c,d,a):null},Sma=function(a,b,c){(0,g.A)(a.g,g.Va(b,!1),c);
(0,g.A)(a.l,g.Va(b,!0),c)},m_=function(a,b,c,d,e,f,k,l,m,n,p,u,x,C){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.C=l||[];this.i=m;this.A=n;this.u=p;this.data=u;this.g=x;this.itct=C},Vma=function(a){if(!a)return null;
var b=QZ(a.id),c=QZ(a.author),d=TZ(a.type,Tma),e=TZ(a.style,n_),f=SZ(PZ(a.TEXT)),k=SZ(a.data);k=0!=k.length?JSON.parse(k):{};var l=PZ(a.segment);var m=l?l:null;m?(QZ(m.timeRelative),l=QZ(m.spaceRelative),l=(m=XZ(m.movingRegion,Mma))?new Nma(l,m):null):l=null;m=XZ(a.action,Fma);var n=XZ(a.trigger,Rma),p=PZ(a.appearance);(p=j_(p?p:null))||(p=j_({}));var u=TZ(a.coordinate_system,Uma,"video_relative"),x=UZ(a.closeable,!0),C=SZ(a.log_data);a=SZ(a.itct);return b&&d?new m_(b,c,d,e,f,l,m,n,p,u,x,k,C,a):null},
p_=function(a){return o_(a,function(a){return"click"==a.trigger})},o_=function(a,b){return(0,g.fk)(a.l,b,void 0)},Wma=function(a,b,c){(0,g.A)(a.l,b,c)},Xma=function(a,b){return g.cb(a.l,b,void 0)},q_=function(a,b,c){(0,g.A)(a.C,b,c)},Yma=function(a,b){(0,g.D)(a.C,b,void 0)},s_=function(a){return(a=r_(a))?k_(a):null},r_=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},t_=function(a,b){var c=s_(a);
return c&&b?a_(b,c.i,c.g?c.g:"xy"):1},v_=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;Sma(b,function(a,b){var c=u_(b.state,b.ref);this.i.subscribe(c,(0,g.y)(this.o,this,c,a));this.g[c]=a},this)},u_=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},w_=function(){this.g=!1;
this.u=this.i=null},x_=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new CZ(b,c,void 0,void 0,void 0),a.i=b,a.i.wp(),a.u=g.we("DIV"),a.u.appendChild(a.i.ha()));
return a.i},y_=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Zb(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},z_=function(a,b){var c=g.Wo(g.Vo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Zma=function(a,b){var c=z_(a,y_("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=z_(a,y_("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},y_("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=z_(a,y_("feComposite",{"in":c,in2:b,operator:"in"}));return z_(a,y_("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},$ma=function(a,b){var c=z_(a,y_("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=z_(a,y_("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=z_(a,y_("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=z_(a,y_("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=z_(a,y_("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=z_(a,y_("feComposite",{operator:"out","in":c,in2:d}));return z_(a,y_("feComposite",{operator:"over","in":b,in2:c}))},ana=function(a,b){return b},bna=function(a){var b=
y_("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(a){a:{switch(a){case "bevel":a=Zma;break a;case "dropshadow":a=$ma;break a}a=ana}c=a(b,c)});
return b},cna=function(a){a=(0,g.Fe)(a,function(a){return a in A_});
g.zb(a,function(a,c){return A_[a]-A_[c]});
return a},dna=function(a){return g.cb(a,function(a){return"dropshadow"==a})?new g.Qh(0,7,7,0):new g.Qh(0,0,0,0)},B_=function(a,b,c){var d=new vZ;
d.moveTo(a.left+b+c,a.top+c);d.Xb(a.left+a.width-b-c,a.top+c);wZ(d,b,b,-90);d.Xb(a.left+a.width-c,a.top+a.height-b-c);wZ(d,b,b,0);d.Xb(a.left+b+c,a.top+a.height-c);wZ(d,b,b,90);d.Xb(a.left+c,a.top+b+c);wZ(d,b,b,180);d.close();return d},C_=function(a,b,c,d){var e=a.u;
e?a=new pZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new oZ(a.bgColor,d?Math.max(b,.9):b));return a},D_=function(a,b){var c=g.Uh(a),d=dna(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.Th(c.left,c.top,c.right-c.left,c.bottom-c.top)},E_=function(a,b,c){if(c.length&&(b=g.ie(document,"g",void 0,b),b.length)){var d=cna(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=bna(d),a=0<d.childNodes.length?rZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},F_=function(){w_.call(this);
this.o=0},ena=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},G_=function(a){w_.apply(this,arguments)},H_=function(a){w_.apply(this,arguments)},I_=function(a){F_.apply(this,arguments)},J_=function(a,b,c,d,e){g.F.call(this);
this.g=a;this.P=b;this.A=c;this.ga=d;this.W=e;this.F=!1;this.aa=new jZ(this);g.G(this,this.aa);this.O=this.u=this.C=this.K=this.i=null;this.Z=!1;this.Y=this.H=this.N=null;this.xm=new g.fm(this.mC,100,this);g.G(this,this.xm);this.D=new g.L(this.Kv,500,this);g.G(this,this.D);this.R=this.l=this.o=null},fna=function(a,b){var c=(0,g.y)(function(a,c,f){c=f?K_(this,c,(0,g.y)(f,this)):K_(this,c);
this.aa.ca(b,a,c)},a);
c("mouseover","G",a.Hw);c("mouseout","F",a.hg);c("click","D");c("touchend","D")},gna=function(a){if(a.g.u){if(o_(a.g,function(a){return"close"==a.type}))var b=a.i;
else a.o=g.we("DIV","annotation-close-button"),g.yi(a.o,!1),g.qq(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(a){a.stopPropagation()};
a.aa.ca(b,"click",K_(a,"E",c));a.aa.ca(b,"touchend",K_(a,"E",c))}},K_=function(a,b,c){return(0,g.y)(function(a){if(this.W)c&&c(a);
else if(a.event.target instanceof Element){var d=a.event.target;g.yi(d,!1);try{var f=document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.Qe(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.yi(d,
!0)}}d=XY(a.target);a=new g.$d(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.ga.M(b,this.g)},a)},N_=function(a){if(a.i||a.l){var b=s_(a.g);
if(b){var c=L_(a);if(a.i){b=f_(b,c);var d=g.RJ(a.A).getVideoContentRect();g.wi(a.i,b.width,b.height);g.mi(a.i,b.left,b.top);a.K=new g.Th(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=s_(a.g))&&d?$Z(d,e.o,e.g?e.g:"xy"):1;var f=t_(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.Qh(d,d,d,d));d=new g.Qh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.RJ(a.A).getVideoContentRect();var p=g.YJ(a.A);g.Vh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=M_(a,23,b,d,e);if(a.o){var u=43-f.width;0<u&&(b.left+f.left-u>n.left&&(f.left-=u),f.width+=u)}u=f;g.wi(a.u,f.width,f.height);g.mi(a.u,f.left,f.top)}a.o&&(u?b=new g.$d(u.left+
u.width-23-18,a.Z?u.top+2:u.top+u.height-18-2):(u=M_(a,18,b,d,e),b=new g.$d(u.left,u.top),g.wi(a.o,u.width,u.height)),g.mi(a.o,b));a.O=new g.Th(a.K.left+u.left,a.K.top+u.top,u.width,u.height);a.N=a.aa.ca(g.RJ(a.A),"mousemove",a.zE,a)}else a.u&&(u=e/f*d.height*4.2/100,u=new g.be(u,u),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,u=new g.Th(b.width-u.width-e,b.height-u.height-e,u.width,u.height)):u=new g.Th(b.width-u.width-3*d.height/100,(b.height-u.height)/2,u.width,u.height),g.wi(a.u,
u.width,u.height),g.mi(a.u,u.left,u.top)),a.o&&(u=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.mi(a.o,u&&e?new g.$d(b.width-9,-9):u?new g.$d(b.width-9,45<b.height?9:b.height-9):e?new g.$d(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.$d(45<b.width?b.width-9-18:-9,b.height-9):new g.$d(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;u=g.RJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
t_(a.g,u)/100+"px";u=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==u||"highlightText"==u?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;u=(b=g.ke("annotation-link-icon",a))?ZY(b):!1;e=(d=g.ke("annotation-close-button",a))?ZY(d):!1;u&&g.yi(b,!1);e&&g.yi(d,!1);m=f="";if(n=g.ke("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=fma(a);p=5;for(var x=Math.floor(k/2);x;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+x,k)):l=Math.max(l-x,p),x=Math.floor(x/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.yi(d,!0);u&&g.yi(b,!0)}}}},M_=function(a,b,c,d,e){var f=0<e;
b=new g.Th(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.Z=!0);return b},O_=function(a){return"label"!=a.g.style||a.l.g},L_=function(a){var b=g.RJ(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.RJ(a.A).getPlayerSize();b=new g.Th(-b.left,-b.top,c.width,c.height)}else b=new g.Th(0,0,b.width,b.height);return new h_(b,a.R?s_(a.R):null)},P_=function(a,b){return b?new g.Th(a.x+b.left,a.y+b.top,b.width,b.height):null},Q_=function(a,b,c){g.F.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;hna(b,a)},hna=function(a,b){Yma(a,function(c){return new v_(a.id,c,b)})},R_=function(a){a.i.unsubscribe("resize",a.Gw,a);
a.i.unsubscribe("onVideoAreaChange",a.wy,a)},S_=function(a){a.g&&(a.g.stop(),a.g=null)},T_=function(a,b,c){mZ.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=YZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},U_=function(a,b,c){mZ.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=YZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=YZ({target:"current",value:a});this.N=b.signin_title||null;this.H=b.signin_message||null},V_=function(a,b,c){U_.call(this,a,b,c);
this.F=b.ypc_flow_type;this.C=b.innertube_request_params},W_=function(a,b,c){mZ.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=YZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},X_=function(a,b,c){mZ.call(this,a,b,c);
this.C=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=YZ({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},Y_=function(a,b,c){U_.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new ina(a[b]))},ina=function(a){this.merchant=g.Fc(a.merchant);
this.price=g.Fc(a.price)},Z_=function(a,b,c){U_.call(this,a,b,c);
this.K=b.ypc_item_type;this.F=b.ypc_item_id;this.C=b.ypc_flow_type},$_=function(a,b,c){mZ.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=YZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},a0=function(a,b,c){mZ.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.C=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=YZ({target:b.target||"new",value:b.url})},jna=function(a){this.g=a;
this.i={}},kna=function(a){var b={};
b=(b["iv-event"]=1,b);g.XJ(a.g,"iv",b,void 0)},e0=function(a,b,c,d){if(b){var e=b0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=c0(a,"cta_annotation_shown",e,c);d0(a,e,lna(b,d))}},f0=function(a,b,c,d,e,f){if(b){var k=b0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.tc(k,d);b=c0(a,"cta_annotation_clicked",k,e);d0(a,k,b,c,f)}},g0=function(a,b){if(b){var c=b0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=c0(a,"cta_annotation_closed",c);d0(a,c,d)}},lna=function(a,b){return b?(0,g.D)(a,g.Va(function(a,b){return g.Tn(b,a)},b)):a},c0=function(a,b,c,d){d=d?g.pb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.P(g.V(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.Nt){if((b=a.Nt[b])&&g.zv(b)){a=g.yc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Mm){b=g.Yq(a.Mm,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},d0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(a){f++;
g.Dr(a,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.XJ(a.g,"iv",b,m)},b0=function(a,b){var c={};
if(b){var d=new g.In(b);(0,g.A)(d.yd(),function(a){c[a]=escape(d.get(a,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.V(a.g).playerStyle;return c},h0=function(a,b,c,d,e){e=b0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;d0(a,e,d)},i0=function(a,b,c,d){c&&(c=b0(a,c),c["iv-event"]=b,d0(a,c,d))},mna=function(a,b,c,d,e,f,k){this.i=a;
this.o=b;this.u=c;this.videoData=d;this.logger=e;this.g=f;this.l=k},j0=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.Co},nna=function(a,b){var c=[];
(0,g.A)(b.choices,function(a){c.push({B:"li",G:b.C+"-"+a.index.toString(),I:[{B:"label",I:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.C+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",I:[{B:"span",G:"iv-card-poll-choice-percent"},k0(this,"span",void 0,a.desc)]}]},{B:"div",G:"iv-card-poll-result",I:[{B:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={B:"ul",L:{role:"radiogroup"},I:c},e={};b.o&&(e["aria-label"]=g.MN("$POLL_TITLE - Fa\u00e7a login para votar.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",I:[k0(a,"h2",e,b.title),{B:"form",I:[{B:"fieldset",I:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({B:"div",V:["iv-card-sign-in"],I:[{B:"h2",U:"Quer votar?"},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:ZZ(b.o)},I:[{B:"span",V:["iv-button-content"],U:"Fazer login"}]}]}));f=new g.T({B:"div",
V:f,I:d});d=f.element;l0(b,d);lma(a.g.i,d,g.Va(a.C,b),a);(0,g.A)(g.je("iv-card-poll-choice-input",d),function(a){this.g.i.ca(a,"focus",g.Va(this.l,!0));this.g.i.ca(a,"blur",g.Va(this.l,!1))},a);
b.o&&(d=g.ke("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Sc,b.l,b.i.click,5));return f},p0=function(a,b,c,d){var e=b.displayDomain?{B:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=m0(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{B:"a",G:"iv-click-target",L:{href:ZZ(b.url)},I:[n0(b.imageUrl,e),{B:"div",G:"iv-card-content",I:[k0(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({B:"div",V:["iv-card-sign-in"],I:[k0(a,"h2",void 0,b.N||""),{B:"p",U:b.H},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:ZZ(b.g)},I:[k0(a,"span","iv-button-content","Fazer login")]}]});k=new g.T({B:"div",V:k,I:e});o0(a,k,b,c,d);return k},r0=function(a,
b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.C&&b.o?{B:"span",V:d,L:e,U:b.o}:"";c={B:"div",V:["iv-card",c],I:[{B:"a",G:"iv-click-target",L:{href:ZZ(b.url)},I:[n0(b.F,d?{B:"div",G:"iv-card-image-text",I:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",I:[{B:"h2",G:"iv-card-primary-link",U:b.title},q0(a,b)]}]}]};c=new g.T(c);o0(a,c,b);return c},s0=function(a,b){return b.customMessage?k0(a,"div","iv-card-message",
b.customMessage):""},n0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},I:d}},q0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(a){c.push(k0(this,"li","",a))},a);
return{B:"ul",G:"iv-card-meta-info",I:c}},k0=function(a,b,c,d){c?g.t(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Do(a.i,d);return{B:b,L:c,U:d}},m0=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.Do(a.i,b.customMessage);var e=[{B:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",V:c,L:d,I:e}},l0=function(a,b){var c=0;
(0,g.A)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.ke(a.C+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.ke("iv-card-poll-choice-percent",f);g.Le(l,g.MN("$PERCENT%",{PERCENT:k}));f=g.ke("iv-card-poll-result-bar",f);g.ei(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.g);g.K(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},t0=function(a,b,c,d){d?(c&&a.g.videoData.oa||a.g.g.pauseVideo(),a.g.g.isFullscreen()&&a.g.g.toggleFullscreen(),f0(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.Gt())&&g.pt(a,b.A)):b.url&&a.u(b.url,b.id,b.Sc,b.l,b.i.click||[],5)},o0=function(a,b,c,d,e){c.g&&u0(a,g.je("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&u0(a,g.je("iv-click-target",b.element),c,c.url,d)},u0=function(a,b,c,d,e){(0,g.A)(b,function(a){if(e){var b=(0,g.y)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.g.i.ca(a,"click",b)}else d&&this.o(a,d,c.id,c.Sc,c.l,c.i.click,5)},a)},v0=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},x0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=w0(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},w0=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},ona=function(a){a=ZZ(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!x0(a))||(b=g.wh(g.vh(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.Wq(a);if(!b||!b.v)return null;if(b=b.t)return v0(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.Uq(a[1]))&&a.t?v0(a.t):-1},y0=function(a){a=ZZ(a);
a=a.replace(/https?:\/\//g,"");return x0(a)?(a=g.Wq(a))&&a.v?a.v:null:null},pna=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},z0=function(a,b){return b?b:x0(a)?"current":"new"},A0=function(a,b){g.F.call(this);
this.Aa=a;this.context=b;this.Ds=!1;this.ga=0},qna=function(a){return(0,g.B)()-a.ga},rna=function(a,b,c,d,e,f){var k=ZZ(b);
if(k){var l=z0(k,b.target),m=(0,g.y)(function(){b.g&&this.context.g.pauseVideo();var a=this.context.videoData.Yb||!1,d=g.Wq(k||"");a&&d&&(d.v||d.list)?g.wX(this.context.g.app,d.v,c,d.list,!1,void 0,void 0):g.fM(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=qna(a);f0(a.context.logger,d,m,n,e,f);x0(k)||(a=g.Gt(),d=c.itct,a&&d&&g.pt(a,g.lt(d)))}},D0=function(a,b,c){A0.call(this,b,c);
var d=this;this.i=a;this.P=null;this.Z=this.wa=this.u=this.sa=!1;this.Y=null;this.O=new g.L(g.Ja,c.u.Dc?4E3:3E3);g.G(this,this.O);this.la=new g.L(g.Ja);g.G(this,this.la);this.A=new j0(c,(0,g.y)(this.hi,this),(0,g.y)(this.Rl,this));this.F=new g.T({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},I:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},I:[{B:"span",G:"iv-drawer-header-text"},{B:"button",V:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Ocultar cart\u00f5es",tabindex:"0"}}]},{B:"div",
G:"iv-drawer-content"}]});g.G(this,this.F);this.C=this.F.element;this.ea=new g.EP(this.F,330);g.G(this,this.ea);this.xa=g.ke("iv-drawer-header-text",this.C);this.o=g.ke("iv-drawer-content",this.C);this.l=[];this.na=this.R=this.D=this.W=this.g=null;this.N=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&B0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&C0(d)});
this.K=this.H=this.ba=null},vna=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&E0[c]){c=new E0[c](b.id,b.data,b.g);if(!a.sa){g.Io(a.ha(),["html5-stop-propagation","iv-drawer-manager"]);g.gK(a.i,a.C,5);sna(a);a.R=g.ke("ytp-cards-button",a.i.getRootNode());var d=g.ke("iv-drawer-close-button",a.C);a.na=d;a.sa=!0}F0(a,c.id);var e=tna(a,c);if(e){d={Bb:c,Do:e.element,gw:!1};var f=una(a,d);g.sb(a.l,f,0,d);e.X(a.o,f);a.Pk();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Va(a.hL,d)):(e=1E3*a.context.g.getCurrentTime(),5E3>e&&e>c.startMs&&a.rz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Va(a.rz,d)),G0(a))}}},wna=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){B0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){C0(a)});
var c=b.data.headerText;g.Le(a.xa,c);a.R&&a.R.setAttribute("title",c);b.data.eventId&&(a.P=b.data.eventId);a.ba=g.lt(b.data.trackingParams);a.K=g.lt(b.data.closeTrackingParams);a.H=g.lt(b.data.iconTrackingParams)},F0=function(a,b){var c=xna(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Bb.id),g.De(c.Do),g.kb(a.l,c),a.Pk(),G0(a))},B0=function(a,b,c,d){if(!a.u){a.ea.show();
a.W=new g.L(function(){g.J(a.context.g.getRootNode(),"ytp-iv-drawer-open")},0);
a.W.start();a.Y=g.gs(a.o,"mousewheel",(0,g.y)(a.bE,a));a.u=!0;a.ga=(0,g.B)();h0(a.context.logger,a.P,7,void 0,d&&d.Bb?d.Bb.l:void 0);var e=g.Gt();e&&a.ba&&a.K&&kZ(e,[a.ba,a.K]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(b){b.gw||(b.gw=!0,e0(a.context.logger,b.Bb.l,b.Bb.i.OC,f));e&&kZ(e,[b.Bb.A])});
WY(a.i);c&&(a.D=new g.L(function(){a.ia=a.R;a.na.focus()},330),a.D.start())}},C0=function(a){a.u&&(a.ea.hide(),g.hs(a.Y),a.Y=null,g.Jo(a.context.g.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,WY(a.i),a.D&&a.D.stop(),a.D=new g.L(function(){a.ia&&(a.ia.focus(),a.ia=null)},330),a.D.start())},sna=function(a){var b=g.ke("iv-drawer-close-button",a.C);
a.context.i.ca(b,"click",a.yB,a);a.context.i.ca(a.o,"touchend",function(){a.O.start()});
a.context.i.ca(a.o,"scroll",a.FB,a);a.context.l.subscribe("onHideControls",function(){a.Z=!0});
a.context.l.subscribe("onShowControls",function(){a.Z=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Z=g.Ho(a.i.getRootNode(),"ytp-autohide")});
a.N.push(g.Aq("iv-button-shown",a.iD,a));a.N.push(g.Aq("iv-button-hidden",a.hD,a));a.N.push(g.Aq("iv-teaser-shown",a.lD,a));a.N.push(g.Aq("iv-teaser-hidden",a.kD,a));a.N.push(g.Aq("iv-teaser-clicked",a.jD,a))},tna=function(a,b){switch(b.type){case "simple":return p0(a.A,b);
case "collaborator":var c=a.A,d={B:"div",V:["iv-card","iv-card-channel"],I:[{B:"a",V:["iv-click-target"],L:{href:ZZ(b.url),"data-ytid":b.channelId},I:[n0(b.profileImageUrl),{B:"div",G:"iv-card-content",I:[s0(c,b),{B:"h2",G:"iv-card-primary-link",U:b.title},q0(c,b)]}]}]};d=new g.T(d);o0(c,d,b);return d;case "donation":return c=a.A,d=(0,g.y)(c.A,c,b),p0(c,b,d,d);case "episode":return r0(a.A,b,"iv-card-episode");case "movie":return r0(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={B:"div",V:["iv-card",
"iv-card-playlist"],I:[{B:"a",G:"iv-click-target",L:{href:ZZ(b.url)},I:[n0(b.o,{B:"div",G:"iv-card-image-overlay",I:[{B:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",I:[s0(c,b),k0(c,"h2","iv-card-primary-link",b.title),q0(c,b)]}]}]},d=new g.T(d),o0(c,d,b),d;case "poll":return nna(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=m0(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({B:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={B:"div",I:k});d={B:"div",V:d,L:{tabindex:"0"},I:[{B:"a",V:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:ZZ(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",I:[b.sponsored?{B:"div",G:"iv-card-sponsored",I:["Patrocinado",{B:"div",G:"iv-ad-info-container",I:[{B:"div",G:"iv-ad-info",U:"{{adInfo}}"},
{B:"div",G:"iv-ad-info-icon-container",I:[{B:"div",G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:ZZ(b.url)},I:[k0(c,"h2",f,b.title),k]}]}]};d=new g.T(d);f=g.ye("span");g.Le(f,"Voc\u00ea v\u00ea este produto porque achamos que ele \u00e9 relevante para o v\u00eddeo. O Google pode ser compensado pelo comerciante.");d.jb(f,"adInfo");o0(c,d,b);return d;case "tip":return c=a.A,d=(0,g.y)(c.D,c,b),p0(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{B:"span",
V:["yt-badge","yt-badge-live"],U:"AO VIVO AGORA"}:"",d={B:"div",V:["iv-card","iv-card-video"],I:[{B:"a",G:"iv-click-target",L:{href:ZZ(b.url)},I:[n0(b.o,b.videoDuration?{B:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{B:"div",G:"iv-card-content",I:[s0(c,b),k0(c,"h2","iv-card-primary-link",b.title),q0(c,b),d]}]}]},d=new g.T(d),o0(c,d,b),d}return null},una=function(a,b){if(0==a.l.length)return 0;
var c=g.db(a.l,function(a){return b.Bb.startMs>a.Bb.startMs||b.Bb.startMs==a.Bb.startMs&&b.Bb.timestamp>=a.Bb.timestamp?!0:!1});
return-1==c?0:c+1},yna=function(a){return a.g?"productListing"==a.g.Bb.type:(0,g.ln)(a.l,function(a){return"productListing"==a.Bb.type})},G0=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",yna(a))},H0=function(a,b){if(a.F.Fa()){var c=new fZ([0,
a.o.scrollTop],[0,b.Do.offsetTop],600,kma);a.context.o.ca(c,"animate",function(b){a.o.scrollTop=b.y});
a.context.o.ca(c,"finish",function(b){a.o.scrollTop=b.y});
c.play()}else g.oC(a.F,!0),a.o.scrollTop=b.Do.offsetTop,g.oC(a.F,!1)},I0=function(a){return a.g&&a.g.Bb?a.g.Bb:a.l[0]&&a.l[0].Bb?a.l[0].Bb:null},xna=function(a,b){return g.cb(a.l,function(a){return a.Bb.id==b})},J0=function(a,b,c){A0.call(this,a,b);
this.annotation=c;this.isActive=!1},zna=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},K0=function(a,b,c){J0.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},L0=function(a,b,c){J0.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.we("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.L(function(){this.g.setAttribute("aria-hidden",!0);g.yi(this.l,!1);g.yi(this.i,!0)},700,this);
g.G(this,this.A)},Ana=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ha().setAttribute("aria-hidden",!0);a.ha().setAttribute("aria-label","Promo\u00e7\u00e3o");a.ha().tabIndex=0;var e=a.annotation.Ib(),f=b.image_url;if(f){var k=g.we("DIV",["iv-promo-img","iv-click-target"]);f=g.we("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.we("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.we("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.hi(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.we("A","iv-promo-txt"),g.Pd(f,ZZ(e)),a.g=f):a.g=g.we("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.we("P",null,g.we("STRONG",null,b.text_line_1));var m=g.we("P",null,g.we("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.P(a.context.u.experiments,"web_center_align_action_cta")&&d.push("iv-promo-website-card-cta-center-aligned");g.P(a.context.u.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.we("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.we("BUTTON",["iv-button","iv-promo-button"],g.we("SPAN","iv-button-content",f));var p=g.we("DIV","iv-promo-button-container");p.appendChild(f);e&&a.hi(a.ha(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.J(a.g,
"iv-click-target");e&&a.hi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=g.we("P",null,g.we("SPAN",null,b.text_line_1)),m=g.we("P",null,g.we("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.we("SPAN",["yt-badge","iv-promo-badge-live"],"AO VIVO AGORA")),g.J(a.g,"iv-click-target"),e&&a.hi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);
c=g.we("DIV","iv-promo-actions");a.i=g.we("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expandir";a.context.i.ca(a.i,"click",g.Va(a.zp,5E3),a);c.appendChild(a.i);g.yi(a.i,!1);a.context.i.ca(a.ha(),"mouseover",a.oC,a);a.context.i.ca(a.ha(),"mouseout",a.nC,a);a.context.i.ca(a.ha(),"touchend",g.Va(a.zp,5E3),a);a.l=g.we("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Fechar";a.context.i.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.gC:a.fC,a);c.appendChild(a.l);g.Io(a.ha(),d);
k&&(a.ha().appendChild(k),n&&k.appendChild(n));a.ha().appendChild(a.D);a.ha().appendChild(c)},M0=function(a){a.u||a.F||a.o||(g.J(a.ha(),"iv-promo-collapsed"),a.u=!0,a.A.start())},N0=function(a){a.A.stop();
a.u&&(g.Ko(a.ha(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.yi(a.i,!1),g.yi(a.l,!0))},P0=function(a,b){a.o||(a.o=g.kh(function(){O0(this);
M0(this)},b,a))},O0=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},Q0=function(a){g.sK.call(this,a);
this.N=!1;this.H=0;this.i={};this.K={};this.D=new jna(a);this.A=new g.vs(this);g.G(this,this.A);this.C=this.l=null;this.A.J(this.player,"onVideoAreaChange",(0,g.y)(this.M,this,"onVideoAreaChange"));this.A.J(this.player,"onHideControls",(0,g.y)(this.M,this,"onHideControls"));this.A.J(this.player,"onShowControls",(0,g.y)(this.M,this,"onShowControls"));this.A.J(this.player,"resize",(0,g.y)(this.M,this,"resize"));this.A.J(this.player,"presentingplayerstatechange",(0,g.y)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.NH,this);this.subscribe("onShowControls",this.OJ,this);this.subscribe("presentingplayerstatechange",this.WI,this);this.subscribe("resize",this.ur,this);this.subscribe("G",this.JD,this);this.subscribe("F",this.hg,this);this.subscribe("D",this.JG,this);this.subscribe("E",this.mH,this);g.V(this.player).K.subscribe("vast_info_card_add",this.vy,this);this.P=new g.vs(this);g.G(this,this.P);this.P.J(this.player,g.WD("annotations_module"),this.HD);this.P.J(this.player,
"crx_annotations_module",this.ID);this.R=g.we("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Z=g.we("DIV","video-custom-annotations");this.u=new g.T({B:"div",V:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.gK(this.player,this.u.element,4);this.u.hide();this.o=new g.T({B:"div",V:["ytp-iv-video-content"]});g.G(this,this.o);g.Ae(this.o.element,g.we("DIV","video-annotations",this.R,this.Z));this.F=this.g=null;this.O=[];Bna(this)&&this.load();var b=g.ye("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Wf(this,function(){g.De(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},R0=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Bna=function(a){var b=g.V(a.player);
a=a.player.getVideoData();return 1==(b.Ef||a.Ef)&&!a.pA||null!==b.K.get(a.videoId)},S0=function(a,b,c){a.N=!0;
a.C=g.hr(b,c)},T0=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(T0(a,e))}return c},U0=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},Dna=function(a,b){var c=Cna(a,b);
if(!c&&"marker"!=b.type)return null;q_(b,function(a){a=(0,g.y)(this.jK,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new Q_(a.ea,b,c);g.G(d,c);return d},Ena=function(a,b){var c=g.we("DIV",["annotation",
"annotation-type-custom"]);g.yi(c,!1);var d=null;switch(b.type){case "branding":if(g.V(a.player).Cc)break;a.u.element.appendChild(c);d=new K0(c,V0(a),b);break;case "promotion":g.gK(a.player,c,4),d=new L0(c,V0(a),b)}d&&d.hn();return d},Fna=function(a){var b=a.player.getVideoData();
if(b.wd){var c=g.V(a.player),d=c.K.get(b.videoId);if(d){var e={format:"XML",yc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.yc.gaming="1");e.Rc=(0,g.y)(function(a,b,c){U0(this,a,b)||(a=g.Rq(c)&&c.responseXML?c.responseXML:null)&&W0(this,a)},a,a.H,b.videoId);
g.Ws()&&(e.Rc=X0(a,e.Rc));e.rb={ic_only:"1"};Y0(e,d);a.N=!0;g.hr(b.wd,e)}}},Y0=function(a,b){a.method="POST";
a.rb=a.rb||{};b.Uk&&(a.rb.ic_coll=b.Uk);b.Vk&&(a.rb.ic_xml=b.Vk);b.os&&(a.rb.ic_track=b.os)},Gna=function(a){var b=new g.T({B:"div"});
g.yi(b.element,!1);var c=new D0(a.player,b.element,V0(a));g.G(c,b);b.X(a.u.element);c.hn();return c},V0=function(a){if(!a.F){var b=new jZ(a);
g.G(a,b);var c=new g.Qn(a);g.G(a,c);a.F=new mna(b,c,g.V(a.player),a.player.getVideoData(),a.D,a.player,a.ea)}return a.F},W0=function(a,b){var c=!1;
Hna(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=T0(a,d[e]),k=null;try{k=Vma(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=Ena(a,k))g.G(a,f),a.K[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=Gna(a),g.G(a,a.g)),"card"==k.type?vna(a.g,k):wna(a.g,k),c=!0;else if(f=Dna(a,k))g.G(a,f),a.i[k.id]=f}}c&&(WY(a.player),a.ur());g.Zb(a.i,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.i&&
(b=this.i[b.segment.i])&&(a.R=b.annotation)}},a)},Hna=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.Gt();
if(b){var c=g.Ft();c&&g.nt(b,c,[g.lt(a)])}}},Ina=function(a,b,c,d){d?Z0(a,b,c):$0(a,b,c)},$0=function(a,b,c){if(b=a.i[b])S_(b),c&&c.i?(a=(0,g.y)(a.Jv,a,b),b.g=new g.L(a,2E3),b.g.start()):a.Jv(b)},Z0=function(a,b,c){if(b=a.i[b])S_(b),c&&c.o?(a=(0,g.y)(a.Cz,a,b),b.g=new g.L(a,2E3),b.g.start()):a.Cz(b)},a1=function(a,b){var c=a.player.getVideoData();
if(!c.Kk)return!1;var d=ZZ(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!x0(d))return!1;d=g.Wq(d);return d.list||d.p?!1:(d=y0(b))?c.videoId==d?!0:"new"!=b.target&&g.V(a.player).i?!0:!1:!1},Cna=function(a,b){if(Jna(b)){var c=b.u||o_(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new J_(b,(0,g.y)(a.R.appendChild,a.R),a.player,a.ea,c)}return null},Jna=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in n_)if(a.style==n_[b])return!0;return!1},b1=function(a,b,c,d){a.M(u_(b,d),c,d)},X0=function(a,b){return(0,g.y)(function(){if(!this.da()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.Va.apply(window,a);this.O.push(g.Us(b))}},a)};
g.LJ.prototype.gi=g.ca(14,function(a,b){var c=g.MJ(this).l;c&&c.gi(a,b)});
g.Xo.prototype.wp=g.ca(0,function(){this.i=this.O.createElement("DIV")});
var cma=/[^\d]+$/,dma={cm:1,"in":1,mm:1,pc:1,pt:1},ema={em:1,ex:1},$Y={},aZ=null;g.z(eZ,g.Zf);g.z(fZ,g.Mo);g.h=fZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;bZ(this);this.startTime=a=(0,g.B)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Ld("play");-1==this.g&&this.Ld("resume");this.g=1;var b=g.Sa(this);b in $Y||($Y[b]=this);cZ();dZ(this,a);return!0};
g.h.stop=function(a){bZ(this);this.g=0;a&&(this.progress=1);gZ(this,this.progress);this.Ld("stop");this.l()};
g.h.pause=function(){1==this.g&&(bZ(this),this.g=-1,this.Ld("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Ld("destroy");fZ.Ga.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.ir=function(){this.Ld("animate")};
g.h.Ld=function(a){this.dispatchEvent(new eZ(a,this))};
g.z(hZ,fZ);hZ.prototype.u=g.Ja;hZ.prototype.ir=function(){this.u();hZ.Ga.ir.call(this)};
hZ.prototype.l=function(){this.u();hZ.Ga.l.call(this)};
hZ.prototype.o=function(){this.u();hZ.Ga.o.call(this)};
g.z(iZ,hZ);iZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.r(jZ,g.F);jZ.prototype.ca=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.gs(a,b,c);this.g.push(a);return a};
jZ.prototype.Sl=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.rs(a,b,c);this.g.push(a);return a};
jZ.prototype.Ma=function(a){g.hs(a);g.kb(this.g,a)};
jZ.prototype.T=function(){g.hs(this.g);this.g.length=0;g.F.prototype.T.call(this)};g.z(nZ,g.xg);g.h=nZ.prototype;g.h.pp=null;g.h.rj=null;g.h.ha=function(){return this.rj};
g.h.addEventListener=function(a,b,c,d){g.jg(this.rj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.rg(this.rj,a,b,c,d)};
g.h.T=function(){nZ.Ga.T.call(this);var a=this.rj;if(a)if(g.cg(a))a.ce&&g.gg(a.ce);else if(a=g.mg(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.sg(d[e])&&++b}};g.z(sZ,nZ);sZ.prototype.fill=null;g.z(uZ,nZ);vZ.prototype.te=null;vZ.prototype.pd=null;vZ.prototype.mk=!0;var nma=[2,2,6,6,0];g.h=vZ.prototype;g.h.clear=function(){this.Ua.length=0;this.ya.length=0;this.Hd.length=0;delete this.te;delete this.pd;delete this.mk;return this};
g.h.moveTo=function(a,b){0==g.Za(this.Ua)?this.Hd.length-=2:(this.Ua.push(0),this.ya.push(1));this.Hd.push(a,b);this.pd=this.te=[a,b];return this};
g.h.Xb=function(a){var b=g.Za(this.Ua);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ua.push(1),this.ya.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Hd.push(c,d)}this.ya[this.ya.length-1]+=b/2;this.pd=[c,d]};
g.h.close=function(){var a=g.Za(this.Ua);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ua.push(4),this.ya.push(1),this.pd=this.te);return this};
g.h.clone=function(){var a=new this.constructor;a.Ua=this.Ua.concat();a.ya=this.ya.concat();a.Hd=this.Hd.concat();a.te=this.te&&this.te.concat();a.pd=this.pd&&this.pd.concat();a.mk=this.mk;return a};
g.h.transform=function(a){if(!this.mk)throw Error("Non-simple path");a.transform(this.Hd,0,this.Hd,0,this.Hd.length/2);this.te&&a.transform(this.te,0,this.te,0,1);this.pd&&this.te!=this.pd&&a.transform(this.pd,0,this.pd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ua.length};g.z(xZ,sZ);g.z(zZ,g.Xo);zZ.prototype.o=null;zZ.prototype.hj=function(){return this.Eg?g.xi(this.ha()):g.Ha(this.width)&&g.Ha(this.height)?new g.be(this.width,this.height):null};
zZ.prototype.resume=function(){};g.z(pZ,tZ);g.z(oZ,tZ);g.z(AZ,uZ);AZ.prototype.clear=function(){g.Be(this.ha())};
AZ.prototype.setSize=function(a,b){var c=this.ha(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.z(BZ,xZ);var EZ;g.z(CZ,zZ);var qma=0;g.h=CZ.prototype;g.h.wp=function(){var a=qZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=qZ(this,"g");this.C=qZ(this,"defs");this.o=new AZ(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ha().setAttribute("preserveAspectRatio","none"),this.R?this.eA():this.ha().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.N:"")))};
g.h.eA=function(){if(this.Eg){var a=this.hj();0==a.width?this.ha().style.visibility="hidden":(this.ha().style.visibility="",this.o.ha().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.N+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.wi(this.ha(),a,b)};
g.h.hj=function(){if(!g.gi)return this.Eg?g.xi(this.ha()):CZ.Ga.hj.call(this);var a=this.width,b=this.height,c=g.t(a)&&-1!=a.indexOf("%"),d=g.t(b)&&-1!=b.indexOf("%");if(!this.Eg&&(c||d))return null;if(c){var e=this.ha().parentNode;var f=g.xi(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ha().parentNode,f=f||g.xi(e),b=parseFloat(b)*f.height/100);return new g.be(a,b)};
g.h.clear=function(){this.o.clear();g.Be(this.C);this.g={}};
g.h.Xi=function(){CZ.Ga.Xi.call(this);this.R&&this.K.Ma(rma(),"tick",this.eA)};
g.h.T=function(){delete this.g;delete this.C;delete this.o;this.K.dispose();delete this.K;CZ.Ga.T.call(this)};g.r(GZ,g.sK);g.h=GZ.prototype;
g.h.load=function(){g.sK.prototype.load.call(this);if(!IZ(g.V(this.player).playerStyle)){var a=g.WB(this.player.getVideoData());if(a)a=FZ(a,HZ(this)),JZ(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Rc:(0,g.y)(this.EH,this,a),yc:{v:a},withCredentials:!0};"gaming"==g.V(this.player).playerStyle&&(a.yc.gaming="1");this.K&&(a.yc.ptype="embedded");var c=this.player.getVideoData().Gu;c&&(a.rb={ad_tracking:c});if(b=g.VB(b))if(b=g.ud(b),b=g.rd(b))this.o=
g.hr(b,a)}}};
g.h.unload=function(){JZ(this,null);this.o&&(this.o.abort(),this.o=null);g.sK.prototype.unload.call(this)};
g.h.Wb=function(a,b){if(!IZ(g.V(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=FZ(b,"new");JZ(this,c);return!0}return null};
g.h.getOptions=function(){return IZ(g.V(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.EH=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=FZ(c,HZ(this)))}JZ(this,c)};
g.h.ob=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<c1.length;f++){var k=Math.abs(b.width-c1[f]);if(-1==e||d>=k)e=f,d=k}d=d1[e];this.l&&g.ei(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.wi(e.element,Math.round(k.width*a.width),f);g.mi(e.element,m,n);g.Ko(e.element,Kna);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ko(e.element,d1);g.J(e.element,d);(e=g.ie(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ei(e,"height",f+"px")}}}}};
g.h.LD=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.UJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(NZ(this,this.i.impressionUrls),(a=g.Gt())&&g.ot(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");NZ(this,c.impressionUrls);(b=g.Gt())&&g.ot(b,c.visualElement);
g.V(this.player).tb&&this.player.ma("endscreenelementshown",a)}};
g.h.MD=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Jo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Jo(b,"ytp-ce-shown");g.V(this.player).tb&&this.player.ma("endscreenelementhidden",a)}};
g.h.yK=function(a){var b=this;a.target===window&&(new g.L(function(){for(var a in b.g)g.Ko(b.g[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Tx=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Ho(c,"ytp-ce-element");){g.Ho(c,"subscribe-label")&&OZ(this,a);if(g.Ho(c,"ytp-ce-channel-subscribe"))return;c=g.Je(c)}if(!c||g.Ho(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.tr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.pn?(OZ(this,a),this.kz(),this.player.pauseVideo(),c=g.ud(a.targetUrl),c=g.rd(c),g.fM(c,void 0,a.Sc)):(c=this.player.getVideoData().Yb,
c=(0,g.y)(this.nL,this,c,a.targetUrl,a.Sc),c=(0,g.y)(this.kz,this,c),OZ(this,a,c))}}};
g.h.nL=function(a,b,c){var d=g.Wq(b);a&&d&&(d.v||d.list)?g.wX(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.eM(b,c)};
g.h.xq=function(a,b){g.Ho(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.V(this.player).g?(new g.L(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),NZ(this,b.MC),MZ(this,b.id,!0))};
g.h.tr=function(a,b){g.Jo(a.element,"ytp-ce-element-hover");g.Jo(a.element,"ytp-ce-force-expand");MZ(this,b.id,!1)};
g.h.kz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var c1=[346,426,470,506,570,640,853,1280,1920],d1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Kna=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Bma={OM:"current",UN:"new"};var Dma={CLOSE:"close",XN:"openUrl",eB:"subscribe"},Ema={HM:"click",CLOSE:"close",qN:"hidden",wO:"rollOut",aB:"rollOver",bB:"shown"};var Gma={aP:"xx",bP:"xy",cP:"yx",dP:"yy"};g.r(i_,b_);var Lma={BA:"anchored",sO:"rect",zO:"shapeless"};var Pma={CLOSED:"closed",gO:"playerControlShow",aB:"rollOver",bB:"shown"};m_.prototype.Ib=function(){var a=Xma(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
m_.prototype.showLinkIcon=function(){return o_(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var n_={BA:"anchored",EA:"branding",CHANNEL:"channel",MM:"cta",sN:"highlightText",GN:"label",PLAYLIST:"playlist",jO:"popup",DO:"speech",eB:"subscribe",MO:"title",VIDEO:"video",WO:"website"},Tma={EA:"branding",yM:"card",UM:"drawer",rN:"highlight",ON:"marker",oO:"promotion",TEXT:"text",YO:"widget"},Uma={UO:"video_relative",hO:"player_relative"};v_.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.cc(this.g,function(a){return a});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};w_.prototype.ha=function(){return this.u};
w_.prototype.l=function(){};var A_={bevel:1,dropshadow:2};g.r(F_,w_);
F_.prototype.l=function(a,b){var c=s_(a);if(c){var d=f_(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=r_(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.Wh(d_(b,e_(e,new g.Th(e.D,e.F,e.ti,e.l),b.g))),k=d.clone();c=new g.Th(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=D_(k,c.effects);l=x_(this,k.width,k.height);m=C_(c,k.width,k.height,this.g);
d=new g.Th(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.$d(f.x-k.left,f.y-k.top);this.o=17*a_(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&p_(a),u=p?f.borderWidth+1:f.borderWidth;p=(f=u?new yZ(u,p?f.i:f.borderColor):null)?f.g/2:0;u=ena(d,n);var x=this.A(d,e,n,u),C=n.x;n=n.y;var E=d.width,H=d.height,R=d.left;d=d.top;var W=new vZ;W.moveTo(R+e+p,d+p);"t"==u&&(W.Xb(x.start,d+p),W.Xb(C,n),W.Xb(x.end,d+p));W.Xb(R+E-e-p,d+p);wZ(W,e,e,-90);"r"==u&&(W.Xb(R+E-p,x.start),W.Xb(C,n),W.Xb(R+
E-p,x.end));W.Xb(R+E-p,d+H-e-p);wZ(W,e,e,0);"b"==u&&(W.Xb(x.end,d+H-p),W.Xb(C,n),W.Xb(x.start,d+H-p));W.Xb(R+e+p,d+H-p);wZ(W,e,e,90);"l"==u&&(W.Xb(R+p,x.end),W.Xb(C,n),W.Xb(R+p,x.start));W.Xb(R+p,d+e+p);wZ(W,e,e,180);W.close();DZ(l,W,f,m);if(m=this.ha())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.mi(m,k.left,k.top),g.wi(m,k.width,k.height),E_(l,m,c.effects)}}}};
F_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.Ud(c-a/2,d+b,d+e-a-b);return new g.xj(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.xj(0,0)};g.r(G_,w_);G_.prototype.l=function(a,b){var c=s_(a);if(c){var d=f_(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=D_(d,e.effects);var f=x_(this,c.width,c.height),k=new yZ(!e.l&&this.g?1:e.l,e.bgColor),l=new oZ("#000",0);d=B_(new g.Th(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);DZ(f,d,k,l);f=this.ha();g.J(f,"annotation-shape");e=e.g;YY(f,this.g?Math.max(e,.9):e);g.mi(f,c.left,c.top);g.wi(f,c.width,c.height)}}};g.r(H_,w_);
H_.prototype.l=function(a,b){var c=s_(a);if(c){var d=f_(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=D_(d,c.effects),f=x_(this,e.width,e.height),k=new g.Th(0,0,d.width,d.height);d=C_(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&p_(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new yZ(p,n?m.i:m.borderColor):null;k=B_(k,l,m?m.g/2+1:0);DZ(f,k,m,d);if(k=this.ha())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.mi(k,e.left,e.top),g.wi(k,e.width,e.height),E_(f,k,c.effects)}}};g.r(I_,F_);I_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new g.xj(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.xj(0,0)};g.r(J_,g.F);g.h=J_.prototype;g.h.Hw=function(){this.F||(this.o&&g.yi(this.o,!0),this.u&&g.yi(this.u,!0),this.l&&(this.l.g=!0,YY(this.i,O_(this)?1:0),this.l.l(this.g,L_(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Sl(g.RJ(this.A),"mouseleave",function(a){this.xm.stop();this.hg(a)}))};
g.h.hg=function(){this.F&&(this.O?this.D.start():this.Kv(),this.l&&(this.l.g=!1,YY(this.i,O_(this)?1:0),this.l.l(this.g,L_(this))),this.F=!1,this.H&&(this.aa.Ma(this.H),this.H=null))};
g.h.Kv=function(){this.o&&g.yi(this.o,!1);this.u&&g.yi(this.u,!1)};
g.h.zE=function(a){this.Y=a;this.xm.pj()};
g.h.mC=function(){var a=this.Y,b=new g.$d(a.clientX,a.clientY),c=g.qi(this.A.getRootNode()),d=P_(c,this.K);c=(this.u&&ZY(this.u)||this.o&&ZY(this.o))&&P_(c,this.O);d&&d.contains(b)||c&&c.contains(b)?this.Hw(a):this.hg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=L_(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new G_:"popup"==this.g.style?d=new H_:"anchored"==this.g.style?d=new F_:"speech"==this.g.style&&(d=new I_);d&&(d.l(this.g,c),this.l=d,c=d.ha())&&(g.yi(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.P(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.we("DIV",c);g.yi(this.i,!1);this.g.o&&(this.C=g.we("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.i.bgColor),g.Le(this.C,this.g.o),this.i.appendChild(this.C));g.qq(this.i,"annotation_id",this.g.id);this.P(this.i);fna(this,this.i);if(p_(this.g)&&this.g.showLinkIcon()){if(d=this.g.Ib())c=this.i,d=new g.Cn(ZZ(d)),c.title=d.g+d.i;this.u=g.we("SPAN","annotation-link-icon");g.yi(this.u,
!1);this.i.appendChild(this.u)}gna(this);p_(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=k_(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ha()&&(this.l.ha().style.zIndex=a)}g.yi(this.i,!0);YY(this.i,O_(this)?1:0);N_(this);this.l&&this.l.ha()&&g.yi(this.l.ha(),!0)};
g.h.hide=function(){this.i&&g.yi(this.i,!1);this.l&&this.l.ha()&&g.yi(this.l.ha(),!1);this.N&&(this.aa.Ma(this.N),this.N=null)};g.r(Q_,g.F);g.h=Q_.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(R_(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.Gw,this),this.i.subscribe("onVideoAreaChange",this.wy,this))};
g.h.destroy=function(){if(this.view){R_(this);var a=this.view,b=a.aa;g.hs(b.g);b.g.length=0;a.xm.dispose();a.D.dispose();a.i&&g.De(a.i);a.l&&a.l.ha()&&g.De(a.l.ha())}S_(this)};
g.h.wy=function(){N_(this.view)};
g.h.Gw=function(){N_(this.view)};g.r(T_,mZ);g.r(U_,mZ);g.r(V_,U_);g.r(W_,mZ);g.r(X_,mZ);g.r(Y_,U_);g.r(Z_,U_);g.r($_,mZ);g.r(a0,mZ);j0.prototype.l=function(a,b){var c=g.Qe(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
j0.prototype.C=function(a,b){var c=g.Qe(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.ke("iv-card-sign-in-button",c).click();else{var d=parseInt(gma(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;l0(a,c);g.lr(this.g.videoData.wd,{yc:{action_poll_vote:1},rb:{poll_id:a.id,index:d,session_token:a.F}});f0(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.Gt())&&g.pt(c,a.A)}};
j0.prototype.A=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.C)});
t0(this,a,!0,c)};
j0.prototype.D=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Va(b,a.K,a.F,a.C));t0(this,a,!1,b)};g.r(A0,g.F);g.h=A0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.TD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&VY(a).subscribe("onEnter",d,this);e&&VY(a).subscribe("onExit",e,this);g.$J(this.context.g,[a])};
g.h.hn=function(){this.context.l.subscribe("resize",this.Pk,this)};
g.h.ha=function(){return this.Aa};
g.h.hi=function(a,b,c,d,e,f,k){this.context.i.ca(a,"click",g.Va(this.Rl,b,c,d,e,f||[],k||0),this);this.context.i.ca(a,"touchstart",g.Va(function(){this.Ds=!1}),this);
this.context.i.ca(a,"touchmove",g.Va(function(){this.Ds=!0}),this)};
g.h.Rl=function(a,b,c,d,e,f,k){if(this.Ds)return!1;k&&(k.stopPropagation(),k.preventDefault());rna(this,a,c,d,e,f);return!1};
g.h.show=function(){this.ga=(0,g.B)()};
g.h.hide=function(){};
g.h.destroy=function(){g.De(this.ha())};
g.h.Pk=function(){};g.r(D0,A0);g.h=D0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.xi(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Pk=function(){var a=this.isAvailable();g.yi(this.ha(),a);g.K(this.context.g.getRootNode(),"ytp-iv-drawer-enabled",a);WY(this.i)};
g.h.destroy=function(){this.i.gi(!1);this.i.getRootNode().removeChild(this.C);g.Bq(this.N);g.hs(this.Y);this.W&&this.W.dispose();this.D&&this.D.dispose();A0.prototype.destroy.call(this)};
g.h.bE=function(a){this.O.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.rz=function(a){if(!g.Ho(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.Gt(),c=this.g?this.g.Bb.u:this.H;b&&c&&lZ(b,[c]);this.g=a;G0(this)}ZY(this.ha())&&(2==this.context.g.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.g.getAdState():void 0):(b=isNaN(void 0)?this.context.g.getPlayerState():void 0,b=1==b||0==b&&0===this.context.g.getCurrentTime()),b&&a.Bb.teaserDurationMs&&this.i.gi(!0,{teaserText:a.Bb.teaserText,durationMs:a.Bb.teaserDurationMs}));this.la.isActive()||
((!this.u||!this.O.isActive()&&this.Z)&&H0(this,a),this.la.start(910+a.Bb.teaserDurationMs))}};
g.h.hL=function(a){this.u||(this.g=a,G0(this),H0(this,a),B0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.yB=function(){if(this.u){h0(this.context.logger,this.P,4,I0(this).i.close);var a=g.Gt();a&&this.K&&g.pt(a,this.K);C0(this)}};
g.h.FB=function(){g.K(this.C,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.iD=function(){var a=g.Gt(),b=I0(this);b=b?b.u:this.H;a&&b&&kZ(a,[b])};
g.h.hD=function(){var a=g.Gt(),b=I0(this);b=b?b.u:this.H;a&&b&&lZ(a,[b])};
g.h.lD=function(){var a=I0(this);i0(this.context.logger,8,a.l,a.i.sL);var b=g.Gt();b&&a&&kZ(b,[a.D,a.u])};
g.h.kD=function(){var a=g.Gt(),b=I0(this);a&&b&&lZ(a,[b.D])};
g.h.jD=function(a){var b=I0(this),c=g.Gt();this.g?a?(a=this.context.logger,i0(a,9,b.l,b.i.hs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.pt(c,b.D)):(a=this.context.logger,i0(a,12,b.l,b.i.hs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.pt(c,b.u)):(a=this.context.logger,h0(a,this.P,12,b.i.hs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.pt(c,this.H))};
var E0={collaborator:T_,donation:V_,episode:a0,movie:a0,playlist:W_,poll:X_,productListing:Y_,simple:U_,tip:Z_,video:$_};g.r(J0,A0);J0.prototype.hn=function(){A0.prototype.hn.call(this);zna(this)};
J0.prototype.show=function(){A0.prototype.show.call(this);var a=g.Gt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&kZ(a,[g.lt(b.itct)])};
J0.prototype.hide=function(){A0.prototype.hide.call(this);var a=g.Gt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&lZ(a,[g.lt(b.itct)])};g.r(K0,J0);g.h=K0.prototype;g.h.oL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.xi(a);this.g||(g.vi(a,e.width),g.vi(b,e.width));g.ei(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ei(c,"right","1px");this.o=!0;g.yi(a,!0);this.A=new g.L(function(){g.J(this.ha(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.LC=function(a,b){g.Jo(this.ha(),"iv-branding-active");this.C=new g.L((0,g.y)(function(){g.yi(a,!1);this.g||g.vi(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){J0.prototype.show.call(this);if(!this.D){g.J(this.ha(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.we("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.yi(this.i,!1);var b=g.we("DIV","branding-img-container",this.i);this.ha().appendChild(b);var c=g.we("DIV","iv-branding-context-name");g.Le(c,a.channel_name);var d=g.we("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.rV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.g),this.g.X(d);b=g.we("DIV","iv-branding-context-subscribe-caret");c=g.we("DIV","branding-context-container-inner",b,c,d);g.yi(c,!1);d=g.we("DIV","branding-context-container-outer",c);g.ei(d,"right",this.u+"px");this.ha().appendChild(d);var e=this.annotation.Ib();e&&this.hi(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.L(g.Va(this.LC,c,d),500,this);g.G(this,this.l);this.context.i.ca(this.ha(),"mouseover",(0,g.y)(this.oL,this,c,d,b,a.image_height));this.context.i.ca(this.ha(),"mouseout",(0,g.y)(this.l.start,this.l,void 0));this.D=!0}e0(this.context.logger,this.annotation.g);g.yi(this.ha(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=XY(a).width;c=g.Ha(void 0)?void 0:b;g.mi(a,c);f=new iZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,jma);g.G(this,f);this.context.o.ca(f,
"begin",g.Va(g.yi,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(J0.prototype.hide.call(this),g.yi(this.ha(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);J0.prototype.destroy.call(this)};g.r(L0,J0);g.h=L0.prototype;g.h.show=function(){this.isActive||(J0.prototype.show.call(this),this.H||(Ana(this),this.H=!0),g.yi(this.ha(),!0),this.annotation&&this.annotation.g&&e0(this.context.logger,this.annotation.g),g.kh(function(){g.Jo(this.ha(),"iv-promo-inactive")},100,this),this.ha().removeAttribute("aria-hidden"),this.isActive=!0,O0(this),N0(this),P0(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ha(),"iv-promo-inactive"),this.isActive=!1,this.ha().setAttribute("aria-hidden",!0))};
g.h.Rl=function(a,b,c,d,e,f,k){return this.u?!1:J0.prototype.Rl.call(this,a,b,c,d,e,f,k)};
g.h.zp=function(a,b){b.stopPropagation();N0(this);P0(this,a);this.g.focus()};
g.h.oC=function(a){this.F=!0;this.zp(500,a)};
g.h.nC=function(){this.F=!1;M0(this)};
g.h.fC=function(a){a.stopPropagation();this.hide();g0(this.context.logger,this.annotation.g)};
g.h.gC=function(a){a.stopPropagation();O0(this);this.u=!0;g.J(this.ha(),"iv-promo-collapsed-no-delay");this.A.start();g0(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();J0.prototype.destroy.call(this)};g.r(Q0,g.sK);g.h=Q0.prototype;g.h.Wb=function(a,b){if(!R0(g.V(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Lo(b);c&&W0(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(F0(this.g,b),WY(this.player)),!0}return null};
g.h.getOptions=function(){return R0(g.V(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.ur=function(){if(this.o){var a=g.RJ(this.player).getVideoContentRect(!0);g.wi(this.o.element,a.width,a.height);g.mi(this.o.element,a.left,a.top)}if(this.g){var b=g.YJ(this.player);a=this.g;b=b.width;g.K(a.C,"iv-drawer-small",426>=b);g.K(a.C,"iv-drawer-big",1280<=b)}};
g.h.WI=function(a){this.dc(a.state);g.U(a.state,2)&&(this.md()&&this.qe()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.gi(!1))};
g.h.load=function(){g.sK.prototype.load.call(this);this.dc(g.QJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.y)(this.FH,this,b,this.H),d=(0,g.y)(function(){this.C=null},this);
g.Ws()&&(c=X0(this,c));c={format:"XML",Rc:c,onError:d,yc:{}};a.isPharma&&(c.yc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.V(this.player);"gaming"==d.playerStyle&&(c.yc.gaming="1");(b=d.K.get(b))&&Y0(c,b);b=b&&(b.Vk||b.Uk);if(!a.Jk||b)a.wd?S0(this,a.wd,c):(this.l=(0,g.y)(this.KD,this,c),this.player.addEventListener("videodatachange",this.l));g.gK(this.player,this.o.element,4);this.ur()};
g.h.dc=function(a){a=!a.isCued()&&!g.U(a,1024);g.oC(this.u,a);g.oC(this.o,a)};
g.h.KD=function(a){var b=this.player.getVideoData();b.wd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),S0(this,b.wd,a))};
g.h.unload=function(){kna(this.D);g.cK(this.player,"annotations_module");g.Zb(this.i,function(a){a.destroy()});
g.Zb(this.K,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,WY(this.player));this.N=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.K={};this.u.hide();g.sK.prototype.unload.call(this);g.nC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.FH=function(a,b,c){this.C=null;if(!U0(this,b,a)&&(a=g.Rq(c)&&c.responseXML?c.responseXML:null)){W0(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.TD(c,e,f);a.push(b)}}g.$J(this.player,a)}};
g.h.vy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Fna(this):this.load())};
g.h.HD=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,Z0(this,a),e0(this.D,b.g))};
g.h.ID=function(a){$0(this,a.getId())};
g.h.Jv=function(a){a&&(a.hide(),b1(this,"shown",!1,a.annotation.id),this.il(a.annotation,"hidden"))};
g.h.Cz=function(a){a&&(a.show(),b1(this,"shown",!0,a.annotation.id),this.il(a.annotation,"shown"))};
g.h.jK=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;q_(d.annotation,function(a){e=e||a.value});
Ina(this,a,b,e)}};
g.h.JG=function(a){if(a&&a.id){var b=a.Ib();if(b){var c=ZZ(b);if(c){var d=(0,g.y)(this.il,this,a,"click");if("new"==z0(c,b.target)||a1(this,b))d(),d=null;f0(this.D,a.g,d)}}}};
g.h.il=function(a,b){Wma(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!a1(this,c.url))){e=y0(c.url);var f=ona(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=V0(this).g,g.wX(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&V0(this).g.Zb()&&V0(this).g.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.V(this.player),(d=ZZ(c.url))?(f=w0(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Va(pna,e.pageId,e.kc),d=new g.Cn(d),e=e(d.i),d.i=e,d=d.toString())):d=null,
d&&(this.player.pauseVideo(),c=z0(d,c.url.target),e=a.itct,"ei"in g.Wq(d)&&(d=g.Nh(d,"ei")),g.fM(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.NH=function(){b1(this,"playerControlShow",!1)};
g.h.OJ=function(){b1(this,"playerControlShow",!0)};
g.h.JD=function(a){b1(this,"rollOver",!0,a.id)};
g.h.hg=function(a){b1(this,"rollOver",!1,a.id)};
g.h.mH=function(a){a&&a.id&&(this.i[a.id].l=!0,$0(this,a.id),g0(this.D,a.g),this.il(a,"close"),b1(this,"closed",!0,a.id))};
g.h.md=function(){return!!this.g&&this.g.isAvailable()};
g.h.qe=function(){this.md();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.md();this.g&&(a?c?B0(this.g,c,b):B0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):C0(this.g))};
g.h.gi=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.V(this.player).K.unsubscribe("vast_info_card_add",this.vy,this);g.Jo(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.O,b=0,c=a.length;b<c;b++)g.Xs(a[b]);this.O.length=0;g.sK.prototype.T.call(this)};g.xU.annotations_module=Q0;g.xU.creatorendscreen=GZ;})(_yt_player);
