(function(g){var window=this;var e1=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.Kz(a),kind:a.o,name:a.u,id:a.Ca,is_servable:a.F,is_default:a.isDefault,is_translateable:a.C,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},f1=function(a){return a.g?a.g.languageCode:a.i},Lna=function(a,b){var c=new g.Jz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.A=a.A;c.D=a.D;c.g=b;return c},g1=function(a){if(!Mna.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Nna,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Ona=function(){this.i=[];
this.g=[]},h1=function(a,b){return b?a.g.concat(a.i):a.g},i1=function(a,b){switch(b.o){case "asr":var c=a.i;
g.cb(c,(0,g.y)(b.yq,b))||c.push(b);break;default:c=a.g,g.cb(c,(0,g.y)(b.yq,b))||c.push(b)}},j1=function(){g.F.call(this);
this.i=new Ona;this.u=[]},k1=function(a,b,c){j1.call(this,a);
this.g=null;this.u=b.Ut;this.l=c},l1=function(){this.Ua=[]},m1=function(a,b,c,d,e,f){g.F.call(this);
this.N=a;this.o=b;this.A=new l1;this.g=null;this.F=d;this.K=f;this.i=this.l=null;this.D=c;this.C=e||!1;this.H=new g.L(this.ew,1E3,this);g.G(this,this.H);this.u=new g.vs(this);g.G(this,this.u);g.P(g.V(b).experiments,"html5_disable_captions_seek_complete")?this.u.J(b,"seekto",this.Nw):this.u.J(b,"seekcomplete",this.KE);this.Nw(b.getCurrentTime());this.ew()},n1=function(a,b){b-=a.o.sc();
var c=a.g;a.g=g.Za(a.D.xe(b).g);c!=a.g&&a.K&&a.K()},o1=function(a,b){var c=g.$v(b,a.N,{}).Ib(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.i=g.Ir(c,d,3,100).then((0,g.y)(a.uJ,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.xb(c.Ua,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ua[e-1]&&e<c.Ua.length&&1==c.Ua[e]-d?(g.jb(c.Ua,e),g.jb(c.Ua,e-1)):0<e&&1==d-c.Ua[e-1]?c.Ua[e-1]=d:e<c.Ua.length&&1==c.Ua[e]-d?c.Ua[e]=d:(g.sb(c.Ua,e,0,d),g.sb(c.Ua,e+1,0,d)))},p1=function(a,b){j1.call(this,g.V(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.uz(g.V(this.C))&&!this.g.i},q1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.qU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Jz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Pna=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},r1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.qU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},s1=function(a,b,c,d,e){j1.call(this,e||null);
c=c||g.Wq(a).hl||"";c=c.split("_").join("-");this.o=g.Yq(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},t1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.TD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.i=k},u1=function(a,b,c,d,e){g.TD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},w1=function(a){a=void 0===a?{}:a;
var b="_"+v1++;return new u1(0,0x8000000000000,0,b,a)},y1=function(a,b,c,d,e,f,k){var l={};
g.Wa(l,b);g.Wa(l,a.params);g.Wa(l,c);var m={};g.Wa(m,b.ub);a.params.ub&&g.Wa(m,a.params.ub);g.Wa(m,c.ub);l.ub=m;g.T.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==l.kg?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},I:[{B:"span",G:"captions-text"}]});this.o=[];this.Y=!1;this.l=a;this.D=[];this.K=[];this.Sa=e;this.Qa=f;this.Oa=k;this.A=this.H=null;this.ea=.96*e;this.wa=.96*f;this.i=l;this.Ha=c;this.u=this.g["captions-text"];this.Aa=null!=this.u.style["box-decoration-break"]||
null!=this.u.style["-webkit-box-decoration-break"];this.W=d/360*16;this.type=0;this.la=this.W*x1(m);a=new g.Bs(this.element,!0);g.G(this,a);a.subscribe("dragstart",this.JE,this);a.subscribe("dragmove",this.IE,this);a.subscribe("dragend",this.HE,this);this.sa=this.na=0;b="";this.i.windowOpacity&&(a=g1(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":Qna[this.i.textAlign]};this.Aa&&(a["border-radius"]=
b?this.la/8+"px":"");if(this.C=!g.P(this.Oa,"web_player_vertical_and_ruby_captions_killswitch")&&(2==this.l.params.kg||3==this.l.params.kg))b=this.element,c="vertical-rl",1==this.i.Lz&&(c="vertical-lr"),g.qe&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.ei(b,"-o-writing-mode",c),g.ei(b,"-webkit-writing-mode",c),g.ei(b,"writing-mode",c),g.ei(b,"text-orientation","upright"),3==this.l.params.kg&&(g.ei(b,"text-orientation",""),g.ei(b,"transform","rotate(180deg)"));g.ei(this.element,a);switch(this.i.Df){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},x1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},z1=function(a,b){var c={},d=b.background?b.background:a.i.ub.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.ub.backgroundOpacity;d=g1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.W*x1(b)+"px";d=1;e=b.color||a.i.ub.color;if(b.color||null!=b.textOpacity)e=g1(e),d=null==b.textOpacity?a.i.ub.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.du&&(k=e=b.du);var l=a.W/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),u=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=u;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.qr()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.ub.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ee&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.Al&&(c.visibility="hidden");return c},A1=function(a,b,c){a.Y=a.Y||!!c;
var d={};g.Wa(d,a.i.ub);g.Wa(d,c||b.i);g.Wa(d,a.Ha.ub);c=a.D[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.Al==!!c.Al&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.D.length;e++)if(g.pc(d,a.D[e])){var f=a.K[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ye("SPAN");g.ei(f,z1(a,e));a.K[0].appendChild(f);e=1}a.K.length=e;a.D.length=e}else a.K.length=0,a.D.length=0,f=g.ye("SPAN"),g.ei(f,z1(a,d)),a.u.appendChild(f);k=!d.Al;e=(c=g.t(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.o.length||!b.l){if(0<l||0!=a.o.length){var n=g.ye("BR");f.appendChild(n)}k&&a.No(f)}m&&(k?a.H:f).appendChild(c?g.ze(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.ei(k[c],z1(a,d)),g.ei(k[c],"font-size","50%");a.D.push(d);a.K.push(f);a.o.push(b)},B1=function(){},D1=function(){this.o=this.i=this.mode=this.l=0;
this.u=new C1(this);this.A=new C1(this);this.g=[];this.clear()},Rna=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Mk:a,
Nk:b,result:0};a=E1[a];b=E1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Mk:a,Nk:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Mk:a,Nk:b,result:2};return{Mk:a,Nk:b,result:3}},Sna=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,F1(a.u,b,c,d))},Tna=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Sna(a,d.Wt,d.Xt,b):1==d.type&&a.l&496&&F1(a.A,d.Wt,d.Xt,b)}a.g.length=0},G1=function(){this.g=0},H1=function(){this.i=this.l=this.g=0},I1=function(){this.timestamp=this.Fd=0},J1=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new I1}this.g=this.i=this.row=0;this.style=new G1;this.u=a;this.o=0},K1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var u=a.l[m][p];
if(0!=u.Fd){0==c&&(c=m,d=p);n=String.fromCharCode(u.Fd);var x=u.timestamp;x<e&&(e=x);u.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==u.Fd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],u=p.Fd,0!=u&&(0==c&&(c=k,d=m),n=String.fromCharCode(u),x=p.timestamp,x<=e&&(e=x),l+=n,p.reset()),32==m||0==u)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Yna=function(a,b){switch(a){case 0:return Una[(b&127)-32];
case 1:return Vna[b&15];case 2:return Wna[b&31];case 3:return Xna[b&31]}return 0},L1=function(a){return a.l[a.row][a.i]},M1=function(a,b,c){2<=b&&1<a.i&&(--a.i,L1(a).Fd=0);
var d=L1(a);d.timestamp=a.u.i+0;d.Fd=Yna(b,c);32>a.i&&a.i++},N1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].Lf(a.l[c+e][f])},O1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},P1=function(a){a.row=0<a.g?a.g:1;
a.i=1;O1(a,0,15)},Q1=function(a){this.o=a;
this.u=0;this.style=new G1;this.A=new J1(a);this.C=new J1(a);this.D=new J1(a);this.i=this.A;this.l=this.C;this.g=this.i},R1=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:K1(d,c),P1(a.i),P1(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(K1(d,c),O1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},S1=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},T1=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},C1=function(a){this.i=a;
this.g=new H1;this.u=0;this.l=new Q1(a);this.A=new Q1(a);this.o=this.l},F1=function(a,b,c,d){a.g.update();
b=Rna(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Mk;c=b.Nk;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&M1(a,0,b),c&96&&M1(a,0,c),0!=b&&0!=c&&3==a.style.g&&K1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;N1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));O1(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:M1(b.g,0,32);break a;case 48:57==c?(b=b.g,L1(b).Fd=0,32>b.i&&b.i++):M1(b.g,1,c&15)}break;case 2:c&32&&M1(b.g,2,c&31);break;case 3:c&32&&M1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:S1(b);break;case 33:b=
b.g;1<b.i&&(--b.i,L1(b).Fd=0);break;case 36:b=b.g;d=L1(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.l[a][c]==d){for(;32>=c;c++)b.l[a][c].reset();break}break;case 37:R1(b,2,d);break;case 38:R1(b,3,d);break;case 39:R1(b,4,d);break;case 40:M1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);P1(d);T1(b);break;case 43:T1(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:K1(a,d)}O1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;K1(a,d);N1(a,b,b+1,a.g-1);O1(a,a.row,1)}break;case 46:O1(b.l,0,15);break;case 47:K1(b.i,d);d=b.l;a=b.o.i+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.l[c][e].timestamp=a;d=b.l;b.l=b.i;b.i=d;S1(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.i+=c&3)&&(b.i=32)}}},U1=function(a){g.F.apply(this,arguments)},V1=function(a,b){U1.call(this);
this.N=b;this.o={};this.F={};this.H={};this.u="_"+v1++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},W1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},X1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},Y1=function(a,b){var c=W1(a,b);
return void 0!=c?c:null},$1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Z1.test(c),c},a2=function(a,b){var c={},d=b.getAttribute("ws");
g.Wa(c,d?a.H[d]:a.A);d=Y1(b,"mh");null!=d&&(c.pq=d);d=Y1(b,"ju");null!=d&&(c.textAlign=d);d=Y1(b,"pd");null!=d&&(c.kg=d);d=Y1(b,"sd");null!=d&&(c.Lz=d);d=$1(b,"wfc");null!=d&&(c.windowColor=d);d=W1(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},b2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Wa(c,a.F[d]);d=Y1(b,"ap");null!=d&&(c.Df=d);d=W1(b,"cc");null!=d&&(c.iu=d);d=W1(b,"ah");null!=d&&(c.Ge=d);d=W1(b,"rc");null!=d&&(c.Jr=d);d=W1(b,"av");null!=d&&(c.mg=d);return c},c2=function(a,b,c,d){var e={};
g.Wa(e,b2(a,b));g.Wa(e,a2(a,b));d?g.pc(e,a.A)?(d=a.u,e=a.A):d="_"+v1++:d=b.getAttribute("id")||"_"+v1++;a=W1(b,"t")+c;b=W1(b,"d")||0x8000000000000;return new u1(a,b,0,d,e)},d2=function(a,b,c,d,e,f,k){y1.call(this,a,b,c,d,e,f,k);
this.type=1},e2=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},f2=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},g2=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},h2=function(a,b){U1.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new D1;this.g.l=1<<this.track},j2=function(a){if(g.t(a))return!1;
a=new e2(a,8,0);return i2(a)},i2=function(a){if(!(a.g<a.i.byteLength)||1380139777!=g2(a))return!1;
a.version=f2(a);if(1<a.version)return!1;f2(a);f2(a);f2(a);return!0},k2=function(a,b,c,d,e,f,k){y1.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.R=this.O=this.ba=0;this.P=NaN;this.xa=0;this.Da=null;this.ia=new g.L(this.zJ,433,this);g.G(this,this.ia)},Zna=function(a,b){return(a.C?b.offsetHeight:b.offsetWidth)+1},$na=function(a){if(isNaN(a.P)){var b=a.i.iu;
if(b){var c=g.ye("SPAN");g.Le(c,"\u2013".repeat(b));g.ei(c,z1(a,a.i.ub));a.u.appendChild(c);a.P=c.offsetWidth;a.u.removeChild(c)}else a.P=0}return a.P},aoa=function(a,b){if(!b)return"";
a.C&&1!=a.l.params.Lz&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},l2=function(a){a.F=Array.prototype.slice.call(g.je("ytp-rollup-caption-line-wrapper"));
for(var b=a.l.params.Jr,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.O=d;a.R=Math.max($na(a),a.xa,Zna(a,a.u))},boa=function(a,b){l2(a);
var c=a.F.reduce(function(b,c){return(a.C?c.offsetWidth:c.offsetHeight)+b},0);
c=a.O-c;if(c!=a.ba){var d=0<c&&0==a.ba;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.So(a.ia));g.ei(a.u,"transform",aoa(a,c));a.ba=c}l2(a)},m2=function(){U1.call(this)},n2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ee=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new t1(b,c,d,e.id,p.nodeValue,f||0<n,g.lc(l)?void 0:l);m.push(p);var u=e;g.G(u,p);u.i.push(p)}else u={},g.Wa(u,l),n2(a,b,c,d,e,!0,p,u,m)}},o2=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},p2=function(a,b,c,d){d=Object.assign({pq:0},d);
return new u1(a,b,c,"_"+v1++,d)},q2=function(a){g.F.call(this);
this.i=a;this.g=null},t2=function(a){g.sK.call(this,a);
this.u=g.V(a);this.l=a.getVideoData();this.wa=g.RJ(a);this.N=a;var b=null,c=g.Ep("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.op(c));this.Y=b;this.o={ub:{}};this.A={ub:{}};this.H=[];this.O={};this.Z={};this.K=!1;this.na=g.rU(this.l,this.N);this.xa=!!this.l.captionTracks.length;this.Aa=!!this.l.Pi;this.la="3"==this.u.o;b=a.app.u;c=!(!b||!b.pk());this.sa=!(!b||!b.gh());this.C=this.la&&c&&!this.na;this.P=!this.C&&this.la&&this.sa&&this.na;this.i=this.D=this.F=this.R=this.ia=null;this.W=
new q2(this.u);g.G(this,this.W);c=b=this.g=null;this.C||(b=new g.Po(this.cA,void 0,this),g.G(this,b),c=new g.L(this.VK,2E3,this),g.G(this,c));this.ga=b;this.ba=c;this.aa=new g.vs(this);g.G(this,this.aa);this.C||this.aa.J(a,"resize",this.ws);this.aa.J(a,"onPlaybackAudioChange",this.TG);this.aa.J(a,g.WD("captions"),this.TD,this);this.aa.J(a,"crx_captions",this.UD,this);r2(this,s2(this,"display-settings")||{})},u2=function(a){if(1==a.u.Hf||1==a.l.Hf||"alwayson"==g.MB(a.l,"yt:cc"))return!0;
if(2==a.u.Hf){var b=s2(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().Co;return"ON"==c||"on"==g.MB(a.l,"yt:cc")},v2=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.ll||"FORCED_ON"==c.Co},x2=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Aa?!1:a.xa?!1:!0);c=h1(a.i.i,c);for(var d=[a.l.Gf,a.u.Gf,g.MB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(f1(c[f])==d[e])return c[f];return a.D&&a.D.Po?a.D.Po:(d=c.find(function(a){return a.isDefault}))?d:c[0]||w2(a)}return null},w2=function(a){return a.D&&a.D.ll},y2=function(a){var b=w2(a);
return!!b&&a.g==b},z2=function(a,b){for(var c=a.N.app.u.ha().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},B2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&A2(a,"module-enabled",!!b));a.g=b;v2(a)&&(a.g=w2(a));a.load()},coa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.pq?b.params.pq:1<b.i.length?1:0){case 1:return new d2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new k2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new y1(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},r2=function(a,b,c){var d=C2.ub;
a.o={};g.Wa(a.o,C2);a.o.ub={};g.Wa(a.o.ub,d);a.A={ub:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;Z1.test(f);e.ub.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;Z1.test(f);e.ub.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||C2.windowColor;Z1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ub.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.ub.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Ee?3:d.bold?1:d.Ee?2:0);f=f.ub;switch(e){case 1:f.bold=!0;delete f.Ee;break;case 2:delete f.bold;f.Ee=!0;break;case 3:f.bold=!0;f.Ee=!0;break;default:delete f.bold,delete f.Ee}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ub.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=C2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.ub.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ub.fontFamily=f;a.loaded&&a.ws();c&&A2(a,"display-settings",b)},E2=function(a,b){if(b&&!a.F){var c=w1({kg:0,
lang:"pt-BR"});a.F=[c,new t1(c.start,c.end-c.start,0,c.id,"As legendas ficam assim")];g.$J(a.player,a.F)}else!b&&a.F&&(D2(a,a.F),a.F=null)},D2=function(a,b){g.bK(a.player,b);
(0,g.A)(b,function(a){g.kb(this.H,a)},a);
a.ga.oj()},s2=function(a,b){if(!a.Y)return null;
try{var c=a.Y.get(b)}catch(d){a.Y.remove(b)}return c},A2=function(a,b,c){if(a.Y)try{a.Y.set(b,c)}catch(d){}};
g.eE.prototype.Ri=g.ca(13,function(){for(var a=g.ie(document,"track",void 0,this.g),b=0;b<a.length;b++)g.De(a[b])});
g.gW.prototype.Ri=g.ca(12,function(){this.g.Ri()});
g.eE.prototype.pk=g.ca(11,function(){return!!this.g.textTracks});
g.gW.prototype.pk=g.ca(10,function(){return this.g.pk()});
g.eE.prototype.Ki=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.gW.prototype.Ki=g.ca(8,function(a){this.g.Ki(a)});
g.VC.prototype.gh=g.ca(7,function(){});
g.eE.prototype.gh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.gW.prototype.gh=g.ca(5,function(){return this.g.gh()});
g.Jz.prototype.yq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Rt.prototype.vl=g.ca(2,function(a){return(a=this.Qf(a))?a.i:0});
g.Kw.prototype.vl=g.ca(1,function(){return 0});
var doa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Nna=/#(.)(.)(.)/,Mna=/^#(?:[0-9a-f]{3}){1,2}$/i,Z1=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(j1,g.F);j1.prototype.Ky=function(){return!1};
j1.prototype.T=function(){this.ng();g.F.prototype.T.call(this)};
g.r(k1,j1);k1.prototype.lq=function(a,b,c){b=this.kj(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.ng();this.g=g.hr(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
k1.prototype.mq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())i1(this.i,c.value);a()};
k1.prototype.kj=function(a,b){var c=a.Ib(),d={fmt:b};a.g&&(d.tlang=f1(a));return g.Yq(c,d)};
k1.prototype.ng=function(){this.g&&this.g.abort()};
l1.prototype.contains=function(a){a=g.xb(this.Ua,a);return 0<=a||0>a&&1==(-a-1)%2};
l1.prototype.length=function(){return this.Ua.length/2};
g.r(m1,g.F);g.h=m1.prototype;g.h.T=function(){g.F.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.Nw=function(a){var b=this;if(this.D.Ig())var c=this.u.J(this.o,"progresssync",function(){b.D.index.Mb()&&(b.reset(),b.g=null,n1(b,b.o.getCurrentTime()),b.u.Ma(c))});
else n1(this,a)};
g.h.KE=function(){n1(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new l1;this.i&&(this.i.cancel(),this.i=null)};
g.h.ew=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.uf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.Qh(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||o1(this,a),this.g=g.Za(a.g)));this.H.start()};
g.h.uJ=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.Rw(a);c?(a=g.$v(this.l,this.N,{}),b=this.l,g.Vv(b.i,a,c),b.requestId=a.get("req_id"),o1(this,this.l)):(b||null===this.F||(this.C?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.sc())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.sc()))),this.i=this.l=null)};
g.r(p1,j1);g.h=p1.prototype;g.h.lq=function(a,b,c){this.ng();b=Pna(this,a.getId());b||(b=a.i,b=this.g.i?r1(this,b,"386"):r1(this,b));if(b){var d=1E3*(b.index.vl(b.index.de())-b.index.cd(b.index.de()));this.l=new m1(new g.pv,this.C,b,function(b,f){c(b,a,f,d)},this.A||g.iv(b.info),(0,g.y)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Ky=function(){var a=this.o;this.o=!1;return a};
g.h.mq=function(a){var b;this.A?b=[new g.Jz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Jz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?q1(this,"386"):q1(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())i1(this.i,c.value);a()};
g.h.ng=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.kj=function(){return""};
g.r(s1,j1);s1.prototype.lq=function(a,b,c){b=this.kj(a,b);var d=(0,g.y)(function(b){this.g=null;c(b.responseText,a)},this);
this.ng();this.g=g.hr(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
s1.prototype.mq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Yq(b,c);c=(0,g.y)(function(b){this.g=null;if((b=b.responseXML)&&b.firstChild){for(var c=g.q(b.getElementsByTagName("track")),d=c.next();!d.done;d=c.next()){var k=d.value;d=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),u="true"==k.getAttribute("lang_default"),x="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
i1(this.i,new g.Jz({languageCode:d,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:x,vss_id:k,is_default:u}))}b=b.getElementsByTagName("target");c=b.length;for(d=0;d<c;d++)l=b[d].getAttribute("lang_code"),m=b[d].getAttribute("lang_translated"),n=b[d].getAttribute("lang_original"),p=b[d].getAttribute("id"),u="true"==b[d].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:u},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.ng();this.g=g.hr(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
s1.prototype.kj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.u,kind:a.o,fmt:b};a.g&&(d.tlang=f1(a));return c=g.Yq(c,d)};
s1.prototype.ng=function(){this.g&&this.g.abort()};var Qna=["left","right","center","justify"];var C2={windowColor:"#080808",windowOpacity:0,textAlign:2,Df:7,Ge:50,mg:100,ub:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(t1,g.TD);t1.prototype.toString=function(){return g.TD.prototype.toString.call(this)};g.r(u1,g.TD);u1.prototype.toString=function(){return g.TD.prototype.toString.call(this)};
var v1=0;g.r(y1,g.T);g.h=y1.prototype;g.h.JE=function(a,b){var c=g.ui(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.IE=function(a,b){var c=g.xi(this.element),d=a-this.na-.02*this.Sa,e=b-this.sa-.02*this.Qa,f=(d+c.width/2)/this.ea*3;f=Math.floor(g.Ud(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.Ud(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ea;d=100*g.Ud(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.Ud(c,0,1);this.l.params.Df=l;this.l.params.mg=c;this.l.params.Ge=d;this.i.Df=l;this.i.mg=c;this.i.Ge=d;this.ez()};
g.h.HE=function(){g.Jo(this.element,"ytp-dragging")};
g.h.ez=function(){this.ah(this.o)};
g.h.ah=function(a){var b=Math.min(this.ev(),this.ea),c=this.dv(),d="";3==this.l.params.kg&&(d="rotate(180deg)");g.ei(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.qo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Ge+2;d=this.i.Df;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.u.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.mg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ei(this.element,a)};
g.h.qo=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.Y||this.o.length>b)b=0,this.Y=!1,this.o=[],this.D=[],this.K=[],this.H=this.A=null,g.Be(this.u);for(;b<a.length;b++)A1(this,a[b])};
g.h.ev=function(){return 0};
g.h.dv=function(){return 0};
g.h.No=function(a){this.A=g.ye("SPAN");this.A.appendChild(g.ze("\u00a0"));this.H=g.ye("SPAN");g.J(this.H,"caption-visual-line");this.A.appendChild(this.H);this.A.appendChild(g.ze("\u00a0"));a.appendChild(this.A)};
g.h.toString=function(){return g.T.prototype.toString.call(this)};B1.prototype.u=function(){};D1.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
D1.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var E1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];G1.prototype.set=function(a){this.g=a};
G1.prototype.get=function(){return this.g};
H1.prototype.clear=function(){this.g=0};
H1.prototype.update=function(){this.g=2==this.g?1:0};
H1.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
I1.prototype.Lf=function(a){this.Fd=a.Fd;this.timestamp=a.timestamp};
I1.prototype.reset=function(){this.timestamp=this.Fd=0};
J1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Fd?a+"_":a+String.fromCharCode(d.Fd)}a+="\n"}return a};
J1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Una=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Vna=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Wna=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Xna=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Q1.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
C1.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.r(U1,g.F);U1.prototype.reset=function(){};g.r(V1,U1);V1.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
V1.prototype.l=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.o,l={},m=c.getAttribute("p");m&&g.Wa(l,this.o[m]);m=X1(c,"b");null!=m&&(l.bold=
m);m=X1(c,"i");null!=m&&(l.Ee=m);m=X1(c,"u");null!=m&&(l.underline=m);m=Y1(c,"et");null!=m&&(l.charEdgeStyle=m);m=Y1(c,"of");null!=m&&(l.offset=m);m=$1(c,"bc");null!=m&&(l.background=m);m=$1(c,"ec");null!=m&&(l.du=m);m=$1(c,"fc");null!=m&&(l.color=m);m=Y1(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=W1(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=W1(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=W1(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=Y1(c,"rb");null!=c&&(l.aL=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.H[d]=a2(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=b2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=c2(this,d,e,!1);g.G(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.u;m=!!X1(d,"a");n=(W1(d,"t")||0)+n;var p=W1(d,"d")||5E3;m||(!this.C&&
this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var u=m?6:5,x=this.o[d.getAttribute("p")],C=d.childNodes;C.length&&(this.C=null!=d.getAttribute("d"));for(var E=0;E<C.length;E++){var H=C[E];0<E&&(m=!0);var R=void 0;1==H.nodeType&&(R=H);if(R&&"s"==R.tagName)if((H=this.o[R.getAttribute("p")])&&1==H.aL&&!g.P(this.N.experiments,"web_player_vertical_and_ruby_captions_killswitch")){H=n;var W=p,ra=l,wb=m,Fb=u;var Oc=R;var $f=C[E+1],Dh=C[E+2],Ec=C[E+3];
Oc.getAttribute("p");W1(Oc,"t");W1($f,"t");W1(Dh,"t");W1(Ec,"t");R=g.ye("RUBY");Oc=Oc.textContent;var Jk=g.ye("SPAN");Jk.innerText=Oc;R.appendChild(Jk);$f.getAttribute("p");Jk=g.ye("RP");Oc=$f.textContent;Jk.innerText=Oc;R.appendChild(Jk);Dh.getAttribute("p");Oc=Dh.textContent;$f=g.ye("RT");$f.innerText=Oc;R.appendChild($f);Ec.getAttribute("p");Oc=Ec.textContent;Ec=g.ye("RP");Ec.innerText=Oc;R.appendChild(Ec);H=new t1(H,W,Fb,ra,R,wb,null);E+=3}else Ec=R,H=n,W=p,ra=l,wb=m,Fb=u,R=Ec.textContent?Ec.textContent:
"",Oc=this.o[Ec.getAttribute("p")],Ec=W1(Ec,"t")||0,H=new t1(H+Ec,W-Ec,Fb,ra,R,wb,Oc);else H=new t1(n,p,u,l,H.textContent||"",m,x);k.push(H);this.i=H}if(0<k.length)for(k[0].windowId==this.u&&(this.g=c2(this,d,e,!0),g.G(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.G(l,k),l.i.push(k),c.push(k)}e=c}else e=[];return e};g.r(d2,y1);d2.prototype.qo=function(a){var b=this.l.i;y1.prototype.qo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i==e)var d=f;else{d={};g.Wa(d,c.i);g.Wa(d,eoa);var e=c.i;var f=d}A1(this,c,d)}};
var eoa={Al:!0};g.r(e2,B1);e2.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+v1++;c=c/1E3-this.C;d=d/1E3-this.C;a=new u1(c,d-c,5,f,{textAlign:0,Df:0,Ge:2.5*b,mg:5.33*a});e=new t1(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.r(h2,U1);h2.prototype.l=function(a){a=new e2(a,a.byteLength,this.i);if(i2(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=g2(a)*(1E3/45):1==a.version&&(a.o=4294967296*g2(a)+g2(a)),a.A=f2(a);0<a.A;a.A--){var b=f2(a),c=f2(a),d=f2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Wt:c,Xt:d,order:b.g.length}))}Tna(this.g,a);return a.l}return[]};
h2.prototype.reset=function(){this.g.clear()};g.r(k2,y1);g.h=k2.prototype;g.h.ez=function(){g.To(this.ia)};
g.h.zJ=function(){g.Jo(this.element,"ytp-rollup-mode");this.ah(this.Da,!0)};
g.h.dv=function(){return this.C?this.R:this.O};
g.h.ev=function(){return this.C?this.O:this.R};
g.h.No=function(a){y1.prototype.No.call(this,a);g.J(this.A,"ytp-rollup-caption-line-wrapper");g.ei(this.A,"display","inline-block");g.ei(this.H,"display","inline-block")};
g.h.ah=function(a,b){this.Da=a;if(this.l.params.Jr){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));this.xa=this.R;this.O=this.R=0;y1.prototype.ah.call(this,a);boa(this,b);y1.prototype.ah.call(this,a)}else y1.prototype.ah.call(this,a)};g.r(m2,U1);
m2.prototype.l=function(a,b){for(var c=[],d=a.split(foa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!goa.test(f)){var l=F2.exec(f);if(l&&4<=l.length){var m=o2(l[1]),n=o2(l[2])-m;m+=k;var p,u=p=void 0,x=void 0,C=void 0,E=l[3];l={textAlign:2};E=g.q(E?E.split(" "):[]);for(var H=E.next();!H.done;H=E.next())if(H=H.value.split(":"),2==H.length){var R=H[1];switch(H[0]){case "line":H=R.split(",");H[0].endsWith("%")&&(C=H[0],l.mg=Number.parseInt(C,10),2==H.length&&(x=H[1].trim()));break;case "position":H=R.split(",");
u=H[0];l.Ge=Number.parseInt(u,10);2==H.length&&(p=H[1].trim());break;case "align":switch(R){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}C||(l.mg=100,x||(x="end"));if(!u)switch(l.textAlign){case 0:l.Ge=0;break;case 1:l.Ge=100;break;default:l.Ge=50}u=0;switch(x){case "center":u+=3;break;case "end":u+=6;break;default:u+=0}switch(p){case "line-left":u+=0;break;case "center":u+=1;break;case "line-right":u+=2;break;default:switch(l.textAlign){case 0:u+=
0;break;case 2:u+=1;break;case 1:u+=2}}l.Df=0>u||8<u?7:u;p=l;f=f.substring(F2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=p2(m,n,5,u),n=new t1(m,n,5,k.id,p,!1,g.lc(f)?void 0:f),c.push(k),c.push(n),g.G(k,n),k.i.push(n);else for(x=p.split(hoa),1==x.length?(p=5,u=p2(m,n,p,u)):(C=p=6,u=Object.assign({iu:32},u),u=new u1(m,n,C,"_"+v1++,u)),c.push(u),C=m,l=0;l<x.length;l++)E=x[l],0==l%2?(H=g.Lo("<html>"+E+"</html>"),H.getElementsByTagName("parsererror").length?
(R=H.createElement("span"),R.appendChild(H.createTextNode(E))):R=H.firstChild,n2(this,C,n-(C-m),p,u,0<l,R,f,c)):C=o2(E)+k}F2.lastIndex=0}}return c};
var goa=/^NOTE/,foa=/(?:\r\n|\r|\n){2,}/,F2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),hoa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(q2,g.F);q2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
q2.prototype.reset=function(){this.g&&this.g.reset()};
q2.prototype.T=function(){this.clear();g.F.prototype.T.call(this)};g.r(t2,g.sK);g.h=t2.prototype;g.h.T=function(){if(this.C||this.P){var a=this.N.app.u;a&&a.Ri()}else E2(this,!1);g.sK.prototype.T.call(this)};
g.h.jk=function(){return this.la?this.C||this.P:v2(this)?!0:u2(this)};
g.h.load=function(){g.sK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.W.clear(),this.C?z2(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.lq(this.g,"srv3",(0,g.y)(this.dK,this))),this.g&&!y2(this)?this.player.ma("captionschanged",e1(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var a;this.na?a=new p1(this.l.ka,this.player):this.xa?a=new k1(this.u,this.l,this.player.getAudioTrack()):a=new s1(this.l.Pi,this.l.videoId,this.l.Gf||this.u.Gf||
g.MB(this.l,"yt:cc_default_lang")||this.u.Tb,this.l.Ao,this.u);this.i=a;g.G(this,this.i);a.mq((0,g.y)(this.cK,this))}};
g.h.unload=function(){this.C&&this.g?z2(this,!1):(this.ba&&g.Uo(this.ba),g.cK(this.player,"captions"),this.H=[],this.i&&this.i.ng(),this.W.clear(),this.F&&g.$J(this.player,this.F),this.ws());g.sK.prototype.unload.call(this);var a=g.X(this.player.app);a&&a.o&&g.JC(a.o.l);this.player.ma("captionschanged",{})};
g.h.cK=function(){var a;this.K||u2(this)?a=x2(this,this.K):v2(this)&&(a=w2(this));if(this.C||this.P){for(var b=h1(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Kz(e),srclang:f1(e),id:e.toString()};this.P||(f.src=this.i.kj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.we("TRACK",f))}this.N.app.u.Ki(c);a=this.N.app.u.ha();this.sa&&this.aa.J(a.textTracks,"change",this.eK)}else!this.g&&a&&B2(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.eK=function(){for(var a=this.N.app.u.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=h1(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&B2(this,b,!0)};
g.h.AL=function(){!this.g&&this.C||this.unload()};
g.h.dK=function(a,b,c,d){if(a){this.i.Ky()&&(this.H=[],g.cK(this.N,"captions"),this.ga.oj(),this.W.reset());var e=this.W;c=c||0;d=d||0;if(!g.t(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.lu(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!j2(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],u=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|u&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.t(a)){if("WEBVTT"==a.substring(0,6)){b=a;var x=c;e.g||(e.g=new m2);var C=e.g.l(b,x);.01>Math.random()&&g.oq(Error("Deprecated subtitles format in web player: WebVTT"));var E=C}else b:{C=a;x=g.Lo(C);if(!x||!x.firstChild)throw Error("Invalid caption track data: "+
C);if("timedtext"==x.firstChild.tagName){if(3==parseInt(x.firstChild.getAttribute("format"),10)){if(!e.g){C={};var H=f1(b);H&&(C.lang=H,doa.test(H)&&(C.kg=1));e.g=new V1(C,e.i)}E=e.g.l(x,c);break b}var R=Error("Unsupported subtitles format in web player (Format2)");R.params=C;throw R;}if("transcript"==x.firstChild.tagName)throw Error("Unsupported subtitles format in web player (Format1): "+C);throw Error("Invalid caption track data: "+C);}var W=E}else{E=a;x=c;H=d;if(!j2(E))throw Error("Invalid binary caption track data");
e.g||(e.g=new h2(H,b));W=e.g.l(E,x)}var ra=W}catch(wb){g.M(wb),e.clear(),ra=[]}else ra=[];g.$J(this.player,ra);!this.K||this.P||y2(this)||g.kz(this.u)||g.lz(this.u)||(g.Uo(this.ba),ra=w1({Df:0,Ge:5,mg:5,Jr:2,textAlign:0,kg:0,lang:"pt-BR"}),this.R=[ra],e=["Clique em "," para configura\u00e7\u00f5es"],this.ia||(W=new g.kC(g.oP()),g.G(this,W),this.ia=W.element),W=ra.end-ra.start,(b=g.Kz(this.g))&&this.R.push(new t1(ra.start,W,0,ra.id,b)),this.R.push(new t1(ra.start,W,0,ra.id,e[0]),new t1(ra.start,W,
0,ra.id,this.ia,!0),new t1(ra.start,W,0,ra.id,e[1],!0)),g.$J(this.player,this.R),g.So(this.ba));!this.K||this.P||y2(this)||(A2(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(ra=g.X(this.player.app))&&ra.o&&g.JC(ra.o.l));this.K=!1}};
g.h.TD=function(a){this.H.push(a);this.ga.oj()};
g.h.UD=function(a){g.kb(this.H,a);this.i instanceof p1&&this.i.A&&g.bK(this.player,[a]);this.ga.oj()};
g.h.PK=function(a){if(a instanceof u1){var b=this.O[a.id];b&&b.l!=a&&(b.dispose(),delete this.O[a.id],b=null);b||(b=coa(this,a))&&(this.O[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.VK=function(){D2(this,this.R);this.R=null};
g.h.cA=function(){this.ga.stop();g.mc(this.Z);this.H.sort(g.VD);var a=this.H;if(this.F){var b=(0,g.Fe)(a,function(a){return-1==this.F.indexOf(a)},this);
b.length&&(a=b)}(0,g.A)(a,this.PK,this);g.Zb(this.O,function(a,b){this.Z[b]?(a.element.parentNode||g.gK(this.player,a.element,4),a.ah(this.Z[b])):(a.dispose(),delete this.O[b])},this)};
g.h.ZK=function(){r2(this,{},!0)};
g.h.ZB=function(){var a=C2.ub;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ee?3:a.bold?1:a.Ee?2:0,textOpacity:a.textOpacity,windowColor:C2.windowColor,windowOpacity:C2.windowOpacity};var b=s2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.hA=function(a,b){var c={};g.Wa(c,s2(this,"display-settings"));g.Wa(c,a);r2(this,c,b);this.player.M("captionssettingschanged")};
g.h.ws=function(){!this.C&&this.loaded&&(g.Zb(this.O,function(a,b){a.dispose();delete this.O[b]},this),this.cA())};
g.h.Wb=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Ud(b,-2,4);this.hA({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&B2(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.tb&&A2(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.lc(b)){B2(this,null,!0);break}for(var d=h1(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?Lna(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||B2(this,c,!0)}else return this.loaded&&this.g&&!y2(this)?e1(this.g):{};return"";case "tracklist":return this.i?(0,g.D)(h1(this.i.i,!(!b||!b.includeAsr)),function(a){return e1(a)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.C||void 0==b||E2(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.tb&&a.push("stickyLoading");return a};
g.h.mj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.Tz=function(){this.loaded&&this.g&&!y2(this)?(A2(this,"module-enabled",!1),this.unload(),v2(this,!0)&&B2(this,w2(this),!1)):B2(this,y2(this)||!this.g?x2(this,!0):this.g,!0)};
g.h.TG=function(){var a=y2(this);v2(this,a)?B2(this,this.player.getAudioTrack().ll,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.jk()&&(a?B2(this,x2(this),!1):this.load()))};g.xU.captions=t2;})(_yt_player);
