(function(g){var window=this;var G2=function(a,b,c){var d=b.ua();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.qc(c?c:"mqdefault.jpg");var f=b instanceof g.mB&&b.lengthSeconds?g.RP(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.XD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.mB?b.oa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Li||g.MN("Assistir a $TITLE",{TITLE:b.title}),duration:f,url:b.nj(),is_live:l,
is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.ZD&&(d.playlist_length=b.getLength());a.update(d)},H2=function(a,b){g.pC.call(this,{B:"div",
V:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},I2=function(a){g.T.call(this,{B:"div",
V:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},I:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",I:[{B:"span",G:"ytp-upnext-header",U:"Pr\u00f3ximo"},{B:"span",G:"ytp-upnext-title",U:"{{title}}"},{B:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Reproduzir pr\u00f3ximo v\u00eddeo"},I:[{B:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},I:[{B:"circle",G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",I:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",
U:"Reprodu\u00e7\u00e3o autom\u00e1tica pausada"}]}]});this.u=null;var b=this.g["ytp-upnext-cancel"];this.u=new g.T({B:"button",V:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancelar reprodu\u00e7\u00e3o autom\u00e1tica"},U:"Cancelar"});g.G(this,this.u);this.u.ca("click",this.YG,this);this.u.X(b);this.i=a;this.H=this.g["ytp-svg-autoplay-ring"];this.C=this.A=this.l=this.o=null;this.D=new g.L(this.Xk,5E3,this);g.G(this,this.D);this.F=0;this.J(this.g["ytp-upnext-autoplay-icon"],
"click",this.RI);this.Lx();this.J(a,"autonavvisibility",this.Lx);this.J(a,"mdxnowautoplaying",this.eI);this.J(a,"mdxautoplaycanceled",this.fI);this.J(a,"mdxautoplayupnext",this.gA);3==this.i.getPresentingPlayerType()&&(a=(a=g.SJ(g.MJ(this.i)))?a.XB():null)&&this.gA(a)},J2=function(a,b){if(!a.l){g.Dq("a11y-announce","Pr\u00f3ximo "+a.o.title);
a.F=g.O();a.l=new g.L((0,g.y)(a.po,a,b),25);a.po(b);var c=b||g.Q(g.V(a.i).experiments,"autoplay_time")||1E4;a.i.ma("onAutonavCoundownStarted",c)}g.Jo(a.element,"ytp-upnext-autoplay-paused")},L2=function(a){K2(a);
a.F=g.O();a.po();g.J(a.element,"ytp-upnext-autoplay-paused")},K2=function(a){a.l&&(a.l.dispose(),a.l=null)},M2=function(a,b){b=void 0===b?!1:b;
if(g.P(g.V(a.i).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.o.ua(),a.Xk(),a.A=new Notification("Pr\u00f3ximo",{body:c.title,icon:c.qc()}),a.C=a.J(a.A,"click",a.II),a.D.start())}K2(a);a.i.nextVideo(!1,b)},N2=function(a){H2.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.i=new g.T({B:"div",G:"ytp-subscribe-card",I:[{B:"img",G:"ytp-author-image",L:{src:b.Xd}},{B:"div",G:"ytp-subscribe-card-right",I:[{B:"div",G:"ytp-author-name",U:b.author},{B:"div",G:"html5-subscribe-button-container"}]}]});g.G(this,this.i);this.i.X(this.element);this.l=new g.rV("Inscreva-se",null,"Cancelar assinatura",null,!0,!1,b.ih,b.subscribed,"trailer-endscreen",null,null,a);g.G(this,this.l);this.l.X(this.i.g["html5-subscribe-button-container"]);this.hide()},O2=function(a){var b=
g.V(a),c=g.nx||g.hi?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.T.call(this,{B:"a",V:e,L:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},I:[{B:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",I:[{B:"span",G:"ytp-videowall-still-info-bg",I:[{B:"span",G:"ytp-videowall-still-info-content",L:c,I:[{B:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{B:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",U:"Ao vivo"},{B:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{B:"span",V:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],I:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{B:"span",G:"ytp-videowall-still-listlabel-length",I:[" (",{B:"span",U:"{{playlist_length}}"},")"]}]},{B:"span",V:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],I:[{B:"span",
G:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.u=d;this.i=a;this.l=null;this.o=new g.vs(this);g.G(this,this.o);this.ca("click",this.C);this.ca("keypress",this.D);this.o.J(a,"videodatachange",this.A);g.V(a).F&&g.aL(a.app.R,this.element,this);this.A()},P2=function(a){g.jK(a.i,a.element);
var b=a.l.ua().videoId,c=a.l.getPlaylistId();g.wX(a.i.app,b,a.l.Sc,c,void 0,void 0,void 0)},Q2=function(a){H2.call(this,a,"videowall-endscreen");
this.F=a;this.A=0;this.l=[];this.C=this.o=this.u=null;this.D=this.R=!1;this.O=null;this.aa=new g.vs(this);g.G(this,this.aa);this.H=new g.L(g.Va(g.J,this.element,"ytp-show-tiles"),0);g.G(this,this.H);var b=new g.T({B:"button",V:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Anterior"},I:[g.WO()]});g.G(this,b);b.X(this.element);b.ca("click",this.xE,this);this.K=new g.kC({B:"div",G:"ytp-endscreen-content"});g.G(this,this.K);this.K.X(this.element);b=new g.T({B:"button",V:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Pr\u00f3ximo"},I:[g.XO()]});g.G(this,b);b.X(this.element);b.ca("click",this.wE,this);this.i=new I2(a);g.G(this,this.i);g.gK(this.player,this.i.element,4);this.hide()},R2=function(a){return g.hK(a.player)&&a.Qt()&&!a.C},S2=function(a,b){return(0,g.D)(b.suggestions,function(b){b=g.xR(g.V(a.F),b);
g.G(a,b);return b})},T2=function(a){var b=a.Ce();
b!=a.R&&(a.R=b,a.player.M("autonavvisibility"))},V2=function(a){g.sK.call(this,a);
this.g=null;this.i=new g.vs(this);g.G(this,this.i);this.l=g.V(a);U2(a)?this.g=new Q2(this.player):this.l.Ra?this.g=new N2(this.player):this.g=new H2(this.player);g.G(this,this.g);g.gK(this.player,this.g.element,4);this.dz();this.i.J(a,"videodatachange",this.dz,this);this.i.J(a,g.WD("endscreen"),this.ND,this);this.i.J(a,"crx_endscreen",this.OD,this)},U2=function(a){a=g.V(a);
return a.Ha&&!a.Ra};
g.r(H2,g.pC);H2.prototype.create=function(){this.created=!0};
H2.prototype.destroy=function(){this.created=!1};
H2.prototype.Qt=function(){return!1};
H2.prototype.Ce=function(){return!1};g.r(I2,g.T);g.h=I2.prototype;g.h.Xk=function(){this.A&&(this.D.stop(),this.Ma(this.C),this.C=null,this.A.close(),this.A=null)};
g.h.Lx=function(){g.oC(this,this.i.Ce())};
g.h.II=function(){window.focus();this.Xk()};
g.h.hide=function(){g.T.prototype.hide.call(this)};
g.h.po=function(a){a=a||g.Q(g.V(this.i).experiments,"autoplay_time")||1E4;var b=Math.min(g.O()-this.F,a);a=Math.min(b/a,1);this.H.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.i.getPresentingPlayerType()?M2(this,!0):this.l&&this.l.start()};
g.h.RI=function(a){!g.Ke(this.u.element,g.is(a))&&g.AR(a,this.i)&&M2(this)};
g.h.YG=function(){g.OJ(this.i,!0)};
g.h.eI=function(a){this.i.getPresentingPlayerType();this.show();J2(this,a)};
g.h.gA=function(a){this.i.getPresentingPlayerType();this.o&&this.o.ua().videoId==a.ua().videoId||(this.o=a,G2(this,a,"hqdefault.jpg"))};
g.h.fI=function(){this.i.getPresentingPlayerType();K2(this);this.hide()};
g.h.T=function(){K2(this);this.Xk();g.T.prototype.T.call(this)};g.r(N2,H2);g.r(O2,g.T);O2.prototype.C=function(a){g.AR(a,this.i,this.u,this.l.Sc||void 0)&&P2(this)};
O2.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.os(a)||(P2(this),g.ns(a))}};
O2.prototype.A=function(){var a=this.i.getVideoData(),b=g.V(this.i);this.u=a.Yb?!1:b.i};g.r(Q2,H2);g.h=Q2.prototype;g.h.create=function(){H2.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.u=S2(this,a),this.o=a);this.wf();this.aa.J(this.player,"appresize",this.wf);this.aa.J(this.player,"onVideoAreaChange",this.wf);this.aa.J(this.player,"videodatachange",this.yE);this.aa.J(this.player,"autonavchange",this.Eq);this.aa.J(this.player,"autonavcancel",this.vE);a=this.o.autonavState;a!=this.O&&this.Eq(a);this.aa.J(this.element,"transitionend",this.fK)};
g.h.destroy=function(){g.xs(this.aa);g.Yf(this.l);this.l=[];this.u=null;H2.prototype.destroy.call(this);g.Jo(this.element,"ytp-show-tiles");this.H.stop();this.O=this.o.autonavState};
g.h.Qt=function(){return 1!=this.o.autonavState};
g.h.show=function(){H2.prototype.show.call(this);g.Jo(this.element,"ytp-show-tiles");g.V(this.player).g?g.To(this.H):this.H.start();(this.D||this.C&&this.C!=this.o.clientPlaybackNonce)&&g.OJ(this.player,!1);R2(this)?(T2(this),2==this.o.autonavState?g.P(g.V(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?M2(this.i,!0):J2(this.i):3==this.o.autonavState&&L2(this.i)):(g.OJ(this.player,!0),T2(this))};
g.h.hide=function(){H2.prototype.hide.call(this);L2(this.i);T2(this)};
g.h.fK=function(a){g.is(a)==this.element&&this.wf()};
g.h.wf=function(){if(this.u&&this.u.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.YJ(this.F,!0),b=g.EC(this.F);b&&(b=b.uc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.u.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,u=e/2,x=b<=f-2&&n>=u*m,C=e<=k-2&&n>=p*m;if((p+1)/u*d/c>c/(p/(u+1)*d)&&C)n-=p*m,e+=2;else if(x)n-=u*m,b+=2;else if(C)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Ud(a.width/m||1,1,1.21);n*=g.Ud(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.K.element;g.wi(a,m,n);g.ei(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.i;f=this.u[0];c.o=f;G2(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",R2(this));T2(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,u=0,d&&f>=b-2&&k>=e-
2?u=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(u=2):u=2),p=g.Vd(p+this.A,l),0!=u){x=this.l[c];x||(x=new O2(this.player),this.l[c]=x,a.appendChild(x.element));C=Math.floor(n*k/e);var E=Math.floor(m*f/b),H=Math.floor(n*(k+u)/e)-C-4,R=Math.floor(m*(f+u)/b)-E-4;g.mi(x.element,E,C);g.wi(x.element,R,H);g.ei(x.element,"transitionDelay",(k+f)/20+"s");g.K(x.element,"ytp-videowall-still-mini",1==u);g.K(x.element,"ytp-videowall-still-large",2<u);u=x;p=this.u[p];u.l!=p&&(u.l=p,G2(u,p,g.Ho(u.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Sc)&&p.itct)&&(x=u.i,g.V(x).F&&g.bL(x.app.R,u.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.l.length-1;b>=c;b--)e=this.l[b],g.De(e.element),g.Xf(e);this.l.length=c}};
g.h.yE=function(){var a=this.player.getVideoData();this.o!=a&&(this.A=0,this.u=S2(this,a),this.o=a,this.wf())};
g.h.wE=function(){this.A+=this.l.length;this.wf()};
g.h.xE=function(){this.A-=this.l.length;this.wf()};
g.h.XC=function(){return!!this.i.l};
g.h.Eq=function(a){1==a?(this.D=!1,this.C=this.o.clientPlaybackNonce,K2(this.i),this.Fa()&&this.wf()):(this.D=!0,this.Fa()&&R2(this)&&(2==a?J2(this.i):3==a&&L2(this.i)))};
g.h.vE=function(a){if(a){for(a=0;a<this.l.length;a++)g.kK(this.F,this.l[a].element,!0);this.Eq(1)}else this.C=null,this.D=!1;this.wf()};
g.h.Ce=function(){return this.Fa()&&R2(this)};g.r(V2,g.sK);g.h=V2.prototype;g.h.jk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!U2(this.player)||b;a=a.Wc;var c=g.XW(this.player.app);return b&&!a&&!c};
g.h.Ce=function(){return this.g.Ce()};
g.h.TC=function(){return this.Ce()?this.g.XC():!1};
g.h.T=function(){g.cK(this.player,"endscreen");g.sK.prototype.T.call(this)};
g.h.load=function(){g.sK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.sK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.ND=function(a){this.jk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.OD=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.dz=function(){g.cK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.TD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.G(this,a);var b=new g.TD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.G(this,b);g.$J(this.player,[a,b])};g.xU.endscreen=V2;})(_yt_player);
