(function(g){var window=this;var poa=function(a,b){return g.ic(a,b)},a4=function(){},qoa=function(a){if(a.tc&&"function"==typeof a.tc)return a.tc();
if(g.t(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.ec(a)},roa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.t(a))(0,g.A)(a,b,void 0);else{if(a.yd&&"function"==typeof a.yd)var c=a.yd();else if(a.tc&&"function"==typeof a.tc)c=void 0;else if(g.Na(a)||g.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.fc(a);d=qoa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},b4=function(a){g.Kn(a,"zx",g.Gc());
return a},c4=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.Pn(a.l,b,c)},d4=function(a){return(a=g.fp(a))?new ActiveXObject(a):new XMLHttpRequest},e4=function(a,b){return b+" ["+a.Y+" "+a.F+" "+a.getStatus()+"]"},soa=function(a){return"content-type"==a.toLowerCase()},f4=function(a){a.g&&a.N&&(a.g.ontimeout=null);
a.C&&(g.v.clearTimeout(a.C),a.C=null)},toa=function(a){return g.qe&&g.Vc(9)&&g.Ha(a.timeout)&&g.Fa(a.ontimeout)},g4=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},h4=function(a,b){if(a.g){f4(a);
var c=a.g,d=a.K[0]?g.Ja:null;a.g=null;a.K=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},i4=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;g4(a);h4(a)},j4=function(a){return a.g?a.g.readyState:0},k4=function(a){if(a.i&&"undefined"!=typeof g.MX)if(a.K[1]&&4==j4(a)&&2==a.getStatus())e4(a,"Local request error detected and ignored");
else if(a.D&&4==j4(a))g.kh(a.yv,0,a);else if(a.dispatchEvent("readystatechange"),4==j4(a)){e4(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vh(String(a.F))[1]||null;if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!uoa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<j4(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";g4(a)}}finally{h4(a)}}},l4=function(a){g.xg.call(this);
this.headers=new g.zn;this.O=a||null;this.i=!1;this.K=this.g=null;this.Y=this.F="";this.u=0;this.l="";this.o=this.Z=this.D=this.R=!1;this.A=0;this.C=null;this.W="";this.N=this.P=!1},m4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},voa=function(a,b){var c=[];
g.xl(b,function(a){try{var b=g.up.prototype.i.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Fa(b)?g.tp(b)&&c.push(a):c.push(a)},a);
return c},woa=function(a,b){var c=voa(a,b);
(0,g.A)(c,function(a){g.up.prototype.remove.call(this,a)},a)},n4=function(a){if(a.Tc){if(a.Tc.locationOverrideToken)return{locationOverrideToken:a.Tc.locationOverrideToken};
if(null!=a.Tc.latitudeE7&&null!=a.Tc.longitudeE7)return{latitudeE7:a.Tc.latitudeE7,longitudeE7:a.Tc.longitudeE7}}return null},xoa=function(a,b){g.gb(a,b)||a.push(b)},o4=function(a){var b=0,c;
for(c in a)b++;return b},yoa=function(a,b,c,d){var e=new g.Cn(null,void 0);
a&&g.Dn(e,a);b&&g.En(e,b);c&&g.Fn(e,c);d&&(e.i=d);return e},p4=function(){this.g=[];
this.i=[]},q4=function(a,b){g.yq[a]=!0;
var c=g.wq();c&&c.publish.apply(c,arguments);g.yq[a]=!1},r4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.zn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",zoa(this,a.capabilities||""),Aoa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},zoa=function(a,b){a.capabilities.clear();
(0,g.Fe)(b.split(","),g.Va(poa,Boa)).forEach(function(b){a.capabilities.add(b)})},Aoa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},s4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},t4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},u4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Coa=function(a){return new s4(a)},v4=function(a){return g.Ma(a)?(0,g.D)(a,Coa):[]},w4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},x4=function(a){return g.Ma(a)?"["+(0,g.D)(a,w4).join(",")+"]":"null"},y4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Doa=function(a){return(0,g.D)(a,function(a){return{key:a.id,
name:a.name}})},z4=function(a,b){return g.cb(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},A4=function(a,b){return g.cb(a,function(a){return t4(a,b)})},Eoa=function(){var a=(0,g.Jt)();
a&&woa(a,a.g.Ye(!0))},B4=function(){var a=g.Mt("yt-remote-connected-devices")||[];
g.zb(a);return a},Foa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.D)(a,function(a,b){return 0==b?a:a.substring(c.length)})},C4=function(a){g.Lt("yt-remote-connected-devices",a,86400)},E4=function(){if(D4)return D4;
var a=g.Mt("yt-remote-device-id");a||(a=y4(),g.Lt("yt-remote-device-id",a,31536E3));for(var b=B4(),c=1,d=a;g.gb(b,d);)c++,d=a+"#"+c;return D4=d},F4=function(){var a=B4(),b=E4();
g.gb(a,b);g.Ot()&&g.Db(a,b);a=Foa(a);if(0==a.length)try{g.gt("remote_sid")}catch(c){}else try{g.ft("remote_sid",a.join(","),-1)}catch(c){}},G4=function(){return g.Mt("yt-remote-session-browser-channel")},H4=function(){return g.Mt("yt-remote-local-screens")||[]},I4=function(){g.Lt("yt-remote-lounge-token-expiration",!0,86400)},Goa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.D)(H4(),function(a){return a.loungeToken}),c=(0,g.D)(a,function(a){return a.loungeToken});
(0,g.ln)(c,function(a){return!g.gb(b,a)})&&I4();
g.Lt("yt-remote-local-screens",a,31536E3)},Hoa=function(a,b){g.Lt("yt-remote-session-browser-channel",a);
g.Lt("yt-remote-session-screen-id",b);var c=B4(),d=E4();g.gb(c,d)||c.push(d);C4(c);F4()},J4=function(a){a||(g.Nt("yt-remote-session-screen-id"),g.Nt("yt-remote-session-video-id"));
F4();a=B4();g.kb(a,E4());C4(a)},L4=function(){if(!K4){var a=g.Ep();
a&&(K4=new g.op(a))}return K4?!!K4.get("yt-remote-use-staging-server"):!1},M4=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},N4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},P4=function(a){a.length?O4(a.shift(),function(){P4(a)}):Q4()},Ioa=function(a){return"chrome-extension://"+a+R4},O4=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Q4=function(){var a=N4();
a&&a(!1,"No cast extension found")},S4=function(){if(Joa){var a=2,b=N4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;O4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Q4,c)}},Koa=function(){S4();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);P4(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+R4,"//www.gstatic.com/eureka/clank"+R4])},T4=function(a,b,c){g.F.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Nc=b;this.u=(0,g.y)(this.cC,this);this.g=!1;this.i=0;this.l=this.Ba=null;this.o=[]},U4=function(){},V4=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.Qn(this);this.i=new g.jh;this.i.setInterval(250)},X4=function(a,b,c){a.zh=1;
a.Uf=b4(b.clone());a.Ug=c;a.u=!0;W4(a,null)},Y4=function(a,b,c,d,e){a.zh=1;
a.Uf=b4(b.clone());a.Ug=null;a.u=c;e&&(a.jz=!1);W4(a,d)},W4=function(a,b){a.di=(0,g.B)();
Z4(a);a.jg=a.Uf.clone();c4(a.jg,"t",a.A);a.vk=0;a.hc=a.g.Oo(a.g.lk()?b:null);0<a.vp&&(a.Pm=new g.fm((0,g.y)(a.rA,a,a.hc),a.vp));a.aa.ca(a.hc,"readystatechange",a.RK);var c=a.Bg?g.qc(a.Bg):{};a.Ug?(a.Dn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.hc.send(a.jg,a.Dn,a.Ug,c)):(a.Dn="GET",a.jz&&!g.se&&(c.Connection="close"),a.hc.send(a.jg,a.Dn,null,c));a.g.ie(1)},f5=function(a,b,c){for(var d=!0;!a.tg&&a.vk<c.length;){var e=Loa(a,c);
if(e==$4){4==b&&(a.Vf=4,a5(15),d=!1);break}else if(e==b5){a.Vf=4;a5(16);d=!1;break}else c5(a,e)}4==b&&0==c.length&&(a.Vf=1,a5(17),d=!1);a.ne=a.ne&&d;d||(d5(a),e5(a))},Loa=function(a,b){var c=a.vk,d=b.indexOf("\n",c);
if(-1==d)return $4;c=Number(b.substring(c,d));if(isNaN(c))return b5;d+=1;if(d+c>b.length)return $4;var e=b.substr(d,c);a.vk=d+c;return e},i5=function(a,b){a.di=(0,g.B)();
Z4(a);var c=b?window.location.hostname:"";a.jg=a.Uf.clone();g.Kn(a.jg,"DOMAIN",c);g.Kn(a.jg,"t",a.A);try{a.pe=new ActiveXObject("htmlfile")}catch(n){d5(a);a.Vf=7;a5(22);e5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in g5)k=g5[l];else if(l in h5)k=g5[l]=h5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
g5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Td(g.gd("b/12014412"),d+"</body></html>");a.pe.open();a.pe.write(g.Jd(c));a.pe.close();a.pe.parentWindow.m=(0,g.y)(a.iK,a);a.pe.parentWindow.d=(0,g.y)(a.uy,a,!0);a.pe.parentWindow.rpcClose=(0,g.y)(a.uy,a,!1);c=a.pe.createElement("DIV");a.pe.parentWindow.document.body.appendChild(c);d=g.ud(a.jg.toString());d=g.Ac(g.rd(d));d=g.Td(g.gd("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Od(c,g.Jd(d));a.g.ie(1)},Z4=function(a){a.Es=(0,g.B)()+
a.o;
j5(a,a.o)},j5=function(a,b){if(null!=a.wi)throw Error("WatchDog timer not null");
a.wi=k5((0,g.y)(a.sK,a),b)},l5=function(a){a.wi&&(g.v.clearTimeout(a.wi),a.wi=null)},e5=function(a){a.g.wv()||a.tg||a.g.Bm(a)},d5=function(a){l5(a);
g.Xf(a.Pm);a.Pm=null;a.i.stop();g.Sn(a.aa);if(a.hc){var b=a.hc;a.hc=null;b.abort();b.dispose()}a.pe&&(a.pe=null)},c5=function(a,b){try{a.g.my(a,b),a.g.ie(4)}catch(c){}},n5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;m5(a,b,function(e){e?c(!0):g.v.setTimeout(function(){n5(a,b,c,d,f)},f)})}},m5=function(a,b,c){var d=new Image;
d.onload=function(){try{o5(d),c(!0)}catch(e){}};
d.onerror=function(){try{o5(d),c(!1)}catch(e){}};
d.onabort=function(){try{o5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{o5(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},o5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},p5=function(a){this.g=a;
this.i=new U4},r5=function(a){var b=q5(a.g,a.Ni,"/mail/images/cleardot.gif");
b4(b);n5(b.toString(),5E3,(0,g.y)(a.uB,a),3,2E3);a.ie(1)},t5=function(a){var b=a.g.F;
if(null!=b)a5(5),b?(a5(11),s5(a.g,a,!1)):(a5(12),s5(a.g,a,!0));else if(a.Ed=new V4(a,void 0,void 0,void 0),a.Ed.Bg=a.rp,b=a.g,b=q5(b,b.lk()?a.sj:null,a.tp),a5(5),!g.qe||g.Xc(10))c4(b,"TYPE","xmlhttp"),Y4(a.Ed,b,!1,a.sj,!1);else{c4(b,"TYPE","html");var c=a.Ed;a=!!a.sj;c.zh=3;c.Uf=b4(b.clone());i5(c,a)}},u5=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new U4;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Moa=function(a,b){this.g=a;
this.map=b;this.context=null},v5=function(a){g.Zf.call(this,"statevent",a)},w5=function(a,b){g.Zf.call(this,"timingevent",a);
this.size=b},x5=function(a){g.Zf.call(this,"serverreachability",a)},B5=function(a){y5(a);
if(3==a.g){var b=a.Yj++,c=a.nl.clone();g.Kn(c,"SID",a.l);g.Kn(c,"RID",b);g.Kn(c,"TYPE","terminate");z5(a,c);b=new V4(a,a.l,b,void 0);b.zh=2;b.Uf=b4(c.clone());(new Image).src=b.Uf;b.di=(0,g.B)();Z4(b)}A5(a)},D5=function(a){a.IB(1,0);
a.nl=q5(a,null,a.qp);C5(a)},y5=function(a){a.Kf&&(a.Kf.abort(),a.Kf=null);
a.Ob&&(a.Ob.cancel(),a.Ob=null);a.bf&&(g.v.clearTimeout(a.bf),a.bf=null);E5(a);a.qd&&(a.qd.cancel(),a.qd=null);a.Rf&&(g.v.clearTimeout(a.Rf),a.Rf=null)},F5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Moa(a.qG++,b));2!=a.g&&3!=a.g||C5(a)},C5=function(a){a.qd||a.Rf||(a.Rf=k5((0,g.y)(a.ty,a),0),a.uh=0)},I5=function(a,b){if(1==a.g){if(!b){a.Yj=Math.floor(1E5*Math.random());
var c=a.Yj++,d=new V4(a,"",c,void 0);d.Bg=null;var e=G5(a),f=a.nl.clone();g.Kn(f,"RID",c);g.Kn(f,"CVER","1");z5(a,f);X4(d,f,e);a.qd=d;a.g=2}}else 3==a.g&&(b?H5(a,b):0==a.i.length||a.qd||H5(a))},H5=function(a,b){if(b)if(6<a.ug){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Yj-1;var d=G5(a)}else c=b.C,d=b.Ug;else c=a.Yj++,d=G5(a);var e=a.nl.clone();g.Kn(e,"SID",a.l);g.Kn(e,"RID",c);g.Kn(e,"AID",a.Lh);z5(a,e);c=new V4(a,a.l,c,a.uh+1);c.Bg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.qd=c;X4(c,e,d)},z5=function(a,b){if(a.Lc){var c=a.Lc.Xu();
c&&g.Zb(c,function(a,c){g.Kn(b,c,a)})}},G5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.ug&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.ug?e:f-d;try{g.Zb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},J5=function(a){a.Ob||a.bf||(a.C=1,a.bf=k5((0,g.y)(a.ry,a),0),a.qh=0)},L5=function(a){if(a.Ob||a.bf||3<=a.qh)return!1;
a.C++;a.bf=k5((0,g.y)(a.ry,a),K5(a,a.qh));a.qh++;return!0},s5=function(a,b,c){a.An=c;
a.ye=b.nf;a.A||D5(a)},E5=function(a){null!=a.xg&&(g.v.clearTimeout(a.xg),a.xg=null)},K5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},N5=function(a,b){if(2==b||9==b){var c=null;
a.Lc&&(c=null);var d=(0,g.y)(a.tL,a);c||(c=new g.Cn("//www.google.com/images/cleardot.gif"),b4(c));m5(c.toString(),1E4,d)}else a5(2);M5(a,b)},M5=function(a,b){a.g=0;
a.Lc&&a.Lc.Zt(b);A5(a);y5(a)},A5=function(a){a.g=0;
a.ye=-1;if(a.Lc)if(0==a.o.length&&0==a.i.length)a.Lc.Eo();else{g.pb(a.o);var b=g.pb(a.i);a.o.length=0;a.i.length=0;a.Lc.Eo(b)}},q5=function(a,b,c){var d=g.Ln(c);
if(""!=d.g)b&&g.En(d,b+"."+d.g),g.Fn(d,d.u);else{var e=window.location;d=yoa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Zi&&g.Zb(a.Zi,function(a,b){g.Kn(d,b,a)});
g.Kn(d,"VER",a.ug);z5(a,d);return d},k5=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},a5=function(a){O5.dispatchEvent(new v5(O5,a))},P5=function(){},Noa=function(a,b){this.action=a;
this.params=b||{}},Q5=function(a,b){g.F.call(this);
this.g=new g.L(this.aK,0,this);g.G(this,this.g);this.Nc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},R5=function(a,b,c){this.H=a;
this.A=b;this.l=new g.np;this.i=new Q5(this.OL,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.N=c||!1},Ooa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.An,sessionId:a.g.l,arrayId:a.g.Lh}},S5=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&I5(a.g),B5(a.g));a.D=0},T5=function(a){return!!a.g&&3==a.g.g},Poa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},U5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.yh(a)||"";b&&(this.port=":"+b);this.domain=g.xh(a)||"";a=g.Xb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Wb(a,"10.0")&&(this.i=!1))},V5=function(a,b){var c=a.g;
if(g.Fa(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.Ih(c+b,{})},W5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Va(a.o,d,!0),onError:g.Va(a.l,e),fd:g.Va(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.hr(b,a)},Qoa=function(){var a=X5;
Y5();Z5.push(a);$5(Z5)},a6=function(a,b){Y5();
var c=Z5,d=Roa(a,String(b));0==c.length?Soa(d):($5(c),(0,g.A)(c,function(a){a(d)}))},Y5=function(){Z5||(Z5=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",Z5,void 0))},Soa=function(a){var b=(b6+1)%50;
b6=b;c6[b]=a;d6||(d6=49==b)},$5=function(a){var b=c6;
if(b[0]){var c=b6,d=d6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.A)(a,function(a){a(e)})}while(d!=c);
c6=Array(50);b6=-1;d6=!1}},Roa=function(a,b){var c=((0,g.B)()-Toa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},e6=function(a){g.N.call(this);
this.C=a;this.g=[]},f6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Uoa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Fe)(a.g,function(a){return!!z4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=f6(a,b[d])||c;return c},Voa=function(a,b){var c=a.g.length;
a.g=(0,g.Fe)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},g6=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Ba=NaN},i6=function(a){e6.call(this,"LocalScreenService");
this.l=a;this.i=NaN;h6(this);this.info("Initializing with "+x4(this.g))},j6=function(a){if(a.g.length){var b=(0,g.D)(a.g,function(a){return a.id}),c=V5(a.l,"/pairing/get_lounge_token_batch");
W5(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.lC,a),(0,g.y)(a.kC,a))}},h6=function(a){var b=v4(H4());
b=(0,g.Fe)(b,function(a){return!a.uuid});
return Uoa(a,b)},k6=function(a,b){Goa((0,g.D)(a.g,u4));
b&&I4()},m6=function(a,b){g.N.call(this);
this.A=b;var c=g.Mt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.gb(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;l6("Initialized with "+g.ph(this.g))},n6=function(a,b,c){var d=V5(a.u,"/pairing/get_screen_availability");
W5(a.u,d,{lounge_token:b.token},(0,g.y)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},o6=function(a,b){a:if(o4(b)!=o4(a.g))var c=!1;
else{c=g.fc(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(l6("Updated online screens: "+g.ph(a.g)),a.g=b,a.M("screenChange"));Woa(a)},p6=function(a){isNaN(a.l)||g.vq(a.l);
a.l=g.tq((0,g.y)(a.Gr,a),0<a.o&&a.o<(0,g.B)()?2E4:1E4)},l6=function(a){a6("OnlineScreenService",a)},q6=function(a){var b={};
(0,g.A)(a.A(),function(a){a.token?b[a.token]=a.id:this.Gb("Requesting availability of screen w/o lounge token.")});
return b},Woa=function(a){a=g.fc(g.$b(a.g,function(a){return a}));
g.zb(a);a.length?g.Lt("yt-remote-online-screen-ids",a.join(","),60):g.Nt("yt-remote-online-screen-ids")},r6=function(a){e6.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Xoa(this)},t6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.zd();if(k=(c?A4(k,c):null)||A4(k,b)){k.uuid=b;var l=s6(a,k);n6(a.i,l,function(a){e(a?l:null)})}else c?Yoa(a,c,(0,g.y)(function(a){var f=s6(this,new s4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));n6(this.i,f,function(a){e(a?f:null)})},a),f):e(null)},u6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Yoa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.hr(V5(a.A,"/pairing/get_lounge_token_batch"),e)},v6=function(a){a.g=a.l.zd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+x4(a.g))},Xoa=function(a){w6(a);
a.l=new i6(a.A);a.l.subscribe("screenChange",(0,g.y)(a.uC,a));v6(a);a.o=v4(g.Mt("yt-remote-automatic-screen-cache")||[]);w6(a);a.info("Initializing automatic screens: "+x4(a.o));a.i=new m6(a.A,(0,g.y)(a.zd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.M("onlineScreenChange")},a))},s6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=A4(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Lt("yt-remote-automatic-screen-cache",(0,g.D)(a.o,u4)));w6(a);a.u[b.uuid]=b.id;g.Lt("yt-remote-device-id-map",a.u,31536E3);return b},w6=function(a){a.u=g.Mt("yt-remote-device-id-map")||{}},x6=function(a,b,c){g.N.call(this);
this.K=c;this.F=a;this.i=b;this.l=null},y6=function(a,b){a6(a.K,b)},A6=function(a,b){x6.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.UL,this);this.u=(0,g.y)(this.DK,this);this.o=g.tq((0,g.y)(function(){z6(this,null)},this),12E4)},Zoa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.ph(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.y)(function(){y6(this,"Failed to send message: getMdxSessionStatus.")},a)):y6(a,"Sending yt message without session: "+g.ph(b))},z6=function(a,b){g.vq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Cm,a),d=(0,g.y)(a.Cd,a);a.kv(b,c,d,5)}}else a.Cd(Error("Waiting for session status timed out."))},B6=function(a,b,c){x6.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.O=c;this.u=null;this.C=g.Ja;this.A=NaN;this.N=(0,g.y)(this.XL,this);this.g=g.Ja},C6=function(a){a.g=a.F.wA(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(a){this.g=g.Ja;
this.Cm(a)},a),(0,g.y)(function(a){this.g=g.Ja;
this.Cd(a)},a))},D6=function(a){var b={};
b.pairingCode=a.H;b.theme=a.O;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}L4()&&(b.env_useStageMdx=1);return g.Gh(b)},E6=function(a,b){x6.call(this,a,b,"ManualSession");
this.g=g.tq((0,g.y)(this.Nh,this,null),150)},F6=function(a,b,c,d){g.N.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.mJ,this)},G6=function(a,b){return b?g.cb(a.l,function(a){return t4(b,a.label)},a):null},H6=function(a){a6("Controller",a)},X5=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},I6=function(a){return a.u||!!a.l.length||!!a.g},J6=function(a,b,c){b!=a.g&&(g.Xf(a.g),(a.g=b)?(c?a.M("yt-remote-cast2-receiver-resumed",b.i):a.M("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.qy,a,b)),b.l?a.M("yt-remote-cast2-session-change",b.l):c&&a.g.Nh(null)):a.M("yt-remote-cast2-session-change",null))},K6=function(a){var b=a.i.vA(),c=a.g&&a.g.i;
a=(0,g.D)(b,function(a){c&&t4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=G6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},cpa=function(a,b,c,d,e,f,k){$oa()?apa(b,e,f,k)&&(M6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?N6(a,c):(window.__onGCastApiAvailable=function(b,d){b?N6(a,c):(O6("Failed to load cast API: "+d),P6(!1),M6(!1),g.Nt("yt-remote-cast-available"),g.Nt("yt-remote-cast-receiver"),Q6(),c(!1))},d?g.Gq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Koa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Q4():(S4(),P4(bpa.map(Ioa))))):L6("Cannot initialize because not running Chrome")},Q6=function(){L6("dispose");
var a=R6();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);S6(!1);g.Bq(T6);T6.length=0},U6=function(){return!!g.Mt("yt-remote-cast-installed")},V6=function(){var a=g.Mt("yt-remote-cast-receiver");
return a?a.friendlyName:null},W6=function(){L6("clearCurrentReceiver");
g.Nt("yt-remote-cast-receiver")},X6=function(){return U6()?R6()?R6().getCastSession():(O6("getCastSelector: Cast is not initialized."),null):(O6("getCastSelector: Cast API is not installed!"),null)},Z6=function(){U6()?R6()?Y6()?(L6("Requesting cast selector."),R6().requestSession()):(L6("Wait for cast API to be ready to request the session."),T6.push(g.Aq("yt-remote-cast2-api-ready",Z6))):O6("requestCastSelector: Cast is not initialized."):O6("requestCastSelector: Cast API is not installed!")},$6=
function(a,b){Y6()?R6().setConnectedScreenStatus(a,b):O6("setConnectedScreenStatus called before ready.")},$oa=function(){var a=0<=g.Xb.search(/ (CrMo|Chrome|CriOS)\//);
return g.nx||a},dpa=function(a,b){R6().init(a,b)},apa=function(a,b,c,d){var e=!1;
R6()||(a=new F6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Lt("yt-remote-cast-available",a);q4("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){L6("onReceiverSelected: "+a.friendlyName);
g.Lt("yt-remote-cast-receiver",a);q4("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){L6("onReceiverResumed: "+a.friendlyName);
g.Lt("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){L6("onSessionChange: "+w4(a));
a||g.Nt("yt-remote-cast-receiver");q4("yt-remote-cast2-session-change",a)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
L6("cloudview.createSingleton_: "+e);return e},R6=function(){return g.w("yt.mdx.remote.cloudview.instance_")},N6=function(a,b){P6(!0);
M6(!1);dpa(a,function(a){a?(S6(!0),g.Dq("yt-remote-cast2-api-ready")):(O6("Failed to initialize cast API."),P6(!1),g.Nt("yt-remote-cast-available"),g.Nt("yt-remote-cast-receiver"),Q6());b(a)})},L6=function(a){a6("cloudview",a)},O6=function(a){a6("cloudview",a)},P6=function(a){L6("setCastInstalled_ "+a);
g.Lt("yt-remote-cast-installed",a)},Y6=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},S6=function(a){L6("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},M6=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},a7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Ae=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},b7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ae=!1;a.hasNext=!1;a.C=0;a.A=(0,g.B)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},c7=function(a){return 1==a.playerState?((0,g.B)()-a.A)/1E3:0},d7=function(a,b){a.C=b;
a.A=(0,g.B)()},e7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.B)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},f7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&b7(a)},g7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.rc(a.g);b.hasPrevious=a.Ae;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},j7=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new p4;this.l=this.i=null;this.F=(0,g.y)(this.bH,this);this.C=(0,g.y)(this.Zj,this);this.D=(0,g.y)(this.aH,this);this.H=(0,g.y)(this.nH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Hs,this),h7(this))):c=3;0!=c&&(b?this.Hs(c):g.tq((0,g.y)(function(){this.Hs(c)},this),0));
var d=X6();d&&i7(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},k7=function(a){return new a7(a.o.getPlayerContextData())},h7=function(a){(0,g.A)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.A.push(this.o.subscribe(a,g.Va(this.iJ,a),this))},a)},l7=function(a){(0,g.A)(a.A,function(a){this.o.unsubscribeByKey(a)},a);
a.A.length=0},m7=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},o7=function(a,b,c){var d=k7(a);
d7(d,c);-1E3!=d.playerState&&(d.playerState=b);n7(a,d)},p7=function(a,b,c){a.o.sendMessage(b,c)},n7=function(a,b){l7(a);
a.o.setPlayerContextData(g7(b));h7(a)},i7=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Zj(null));
a.l=b;a.l&&(a6("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Zj(a.l.media[0]))},q7=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=k7(a);b.contentId!=d.videoId&&a6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;d7(d,a.i.getEstimatedTime());n7(a,d)}else a6("CP","No cast media video. Ignoring state update.")},r7=function(a,b,c){return(0,g.y)(function(a){this.Gb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gb("Retrying "+b+" using MDx browser channel."),p7(this,b,c))},a)},s7=function(a,b,c){g.N.call(this);
this.u=NaN;this.O=!1;this.H=this.F=this.N=this.K=NaN;this.R=[];this.o=this.C=this.l=this.Pa=this.g=null;this.na=a;this.R.push(g.gs(window,"beforeunload",(0,g.y)(this.eC,this)));this.i=[];this.Pa=new a7;this.Z=b.id;this.g=epa(this,c);this.g.subscribe("handlerOpened",this.fH,this);this.g.subscribe("handlerClosed",this.cH,this);this.g.subscribe("handlerError",this.dH,this);this.g.subscribe("handlerMessage",this.eH,this);Poa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=this.Pa.videoId;
g.Ot()&&g.Lt("yt-remote-session-video-id",a)},this)},t7=function(a){a6("conn",a)},epa=function(a,b){return new R5(V5(a.na,"/bc"),b)},u7=function(a,b){a.M("proxyStateChange",b)},fpa=function(a){a.u=g.tq((0,g.y)(function(){t7("Connecting timeout");
this.A(1)},a),2E4)},v7=function(a){g.vq(a.u);
a.u=NaN},w7=function(a){g.vq(a.K);
a.K=NaN},gpa=function(a){x7(a);
a.N=g.tq((0,g.y)(function(){y7(this,"getNowPlaying")},a),2E4)},x7=function(a){g.vq(a.N);
a.N=NaN},A7=function(a,b){b&&(v7(a),w7(a));
b==(T5(a.g)&&isNaN(a.u))?b&&(u7(a,1),y7(a,"getSubtitlesTrack")):b?(a.P()&&a.Pa.reset(),u7(a,1),y7(a,"getNowPlaying"),z7(a)):a.A(1)},hpa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.lc(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.M("remotePlayerChange"))},B7=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;f7(a.Pa,c,d);a.M("remoteQueueChange")},ipa=function(a,b){b.params=b.params||{};
B7(a,b);C7(a,b);a.M("autoplayDismissed")},C7=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
d7(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?gpa(a):x7(a);a.M("remotePlayerChange")},jpa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);d7(a.Pa,isNaN(c)?0:c);a.M("remotePlayerChange")}},kpa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.M("remotePlayerChange")},lpa=function(a,b){a.C=b.params.videoId;
a.M("nowAutoplaying",parseInt(b.params.timeout,10))},mpa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Ae="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.M("previousNextChange")},z7=function(a){g.vq(a.H);
a.H=g.tq((0,g.y)(a.A,a,1),864E5)},y7=function(a,b,c){c?t7("Sending: action="+b+", params="+g.ph(c)):t7("Sending: action="+b);
a.g.sendMessage(b,c)},D7=function(a){e6.call(this,"ScreenServiceProxy");
this.Ac=a;this.i=[];this.i.push(this.Ac.$_s("screenChange",(0,g.y)(this.SL,this)));this.i.push(this.Ac.$_s("onlineScreenChange",(0,g.y)(this.LI,this)))},rpa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.mq("MDX_CONFIG")||b;Eoa();F4();E7||(E7=new U5(b?b.loungeApiHost:void 0),L4()&&(E7.g="/api/loungedev"));F7||(F7=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",F7,void 0));npa();var c=G7();if(!c){var d=new r6(E7);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=G7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);cpa(a,d,function(a){a?H7()&&$6(H7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){q4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),I7("Initializing: "+g.ph(b)),J7.push(g.Aq("yt-remote-cast2-availability-change",function(){q4("yt-remote-receiver-availability-change")})),J7.push(g.Aq("yt-remote-cast2-receiver-selected",function(){K7(null);
q4("yt-remote-auto-connect","cast-selector-receiver")})),J7.push(g.Aq("yt-remote-cast2-receiver-resumed",function(){q4("yt-remote-receiver-resumed","cast-selector-receiver")})),J7.push(g.Aq("yt-remote-cast2-session-change",opa)),J7.push(g.Aq("yt-remote-connection-change",function(a){a?$6(H7(),"YouTube TV"):L7()||($6(null,null),W6())})),a=M7(),b.isAuto&&(a.id+="#dial"),g.Oq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),I7(" -- with channel params: "+
g.ph(a)),ppa(a),c.start(),H7()||qpa())},spa=function(){var a=N7();
U6()&&g.Mt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},N7=function(){var a=G7().Ac.$_gos();
var b=O7();b&&P7()&&(z4(a,b)||a.push(b));return Doa(a)},Q7=function(){var a=tpa();
!a&&U6()&&V6()&&(a={key:"cast-selector-receiver",name:V6()});return a},tpa=function(){var a=N7(),b=O7();
b||(b=L7());return g.cb(a,function(a){return b&&t4(b,a.key)?!0:!1})},O7=function(){var a=H7();
if(!a)return null;var b=G7().zd();return A4(b,a)},opa=function(a){I7("remote.onCastSessionChange_: "+w4(a));
if(a){var b=O7();b&&b.id==a.id?$6(b.id,"YouTube TV"):(b&&R7(),S7(a,1))}else P7()&&R7()},R7=function(){Y6()?R6().stopSession():O6("stopSession called before API ready.");
var a=P7();a&&(a.disconnect(1),T7(null))},U7=function(){var a=P7();
return!!a&&3!=a.getProxyState()},I7=function(a){a6("remote",a)},G7=function(){if(!V7){var a=g.w("yt.mdx.remote.screenService_");
V7=a?new D7(a):null}return V7},H7=function(){return g.w("yt.mdx.remote.currentScreenId_")},W7=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},X7=function(){return g.w("yt.mdx.remote.connectData_")},K7=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},P7=function(){return g.w("yt.mdx.remote.connection_")},T7=function(a){var b=P7();
K7(null);a||W7("");g.Ia("yt.mdx.remote.connection_",a,void 0);F7&&((0,g.A)(F7,function(b){b(a)}),F7.length=0);
b&&!a?q4("yt-remote-connection-change",!1):!b&&a&&q4("yt-remote-connection-change",!0)},L7=function(){var a=g.Ot();
if(!a)return null;var b=G7().zd();return A4(b,a)},S7=function(a,b){O7()&&O7();
W7(a.id);var c=new s7(E7,a,M7());c.connect(b,X7());c.subscribe("beforeDisconnect",function(a){q4("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){P7()&&T7(null)});
T7(c)},qpa=function(){var a=L7();
a?(I7("Resume connection to: "+w4(a)),S7(a,0)):(J4(),W6(),I7("Skipping connecting because no session screen found."))},npa=function(){var a=M7();
if(g.lc(a)){a=E4();var b=g.Mt("yt-remote-session-name")||"",c=g.Mt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},M7=function(){return g.w("yt.mdx.remote.channelParams_")||{}},ppa=function(a){a?(g.Lt("yt-remote-session-app",a.app),g.Lt("yt-remote-session-name",a.name)):(g.Nt("yt-remote-session-app"),g.Nt("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},Y7=function(a,b,c){g.F.call(this);
this.u=a;this.i=b;this.l=new g.vs(this);g.G(this,this.l);this.l.J(b,"onCaptionsTrackListChanged",this.cI);this.l.J(b,"captionschanged",this.ZG);this.l.J(b,"captionssettingschanged",this.Jz);this.l.J(b,"videoplayerreset",this.Dm);this.l.J(b,"mdxautoplaycancel",this.tB);this.R=this.l.J(b,"onVolumeChange",this.Yx);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.ly,this);c.subscribe("remotePlayerChange",this.bk,this);c.subscribe("remoteQueueChange",this.Dm,this);c.subscribe("autoplayUpNext",this.Nx,
this);c.subscribe("previousNextChange",this.iy,this);c.subscribe("nowAutoplaying",this.ey,this);c.subscribe("autoplayDismissed",this.Mx,this);this.suggestion=null;this.F=new g.fD(64);this.o=new g.L(this.Hz,500,this);g.G(this,this.o);this.A=new g.L(this.Iz,1E3,this);g.G(this,this.A);this.N=new T4(this.BL,0,this);g.G(this,this.N);this.C={};this.K=new g.L(this.jA,1E3,this);g.G(this,this.K);this.H=new g.fm(this.EE,1E3,this);g.G(this,this.H);this.O=g.Ja;this.Jz();this.Dm();this.bk()},Z7=function(a,b){a.u.hd(b,
a.i.getVideoData().lengthSeconds)},a8=function(a){Z7(a,0);
a.o.stop();$7(a,new g.fD(64))},c8=function(a,b){if(b8(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.tc(c,b));a.g.wz(a.i.getVideoData(1).videoId,c);a.C=k7(a.g).g}},d8=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Eh,n4(c));$7(a,new g.fD(1))},e8=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{kP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},b8=function(a){return k7(a.g).videoId==a.i.getVideoData(1).videoId},$7=function(a,b){a.A.stop();
var c=a.F;if(!g.lD(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.UJ(a.i,d);a.F=b;f8(a.u,c,b)}},h8=function(a){g.T.call(this,{B:"div",
G:"ytp-remote",I:[{B:"div",G:"ytp-remote-display-status",I:[{B:"div",G:"ytp-remote-display-status-icon",I:[g.UO()]},{B:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.i=new g.EP(this,250);g.G(this,this.i);this.l=a;this.J(a,"presentingplayerstatechange",this.o);g8(this,g.QJ(a))},g8=function(a,b){if(3==a.l.getPresentingPlayerType()){var c={RECEIVER_NAME:a.l.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.MN("Erro em $RECEIVER_NAME",c):g.mD(b)||g.U(b,4)?g.MN("Reproduzindo em $RECEIVER_NAME",c):g.MN("Conectado a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.i.show()}else a.i.hide()},i8=function(a,b){g.kT.call(this,"Reproduzir em",0,a,b);
this.i=a;this.C={};this.J(a,"onMdxReceiversChange",this.H);this.J(a,"presentingplayerstatechange",this.H);this.H()},j8=function(a){g.sK.call(this,a);
this.i={key:y4(),name:"Este computador"};this.o=null;this.u=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.Nj=new g.fD(64);this.D=0;this.Pl=-1;if(!g.lz(g.V(this.player))){a=this.player;var b=g.EC(a);b&&(b=b.km())&&(b=new i8(a,b),g.G(this,b));b=new h8(a);g.G(this,b);g.gK(a,b.element,4)}},f8=function(a,b,c){a.Nj=c;
a.player.M("presentingplayerstatechange",new g.qD(c,b))},k8=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)R7();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Eh,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=n4(d))&&(c.locationInfo=d);d=c}else d=null;I7("Connecting to: "+g.ph(b));"cast-selector-receiver"==b.key?
(K7(d||null),Y6()?R6().setLaunchParams(d||null):O6("setLaunchParams called before ready.")):!d&&U7()&&H7()==b.key?q4("yt-remote-connection-change",!0):(R7(),K7(d||null),d=G7().zd(),(d=A4(d,b.key))&&S7(d,1))}},uoa=/^https?$/i,upa=["POST",
"PUT"];g.z(l4,g.xg);g.h=l4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.Y=b;this.R=!1;this.i=!0;this.g=this.O?d4(this.O):d4(g.gY);this.K=this.O?this.O.getOptions():g.gY.getOptions();this.g.onreadystatechange=(0,g.y)(this.yv,this);try{a4(e4(this,"Opening Xhr")),this.Z=!0,this.g.open(b,String(a),!0),this.Z=!1}catch(f){a4(e4(this,"Error opening Xhr: "+f.message));i4(this,f);return}a=c||
"";var e=this.headers.clone();d&&roa(d,function(a,b){e.set(b,a)});
d=g.cb(e.yd(),soa);c=g.v.FormData&&a instanceof g.v.FormData;!g.gb(upa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.W&&(this.g.responseType=this.W);"withCredentials"in this.g&&this.g.withCredentials!==this.P&&(this.g.withCredentials=this.P);try{f4(this),0<this.A&&(this.N=toa(this.g),a4(e4(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.N)),this.N?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.zv,this)):this.C=g.kh(this.zv,this.A,this)),a4(e4(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){a4(e4(this,"Send error: "+f.message)),i4(this,f)}};
g.h.zv=function(){"undefined"!=typeof g.MX&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,e4(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(e4(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),h4(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),h4(this,!0));l4.Ga.T.call(this)};
g.h.yv=function(){this.da()||(this.Z||this.D||this.o?k4(this):this.lJ())};
g.h.lJ=function(){k4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<j4(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.t(this.l)?this.l:String(this.l)};
var h5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},g5={"'":"\\'"},vpa={};g.h=p4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.gb(this.g,a)||g.gb(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.dla)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.i,a)};
g.h.tc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var Boa={qM:"atp",BO:"ska",rO:"que",SN:"mus",AO:"sus",jN:"dsp",xO:"seq"};r4.prototype.Lf=function(){var a=new r4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var K4,D4="",R4=M4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",Joa=M4("loadCastFramework")||M4("loadCastApplicationFramework"),bpa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.z(T4,g.F);g.h=T4.prototype;g.h.bC=function(a){this.o=arguments;this.g=!1;this.Ba?this.l=(0,g.B)()+this.Nc:this.Ba=g.kh(this.u,this.Nc)};
g.h.stop=function(){this.Ba&&(g.v.clearTimeout(this.Ba),this.Ba=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();T4.Ga.T.call(this)};
g.h.cC=function(){this.l?(this.Ba=g.kh(this.u,this.l-(0,g.B)()),this.l=null):(this.Ba=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};U4.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
U4.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=V4.prototype;g.h.Bg=null;g.h.ne=!1;g.h.wi=null;g.h.Es=null;g.h.di=null;g.h.zh=null;g.h.Uf=null;g.h.jg=null;g.h.Ug=null;g.h.hc=null;g.h.vk=0;g.h.pe=null;g.h.Dn=null;g.h.Vf=null;g.h.tj=-1;g.h.jz=!0;g.h.tg=!1;g.h.vp=0;g.h.Pm=null;var b5={},$4={};g.h=V4.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.RK=function(a){a=a.target;var b=this.Pm;b&&3==j4(a)?b.pj():this.rA(a)};
g.h.rA=function(a){try{if(a==this.hc)a:{var b=j4(this.hc),c=this.hc.u,d=this.hc.getStatus();if(g.qe&&!g.Xc(10)||g.se&&!g.Vc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.hi&&!m4(this.hc))break a;this.tg||4!=b||7==c||(8==c||0>=d?this.g.ie(3):this.g.ie(2));l5(this);var e=this.hc.getStatus();this.tj=e;var f=m4(this.hc);(this.ne=200==e)?(4==b&&d5(this),this.u?(f5(this,b,f),g.hi&&this.ne&&3==b&&(this.aa.ca(this.i,"tick",this.NK),this.i.start())):c5(this,f),this.ne&&!this.tg&&(4==b?this.g.Bm(this):(this.ne=
!1,Z4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Vf=3,a5(13)):(this.Vf=0,a5(14)),d5(this),e5(this))}}catch(k){this.hc&&m4(this.hc)}finally{}};
g.h.NK=function(){var a=j4(this.hc),b=m4(this.hc);this.vk<b.length&&(l5(this),f5(this,a,b),this.ne&&4!=a&&Z4(this))};
g.h.iK=function(a){k5((0,g.y)(this.hK,this,a),0)};
g.h.hK=function(a){this.tg||(l5(this),c5(this,a),Z4(this))};
g.h.uy=function(a){k5((0,g.y)(this.gK,this,a),0)};
g.h.gK=function(a){this.tg||(d5(this),this.ne=a,this.g.Bm(this),this.g.ie(4))};
g.h.cancel=function(){this.tg=!0;d5(this)};
g.h.sK=function(){this.wi=null;var a=(0,g.B)();0<=a-this.Es?(2!=this.zh&&this.g.ie(3),d5(this),this.Vf=2,a5(18),e5(this)):j5(this,this.Es-a)};
g.h.getLastError=function(){return this.Vf};g.h=p5.prototype;g.h.rp=null;g.h.Ed=null;g.h.Qm=!1;g.h.xv=null;g.h.kl=null;g.h.hq=null;g.h.tp=null;g.h.Rd=null;g.h.nf=-1;g.h.sj=null;g.h.Ni=null;g.h.connect=function(a){this.tp=a;a=q5(this.g,null,this.tp);a5(3);this.xv=(0,g.B)();var b=this.g.D;null!=b?(this.sj=b[0],(this.Ni=b[1])?(this.Rd=1,r5(this)):(this.Rd=2,t5(this))):(c4(a,"MODE","init"),this.Ed=new V4(this,void 0,void 0,void 0),this.Ed.Bg=this.rp,Y4(this.Ed,a,!1,null,!0),this.Rd=0)};
g.h.uB=function(a){if(a)this.Rd=2,t5(this);else{a5(4);var b=this.g;b.ye=b.Kf.nf;N5(b,9)}a&&this.ie(2)};
g.h.Oo=function(a){return this.g.Oo(a)};
g.h.abort=function(){this.Ed&&(this.Ed.cancel(),this.Ed=null);this.nf=-1};
g.h.wv=function(){return!1};
g.h.my=function(a,b){this.nf=a.tj;if(0==this.Rd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.ye=this.nf;N5(c,2);return}this.sj=c[0];this.Ni=c[1]}else c=this.g,c.ye=this.nf,N5(c,2);else if(2==this.Rd)if(this.Qm)a5(7),this.hq=(0,g.B)();else if("11111"==b){if(a5(6),this.Qm=!0,this.kl=(0,g.B)(),c=this.kl-this.xv,!g.qe||g.Xc(10)||500>c)this.nf=200,this.Ed.cancel(),a5(12),s5(this.g,this,!0)}else a5(8),this.kl=this.hq=(0,g.B)(),this.Qm=!1};
g.h.Bm=function(){this.nf=this.Ed.tj;if(this.Ed.ne)0==this.Rd?this.Ni?(this.Rd=1,r5(this)):(this.Rd=2,t5(this)):2==this.Rd&&((!g.qe||g.Xc(10)?!this.Qm:200>this.hq-this.kl)?(a5(11),s5(this.g,this,!1)):(a5(12),s5(this.g,this,!0)));else{0==this.Rd?a5(9):2==this.Rd&&a5(10);var a=this.g;a.ye=this.nf;N5(a,2)}};
g.h.lk=function(){return this.g.lk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ie=function(a){this.g.ie(a)};g.h=u5.prototype;g.h.Zi=null;g.h.qd=null;g.h.Ob=null;g.h.qp=null;g.h.nl=null;g.h.Rt=null;g.h.wl=null;g.h.Yj=0;g.h.qG=0;g.h.Lc=null;g.h.Rf=null;g.h.bf=null;g.h.xg=null;g.h.Kf=null;g.h.An=null;g.h.Lh=-1;g.h.Zv=-1;g.h.ye=-1;g.h.uh=0;g.h.qh=0;g.h.ug=8;var O5=new g.xg;g.z(v5,g.Zf);g.z(w5,g.Zf);g.z(x5,g.Zf);g.h=u5.prototype;g.h.connect=function(a,b,c,d,e){a5(0);this.qp=b;this.Zi=c||{};d&&g.Fa(e)&&(this.Zi.OSID=d,this.Zi.OAID=e);this.A?(k5((0,g.y)(this.ju,this,a),100),D5(this)):this.ju(a)};
g.h.ju=function(a){this.Kf=new p5(this);this.Kf.rp=null;this.Kf.i=this.u;this.Kf.connect(a)};
g.h.wv=function(){return 0==this.g};
g.h.ty=function(a){this.Rf=null;I5(this,a)};
g.h.ry=function(){this.bf=null;this.Ob=new V4(this,this.l,"rpc",this.C);this.Ob.Bg=null;this.Ob.vp=0;var a=this.Rt.clone();g.Kn(a,"RID","rpc");g.Kn(a,"SID",this.l);g.Kn(a,"CI",this.An?"0":"1");g.Kn(a,"AID",this.Lh);z5(this,a);if(!g.qe||g.Xc(10))g.Kn(a,"TYPE","xmlhttp"),Y4(this.Ob,a,!0,this.wl,!1);else{g.Kn(a,"TYPE","html");var b=this.Ob,c=!!this.wl;b.zh=3;b.Uf=b4(a.clone());i5(b,c)}};
g.h.my=function(a,b){if(0!=this.g&&(this.Ob==a||this.qd==a))if(this.ye=a.tj,this.qd==a&&3==this.g)if(7<this.ug){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.bf){if(this.Ob)if(this.Ob.di+3E3<this.qd.di)E5(this),this.Ob.cancel(),this.Ob=null;else break a;L5(this);a5(19)}}else this.Zv=c[1],0<this.Zv-this.Lh&&37500>c[2]&&this.An&&0==this.qh&&!this.xg&&(this.xg=k5((0,g.y)(this.VG,this),6E3));else N5(this,11)}else b!=vpa.PM.g&&N5(this,11);else if(this.Ob==a&&
E5(this),!g.Kb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.Lh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.wl=e[2],e=e[3],null!=e?this.ug=e:this.ug=6,this.g=3,this.Lc&&this.Lc.cu(),this.Rt=q5(this,this.lk()?this.wl:null,this.qp),J5(this)):"stop"==e[0]&&N5(this,7):3==this.g&&("stop"==e[0]?N5(this,7):"noop"!=e[0]&&this.Lc&&this.Lc.au(e),this.qh=0)}}};
g.h.VG=function(){null!=this.xg&&(this.xg=null,this.Ob.cancel(),this.Ob=null,L5(this),a5(20))};
g.h.Bm=function(a){if(this.Ob==a){E5(this);this.Ob=null;var b=2}else if(this.qd==a)this.qd=null,b=1;else return;this.ye=a.tj;if(0!=this.g)if(a.ne)1==b?(b=(0,g.B)()-a.di,O5.dispatchEvent(new w5(O5,a.Ug?a.Ug.length:0,b,this.uh)),C5(this),this.o.length=0):J5(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ye)){if(d=1==b)this.qd||this.Rf||1==this.g||2<=this.uh?d=!1:(this.Rf=k5((0,g.y)(this.ty,this,a),K5(this,this.uh)),this.uh++,d=!0);d=!(d||2==b&&L5(this))}if(d)switch(c){case 1:N5(this,
5);break;case 4:N5(this,10);break;case 3:N5(this,6);break;case 7:N5(this,12);break;default:N5(this,2)}}};
g.h.IB=function(a){if(!g.gb(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.tL=function(a){a?a5(2):(a5(1),M5(this,8))};
g.h.Oo=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new l4;a.P=!1;return a};
g.h.isActive=function(){return!!this.Lc&&this.Lc.isActive(this)};
g.h.ie=function(a){O5.dispatchEvent(new x5(O5,a))};
g.h.lk=function(){return!(!g.qe||g.Xc(10))};
g.h=P5.prototype;g.h.cu=function(){};
g.h.au=function(){};
g.h.Zt=function(){};
g.h.Eo=function(){};
g.h.Xu=function(){return{}};
g.h.isActive=function(){return!0};g.z(Q5,g.F);g.h=Q5.prototype;g.h.aK=function(){this.Nc=Math.min(3E5,2*this.Nc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Nc+15E3*Math.random();g.So(this.g,a);this.i=(0,g.B)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Nc=5E3};g.z(R5,P5);g.h=R5.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.vf=function(a){return this.l.Cg(a)};
g.h.M=function(a,b){return this.l.M.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.Xf(this.l),S5(this),g.Xf(this.i),this.i=null)};
g.h.da=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new u5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.g;e&&(e.Lc=null);d.Lc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Lh):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.tc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):T5(this)&&F5(this.g,c)};
g.h.cu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)F5(this.g,a[b])}this.M("handlerOpened")};
g.h.Zt=function(a){var b=2==a&&401==this.g.ye;4==a||b||this.i.start();this.M("handlerError",a)};
g.h.Eo=function(a){if(!this.i.isActive())this.M("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Xu=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.tc(a,this.u);return a};
g.h.au=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),B5(this.g)):this.M("handlerMessage",new Noa(a[0],a[1]))};
g.h.OL=function(){this.i.isActive();var a=this.g,b=0;a.Ob&&b++;a.qd&&b++;0!=b||this.connect(this.u,this.o)};U5.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
U5.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
U5.prototype.u=function(a){a(Error("request timed out"))};var Toa=(0,g.B)(),Z5=null,c6=Array(50),b6=-1,d6=!1;g.z(e6,g.N);e6.prototype.zd=function(){return this.g};
e6.prototype.contains=function(a){return!!z4(this.g,a)};
e6.prototype.get=function(a){return a?A4(this.g,a):null};
e6.prototype.info=function(a){a6(this.C,a)};g.z(g6,g.N);var l8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=g6.prototype;g.h.start=function(){!this.g&&isNaN(this.Ba)&&this.uA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ba)||(g.vq(this.Ba),this.Ba=NaN)};
g.h.T=function(){this.stop();g6.Ga.T.call(this)};
g.h.uA=function(){this.Ba=NaN;this.g=g.hr(V5(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.QL,this),onError:(0,g.y)(this.PL,this),fd:(0,g.y)(this.RL,this)})};
g.h.QL=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.M("pairingComplete",new s4(c))};
g.h.PL=function(a){this.g=null;a.status&&404==a.status?this.i>=l8.length?this.M("pairingFailed",Error("DIAL polling timed out")):(a=l8[this.i],this.Ba=g.tq((0,g.y)(this.uA,this),a),this.i++):this.M("pairingFailed",Error("Server error "+a.status))};
g.h.RL=function(){this.g=null;this.M("pairingFailed",Error("Server not responding"))};g.z(i6,e6);g.h=i6.prototype;g.h.start=function(){h6(this)&&this.M("screenChange");!g.Mt("yt-remote-lounge-token-expiration")&&j6(this);g.vq(this.i);this.i=g.tq((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){h6(this);f6(this,a);k6(this,!1);this.M("screenChange");b(a);a.token||j6(this)};
g.h.remove=function(a,b){var c=h6(this);Voa(this,a)&&(k6(this,!1),c=!0);b(a);c&&this.M("screenChange")};
g.h.wn=function(a,b,c,d){var e=h6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.M("screenChange")};
g.h.T=function(){g.vq(this.i);i6.Ga.T.call(this)};
g.h.lC=function(a){h6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k6(this,!b);b&&a6(this.C,"Missed "+b+" lounge tokens.")};
g.h.kC=function(a){a6(this.C,"Requesting lounge tokens failed: "+a)};g.z(m6,g.N);g.h=m6.prototype;g.h.start=function(){var a=parseInt(g.Mt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.B)()-144E5<a?0:a)?p6(this):(this.o=(0,g.B)()+3E5,g.Lt("yt-remote-fast-check-period",this.o),this.Gr())};
g.h.isEmpty=function(){return g.lc(this.g)};
g.h.update=function(){l6("Updating availability on schedule.");var a=this.A(),b=g.$b(this.g,function(b,d){return b&&!!A4(a,d)},this);
o6(this,b)};
g.h.T=function(){g.vq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);m6.Ga.T.call(this)};
g.h.Gr=function(){g.vq(this.l);this.l=NaN;this.i&&this.i.abort();var a=q6(this);if(o4(a)){var b=V5(this.u,"/pairing/get_screen_availability");this.i=W5(this.u,b,{lounge_token:g.fc(a).join(",")},(0,g.y)(this.HJ,this,a),(0,g.y)(this.GJ,this))}else o6(this,{}),p6(this)};
g.h.HJ=function(a,b){this.i=null;var c=g.fc(q6(this));if(g.Cb(c,g.fc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;o6(this,d);p6(this)}else this.Gb("Changing Screen set during request."),this.Gr()};
g.h.GJ=function(a){this.Gb("Screen availability failed: "+a);this.i=null;p6(this)};
g.h.Gb=function(a){a6("OnlineScreenService",a)};g.z(r6,e6);g.h=r6.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.M("screenChange"),this.i.isEmpty()||this.M("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.wn=function(a,b,c,d){this.l.contains(a)?this.l.wn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,a6(this.C,a),d(Error(a)))};
g.h.zd=function(a){return a?this.g:g.ob(this.g,(0,g.Fe)(this.o,function(a){return!this.contains(a)},this))};
g.h.vA=function(){return(0,g.Fe)(this.zd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.wA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new g6(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(a){g.Xf(f);d(s6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Xf(f);e(a)});
f.start();return(0,g.y)(f.stop,f)};
g.h.TL=function(a,b,c,d){g.hr(V5(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(a,d){var e=new s4(d.screen||{});if(!e.name||u6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);u6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(s6(this,e))},this),
onError:(0,g.y)(function(a){d(Error("pairing request failed: "+a.status))},this),
fd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.Xf(this.l);g.Xf(this.i);r6.Ga.T.call(this)};
g.h.uC=function(){v6(this);this.M("screenChange");this.i.update()};
r6.prototype.dispose=r6.prototype.dispose;g.z(x6,g.N);g.h=x6.prototype;g.h.Cm=function(a){this.l=a;this.M("sessionScreen",this.l)};
g.h.Cd=function(a){this.da()||(a&&y6(this,""+a),this.l=null,this.M("sessionScreen",null))};
g.h.info=function(a){a6(this.K,a)};
g.h.yA=function(){return null};
g.h.Rr=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){y6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.Rr("");x6.Ga.T.call(this)};g.z(A6,x6);g.h=A6.prototype;g.h.Qr=function(a){if(this.g){if(this.g==a)return;y6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Zoa(this)};
g.h.Nh=function(a){this.info("launchWithParams no-op for Cast: "+g.ph(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Cd()},this),(0,g.y)(function(){this.Cd(Error("Failed to stop receiver app."))},this)):this.Cd(Error("Stopping cast device witout session."))};
g.h.Rr=g.Ja;g.h.T=function(){this.info("disposeInternal");g.vq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;A6.Ga.T.call(this)};
g.h.DK=function(a,b){if(!this.da())if(b){var c=g.cp(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.ph(c));switch(d){case "mdxSessionStatus":z6(this,c.screenId);break;default:y6(this,"Unknown youtube message: "+d)}}else y6(this,"Unable to parse message.")}else y6(this,"No data in message.")};
g.h.kv=function(a,b,c,d){t6(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(y6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.tq((0,g.y)(this.kv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.yA=function(){return this.g};
g.h.UL=function(a){this.da()||a||(y6(this,"Cast session died."),this.Cd())};g.z(B6,x6);g.h=B6.prototype;g.h.Qr=function(a){this.o=a;this.o.addUpdateListener(this.N)};
g.h.Nh=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.vq(this.A);this.o?this.o.stop((0,g.y)(this.Cd,this,null),(0,g.y)(this.Cd,this,"Failed to stop DIAL device.")):this.Cd()};
g.h.T=function(){this.g();this.g=g.Ja;g.vq(this.A);this.o&&this.o.removeUpdateListener(this.N);this.o=null;B6.Ga.T.call(this)};
g.h.XL=function(a){this.da()||a||(y6(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Cd())};
g.h.Jp=function(a){this.H=y4();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,D6(this));a(b);C6(this)}else this.C=(0,g.y)(function(){g.vq(this.A);this.C=g.Ja;this.A=NaN;var b=new chrome.cast.DialLaunchResponse(!0,D6(this));a(b);C6(this)},this),this.A=g.tq((0,g.y)(function(){this.C()},this),100)};
g.h.RC=function(a,b,c){t6(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(a){a&&a.token?(this.Cm(a),b(new chrome.cast.DialLaunchResponse(!1))):this.Jp(b,c)},this),(0,g.y)(function(a){y6(this,"Failed to get DIAL screen: "+a);
this.Jp(b,c)},this))};g.z(E6,x6);E6.prototype.stop=function(){this.Cd()};
E6.prototype.Qr=g.Ja;E6.prototype.Nh=function(){g.vq(this.g);this.g=NaN;var a=A4(this.F.zd(),this.i.label);a?this.Cm(a):this.Cd(Error("No such screen"))};
E6.prototype.T=function(){g.vq(this.g);this.g=NaN;E6.Ga.T.call(this)};g.z(F6,g.N);g.h=F6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.oy,this),(0,g.y)(this.qJ,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.wH,this);chrome.cast.initialize(c,(0,g.y)(function(){this.da()||
(chrome.cast.addReceiverActionListener(this.o),Qoa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.xA,this)),this.l=K6(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.y)(function(a){this.Gb("Failed to set initial custom receivers: "+g.ph(a))},this)),this.M("yt-remote-cast2-availability-change",I6(this)),b(!0))},this),(0,g.y)(function(a){this.Gb("Failed to initialize API: "+g.ph(a));
b(!1)},this))};
g.h.jL=function(a,b){H6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)H6("Unsetting old screen status: "+this.g.i.friendlyName),J6(this,null)}if(a&&b){if(!this.g){c=A4(this.i.zd(),a);if(!c){H6("setConnectedScreenStatus: Unknown screen.");return}var d=G6(this,c);d||(H6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.y)(function(a){this.Gb("Failed to set initial custom receivers: "+g.ph(a))},this)));
H6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);J6(this,new E6(this.i,d),!0)}this.g.Rr(b)}else H6("setConnectedScreenStatus: no screen.")};
g.h.kL=function(a){this.da()?this.Gb("Setting connection data on disposed cast v2"):this.g?this.g.Nh(a):this.Gb("Setting connection data without a session")};
g.h.WL=function(){this.da()?this.Gb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),J6(this,null)):H6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.oy,this),(0,g.y)(this.MJ,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.xA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.kb(g.w("yt.mdx.remote.debug.handlers_")||[],X5);g.Xf(this.g);F6.Ga.T.call(this)};
g.h.Gb=function(a){a6("Controller",a)};
g.h.qy=function(a,b){this.g==a&&(b||J6(this,null),this.M("yt-remote-cast2-session-change",b))};
g.h.mJ=function(a,b){if(!this.da())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),H6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)H6("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{H6("onReceiverAction_: Casting to active receiver.");this.g.l&&this.M("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:J6(this,
new E6(this.i,a));break;case chrome.cast.ReceiverType.DIAL:J6(this,new B6(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:J6(this,new A6(this.i,a));break;default:this.Gb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Gb("Stopping receiver w/o session: "+a.friendlyName)}else this.Gb("onReceiverAction_ called without receiver.")};
g.h.wH=function(a){if(this.da())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Gb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return H6("Reselecting dial screen."),
this.M("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);J6(this,new B6(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.RC,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Jp,b))};
g.h.oy=function(a){if(!this.da()){H6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)H6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),J6(this,new A6(this.i,b),!0);else{this.Gb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=A4(this.i.zd(),c.label);d&&t4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(H6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Xf(this.g),this.g=new A6(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.qy,this,this.g)),this.g.Nh(null));this.g.Qr(a)}}};
g.h.VL=function(){return this.g?this.g.yA():null};
g.h.MJ=function(a){this.da()||(this.Gb("Failed to estabilish a session: "+g.ph(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&J6(this,null))};
g.h.qJ=function(a){H6("Receiver availability updated: "+a);if(!this.da()){var b=I6(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;I6(this)!=b&&this.M("yt-remote-cast2-availability-change",I6(this))}};
g.h.xA=function(){this.da()||(this.l=K6(this),H6("Updating custom receivers: "+g.ph(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.y)(function(){this.Gb("Failed to set custom receivers.")},this)),this.M("yt-remote-cast2-availability-change",I6(this)))};
F6.prototype.setLaunchParams=F6.prototype.kL;F6.prototype.setConnectedScreenStatus=F6.prototype.jL;F6.prototype.stopSession=F6.prototype.WL;F6.prototype.getCastSession=F6.prototype.VL;F6.prototype.requestSession=F6.prototype.requestSession;F6.prototype.init=F6.prototype.init;F6.prototype.dispose=F6.prototype.dispose;var T6=[];a7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";b7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ae=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
a7.prototype.isAdPlaying=function(){return 1081==this.playerState};
a7.prototype.getDuration=function(){return this.u?this.D+c7(this):this.D};
a7.prototype.clone=function(){return new a7(g7(this))};g.z(j7,g.N);g.h=j7.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,r7(this,"play")):p7(this,"play"),o7(this,1,e7(k7(this))),this.M("remotePlayerChange")):m7(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,r7(this,"pause")):p7(this,"pause"),o7(this,2,e7(k7(this))),this.M("remotePlayerChange")):m7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=k7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,r7(this,"seekTo",{newTime:a}))}else p7(this,"seekTo",{newTime:a});o7(this,3,a);this.M("remotePlayerChange")}else m7(this,g.Va(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,r7(this,"stopVideo")):p7(this,"stopVideo");var a=k7(this);a.index=-1;a.videoId="";b7(a);n7(this,a);this.M("remotePlayerChange")}else m7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=k7(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){a6("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Gb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){a6("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Gb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);p7(this,"setVolume",e)}c.muted=b;c.volume=a;n7(this,c)}else m7(this,g.Va(this.setVolume,a,b))};
g.h.wz=function(a,b){if(1==this.g){var c=k7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.ph(b.style),g.tc(d,c.g));p7(this,"setSubtitlesTrack",d);n7(this,c)}else m7(this,g.Va(this.wz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){p7(this,"setAudioTrack",{videoId:a,audioTrackId:b.nb.id});var c=k7(this);c.audioTrackId=b.nb.id;n7(this,c)}else m7(this,g.Va(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=k7(this);c=c||0;var m={videoId:a,currentIndex:c};f7(l,a,c);g.Fa(b)&&(d7(l,b),m.currentTime=b);g.Fa(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.ph(k));p7(this,"setPlaylist",m);d||n7(this,l)};
g.h.Jm=function(a,b){if(1==this.g){if(a&&b){var c=k7(this);f7(c,a,b);n7(this,c)}p7(this,"previous")}else m7(this,g.Va(this.Jm,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=k7(this);f7(c,a,b);n7(this,c)}p7(this,"next")}else m7(this,g.Va(this.nextVideo,a,b))};
g.h.Bu=function(){1==this.g?p7(this,"dismissAutoplay"):m7(this,this.Bu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.M("proxyStateChange",a,this.g)}j7.Ga.dispose.call(this)};
g.h.T=function(){l7(this);this.o=null;this.u.clear();i7(this,null);j7.Ga.T.call(this)};
g.h.Hs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.M("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.iJ=function(a,b){this.M(a,b)};
g.h.bH=function(a){if(!a)this.Zj(null),i7(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=k7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)a6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,n7(this,b)}};
g.h.Zj=function(a){a6("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),q7(this),this.M("remotePlayerChange")};
g.h.aH=function(a){a?(q7(this),this.M("remotePlayerChange")):this.Zj(null)};
g.h.ms=function(){p7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.nH=function(){var a=X6();a&&i7(this,a)};
g.h.Gb=function(a){a6("CP",a)};g.z(s7,g.N);g.h=s7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Fa(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Fa(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;d7(this.Pa,m);this.o="UNSUPPORTED";t7("Connecting with setPlaylist and params: "+g.ph(l));this.g.connect({method:"setPlaylist",
params:g.ph(l)},a,G4())}else t7("Connecting without params"),this.g.connect({},a,G4());fpa(this)};
g.h.dispose=function(){this.da()||(this.M("beforeDispose"),u7(this,3));s7.Ga.dispose.call(this)};
g.h.T=function(){v7(this);x7(this);w7(this);g.vq(this.F);this.F=NaN;g.vq(this.H);this.H=NaN;this.l=null;g.hs(this.R);this.R.length=0;this.g.dispose();s7.Ga.T.call(this);this.o=this.C=this.i=this.Pa=this.g=null};
g.h.eC=function(){this.A(2)};
g.h.fH=function(){t7("Channel opened");this.O&&(this.O=!1,w7(this),this.K=g.tq((0,g.y)(function(){t7("Timing out waiting for a screen.");this.A(1)},this),15E3));
Hoa(Ooa(this.g),this.Z)};
g.h.cH=function(){t7("Channel closed");isNaN(this.u)?J4(!0):J4();this.dispose()};
g.h.dH=function(a){J4();isNaN(this.D())?(t7("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,t7("Channel error: "+a+" with reconnection in "+this.D()+" ms"),u7(this,2))};
g.h.eH=function(a){a.params?t7("Received: action="+a.action+", params="+g.ph(a.params)):t7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.cp(a.params.devices);this.i=(0,g.D)(a,function(a){return new r4(a)});
a=!!g.cb(this.i,function(a){return"LOUNGE_SCREEN"==a.type});
A7(this,a);break;case "loungeScreenDisconnected":g.lb(this.i,function(a){return"LOUNGE_SCREEN"==a.type});
A7(this,!1);break;case "remoteConnected":var b=new r4(g.cp(a.params.device));g.cb(this.i,function(a){return b?a.id==b.id:!1})||xoa(this.i,b);
break;case "remoteDisconnected":b=new r4(g.cp(a.params.device));g.lb(this.i,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":B7(this,a);break;case "nowPlaying":ipa(this,a);break;case "onStateChange":C7(this,a);break;case "onAdStateChange":jpa(this,a);break;case "onVolumeChanged":kpa(this,a);break;case "onSubtitlesTrackChanged":hpa(this,a);break;case "nowAutoplaying":lpa(this,a);break;case "autoplayDismissed":this.M("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.M("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.M("autoplayModeChange",this.o);"DISABLED"==this.o&&this.M("autoplayDismissed");break;case "onHasPreviousNextChanged":mpa(this,a);break;case "requestAssistedSignIn":this.M("assistedSignInRequested",a.params.authCode);break;default:t7("Unrecognized action: "+a.action)}};
g.h.XK=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&y7(this,"getNowPlaying")}};
s7.prototype.subscribe=s7.prototype.subscribe;s7.prototype.unsubscribeByKey=s7.prototype.vf;s7.prototype.ba=function(){var a=3;this.da()||(a=0,isNaN(this.D())?T5(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
s7.prototype.getProxyState=s7.prototype.ba;s7.prototype.A=function(a){t7("Disconnecting with "+a);v7(this);this.M("beforeDisconnect",a);1==a&&J4();S5(this.g,a);this.dispose()};
s7.prototype.disconnect=s7.prototype.A;s7.prototype.ga=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),f7(a,this.l,a.index));return g7(a)};
s7.prototype.getPlayerContextData=s7.prototype.ga;
s7.prototype.la=function(a){var b=new a7(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.vq(this.F),this.F=g.tq((0,g.y)(this.XK,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&e7(this.Pa)==e7(b)&&g.ph(this.Pa.g)==g.ph(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.A)(c,function(a){this.M(a)},this)};
s7.prototype.setPlayerContextData=s7.prototype.la;s7.prototype.P=function(){var a=this.g.A.id,b=g.cb(this.i,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
s7.prototype.getOtherConnectedRemoteId=s7.prototype.P;s7.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.B)():NaN};
s7.prototype.getReconnectTimeout=s7.prototype.D;s7.prototype.Y=function(){return this.o||"UNSUPPORTED"};
s7.prototype.getAutoplayMode=s7.prototype.Y;s7.prototype.W=function(){return this.C||""};
s7.prototype.getAutoplayVideoId=s7.prototype.W;s7.prototype.sa=function(){if(!isNaN(this.D())){var a=this.g.i;g.To(a.g);a.start()}};
s7.prototype.reconnect=s7.prototype.sa;s7.prototype.ia=function(a,b){y7(this,a,b);z7(this)};
s7.prototype.sendMessage=s7.prototype.ia;g.z(D7,e6);g.h=D7.prototype;g.h.zd=function(a){return this.Ac.$_gs(a)};
g.h.contains=function(a){return!!this.Ac.$_c(a)};
g.h.get=function(a){return this.Ac.$_g(a)};
g.h.start=function(){this.Ac.$_st()};
g.h.add=function(a,b,c){this.Ac.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ac.$_r(a,b,c)};
g.h.wn=function(a,b,c,d){this.Ac.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ac.$_ubk(this.i[a]);this.i.length=0;this.Ac=null;D7.Ga.T.call(this)};
g.h.SL=function(){this.M("screenChange")};
g.h.LI=function(){this.M("onlineScreenChange")};
r6.prototype.$_st=r6.prototype.start;r6.prototype.$_gspc=r6.prototype.TL;r6.prototype.$_gsppc=r6.prototype.wA;r6.prototype.$_c=r6.prototype.contains;r6.prototype.$_g=r6.prototype.get;r6.prototype.$_a=r6.prototype.add;r6.prototype.$_un=r6.prototype.wn;r6.prototype.$_r=r6.prototype.remove;r6.prototype.$_gs=r6.prototype.zd;r6.prototype.$_gos=r6.prototype.vA;r6.prototype.$_s=r6.prototype.subscribe;r6.prototype.$_ubk=r6.prototype.vf;var E7=null,F7=null,V7=null,J7=[];g.r(Y7,g.F);g.h=Y7.prototype;
g.h.T=function(){g.F.prototype.T.call(this);this.o.stop();this.A.stop();this.N.stop();this.O();this.g.unsubscribe("proxyStateChange",this.ly,this);this.g.unsubscribe("remotePlayerChange",this.bk,this);this.g.unsubscribe("remoteQueueChange",this.Dm,this);this.g.unsubscribe("autoplayUpNext",this.Nx,this);this.g.unsubscribe("previousNextChange",this.iy,this);this.g.unsubscribe("nowAutoplaying",this.ey,this);this.g.unsubscribe("autoplayDismissed",this.Mx,this);this.g=this.u=null};
g.h.Lw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(b8(this)){if(!k7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==k7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.pj(c[0],c[1]);break;case "control_subtitles_set_track":c8(this,c[0]);break;case "control_set_audio_track":c=c[0],b8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();d8(this,0==c?void 0:c);break;case "control_seek":d8(this,c[0]);break;case "control_subtitles_set_track":c8(this,c[0]);break;case "control_set_audio_track":c=c[0],b8(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.ZG=function(a){this.N.bC(a)};
g.h.BL=function(a){this.Lw("control_subtitles_set_track",g.lc(a)?null:a)};
g.h.Jz=function(){var a=this.i.getOption("captions","track");g.lc(a)||c8(this,a)};
g.h.Yx=function(a){if(b8(this)){this.g.unsubscribe("remotePlayerChange",this.bk,this);var b=Math.round(a.volume);a=!!a.muted;var c=k7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.bk,this)}};
g.h.cI=function(){g.lc(this.C)||e8(this,this.C);this.D=!1};
g.h.ly=function(a,b){this.A.stop();2==b&&this.Iz()};
g.h.bk=function(){if(b8(this)){this.o.stop();var a=k7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Pl=1;break;case 1082:case 1083:this.u.Pl=0;break;default:this.u.Pl=-1}switch(a.playerState){case 1081:case 1:$7(this,new g.fD(8));this.Hz();break;case 1085:case 3:$7(this,new g.fD(9));break;case 1083:case 0:$7(this,new g.fD(2));this.H.stop();Z7(this,this.i.getVideoData().lengthSeconds);break;case 1084:$7(this,new g.fD(4));break;case 2:$7(this,new g.fD(4));Z7(this,e7(a));
break;case -1:$7(this,new g.fD(64));break;case -1E3:$7(this,new g.fD(128,{errorCode:"mdx.remoteerror",message:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=k7(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,e8(this,a));a=k7(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.K.isActive()||
this.jA()}else a8(this)};
g.h.iy=function(){this.i.M("mdxpreviousnextchange")};
g.h.Dm=function(){b8(this)||a8(this)};
g.h.tB=function(){this.g.Bu()};
g.h.Nx=function(a){a&&(a=g.hr("/watch_queue_ajax",{method:"GET",yc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.lK,this)}))&&(this.O=(0,g.y)(a.abort,a))};
g.h.lK=function(a,b){var c=new g.mB(g.V(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.M("mdxautoplayupnext",c)};
g.h.ey=function(a){isNaN(a)||this.i.M("mdxnowautoplaying",a)};
g.h.Mx=function(){this.i.M("mdxautoplaycanceled")};
g.h.EE=function(a,b){-1==k7(this.g).playerState?d8(this,a):b&&this.g.seekTo(a)};
g.h.jA=function(){if(b8(this)){var a=k7(this.g);this.l.Ma(this.R);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.R=this.l.J(this.i,"onVolumeChange",this.Yx)}};
g.h.Hz=function(){this.o.stop();if(!this.g.da()){var a=k7(this.g);1==a.playerState&&$7(this,new g.fD(8));Z7(this,e7(a));this.o.start()}};
g.h.Iz=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.r(h8,g.T);h8.prototype.o=function(a){g8(this,a.state)};g.r(i8,g.kT);i8.prototype.H=function(){var a=this.i.getOption("remote","receivers");a&&1<a.length&&!this.i.getOption("remote","quickCast")?(this.C=g.Eb(a,this.u,this),g.lT(this,(0,g.D)(a,this.u)),a=this.i.getOption("remote","currentReceiver"),this.he(this.u(a)),this.enable(!0)):this.enable(!1)};
i8.prototype.u=function(a){return a.key};
i8.prototype.ge=function(a){return"cast-selector-receiver"==a?"Elenco...":this.C[a].name};
i8.prototype.Qc=function(a){g.kT.prototype.Qc.call(this,a);this.i.setOption("remote","currentReceiver",this.C[a]);this.l.gb()};g.r(j8,g.sK);g.h=j8.prototype;g.h.create=function(){rpa(g.dz(g.V(this.player)));this.u.push(g.Aq("yt-remote-before-disconnect",this.WG,this));this.u.push(g.Aq("yt-remote-connection-change",this.rJ,this));this.u.push(g.Aq("yt-remote-receiver-availability-change",this.jy,this));this.u.push(g.Aq("yt-remote-auto-connect",this.pJ,this));this.u.push(g.Aq("yt-remote-receiver-resumed",this.oJ,this));this.jy()};
g.h.load=function(){this.player.cancelPlayback();g.sK.prototype.load.call(this);this.o=new Y7(this,this.player,this.g);var a=(a=X7())?a.currentTime:0;var b=U7()?new j7(P7(),void 0):null;0==a&&b&&(a=e7(k7(b)));0!=a&&this.hd(a);f8(this,this.Nj,this.Nj);g.hX(this.player.app,6)};
g.h.unload=function(){this.player.M("mdxautoplaycanceled");this.l=this.i;g.Yf(this.o,this.g);this.g=this.o=null;g.sK.prototype.unload.call(this);g.hX(this.player.app,5)};
g.h.T=function(){g.Bq(this.u);g.sK.prototype.T.call(this)};
g.h.Ne=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.Lw.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Pl};
g.h.XB=function(){return this.loaded?this.o.suggestion:null};
g.h.Ae=function(){return this.g?k7(this.g).Ae:!1};
g.h.hasNext=function(){return this.g?k7(this.g).hasNext:!1};
g.h.hd=function(a,b){this.D=a||0;this.player.M("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=k7(this.g),b=this.player.getVideoData();return{allowSeeking:g.P(g.V(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Zb():!a.isAdPlaying()&&this.player.Zb(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+c7(a):a.l,isPeggedToLive:1>=(a.u?a.i+c7(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+c7(a):a.i,seekableStart:0<a.o?a.o+
c7(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Jm=function(){this.g&&this.g.Jm()};
g.h.WG=function(a){1==a&&(this.C=this.g?k7(this.g):null)};
g.h.rJ=function(){var a=U7()?new j7(P7(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.Xf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,e7(a)));this.player.M("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.jy=function(){this.A=[this.i].concat(spa());var a=Q7()||this.i;k8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.pJ=function(){var a=Q7();k8(this,a)};
g.h.oJ=function(){this.l=Q7()};
g.h.Wb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Z6():k8(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&Z6(),!0):!1}};
g.h.ms=function(){this.g.ms()};
g.h.Kb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.xU.remote=j8;})(_yt_player);
