<html lang="en" class="wf-poppins-n3-active wf-poppins-n4-active wf-poppins-n5-active wf-poppins-n6-active wf-poppins-n7-active wf-roboto-n3-active wf-roboto-n4-active wf-roboto-n5-active wf-roboto-n6-active wf-roboto-n7-active wf-active">
   <head>
      <meta charset="utf-8">
      <title>Metronic | Login Page - 5</title>
      <meta name="description" content="Latest updates and statistic charts">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700%7CRoboto:300,400,500,600,700" media="all">
      <link href="https://keenthemes.com/metronic/preview/assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css">
      <link href="https://keenthemes.com/metronic/preview/assets/demo/default/base/style.bundle.css" rel="stylesheet" type="text/css">
      <link rel="shortcut icon" href="https://keenthemes.com/metronic/preview/assets/demo/default/media/img/logo/favicon.ico">
   </head>
   <body class="m--skin- m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default">
      <div class="m-grid m-grid--hor m-grid--root m-page">
         <header id="m_header" class="m-grid__item    m-header " m-minimize-offset="200" m-minimize-mobile-offset="200">
            <div class="m-container m-container--fluid m-container--full-height">
               <div class="m-stack m-stack--ver m-stack--desktop">
                  <div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">
                     <button class="m-aside-header-menu-mobile-close  m-aside-header-menu-mobile-close--skin-dark " id="m_aside_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
                     <div id="m_header_menu" class="m-header-menu m-aside-header-menu-mobile m-aside-header-menu-mobile--offcanvas  m-header-menu--skin-light m-header-menu--submenu-skin-light m-aside-header-menu-mobile--skin-dark m-aside-header-menu-mobile--submenu-skin-dark ">
                     </div>
                     <div id="m_header_topbar" class="m-topbar  m-stack m-stack--ver m-stack--general m-stack--fluid">
                        <div class="m-stack__item m-topbar__nav-wrapper">
                           <ul class="m-topbar__nav m-nav m-nav--inline">
                              <li 
                                class="m-nav__item m-dropdown m-dropdown--large m-dropdown--arrow m-dropdown--align-center m-dropdown--mobile-full-width m-dropdown--skin-light m-list-search m-list-search--skin-light" 
                                m-dropdown-toggle="click" 
                                id="m_quicksearch" 
                                m-quicksearch-mode="dropdown" 
                                m-dropdown-persistent="1" 
                                aria-expanded="true">
                                 <div class="form-group m-form__group">
                                    <label for="exampleInputEmail1">
                                    <font style="vertical-align: inherit;"></font></label>
                                    <input 
                                        type="email" 
                                        class="form-control m-input m-input--air m-input--pill" 
                                        id="email" 
                                        aria-describedby="emailHelp" 
                                        placeholder="Email ou Telefone">
                                 </div>
                              </li>
                              <li 
                                class="m-nav__item m-dropdown m-dropdown--large m-dropdown--arrow m-dropdown--align-center m-dropdown--mobile-full-width m-dropdown--skin-light m-list-search m-list-search--skin-light" 
                                m-dropdown-toggle="click" 
                                id="m_quicksearch" 
                                m-quicksearch-mode="dropdown" 
                                m-dropdown-persistent="1" 
                                aria-expanded="true">
                                 <div class="form-group m-form__group">
                                    <label for="exampleInputPassword1"><font style="vertical-align: inherit;"></font></label>
                                    <input 
                                        type="password" 
                                        class="form-control m-input m-input--air m-input--pill" 
                                        id="password" 
                                        placeholder="Senha">
                                 </div>
                              </li>
                              <li 
                                class="m-nav__item m-dropdown m-dropdown--large m-dropdown--arrow m-dropdown--align-center m-dropdown--mobile-full-width m-dropdown--skin-light m-list-search m-list-search--skin-light m-dropdown--open" 
                                m-dropdown-toggle="click" 
                                id="m_quicksearch" 
                                m-quicksearch-mode="dropdown" 
                                m-dropdown-persistent="1" 
                                aria-expanded="true">
                                 <label for="exampleInputPassword1"><font style="vertical-align: inherit;"></font></label>
                                 <div class="m-login__form-action">
                                    <button 
                                        id="m_login_signin_submit" 
                                        class="btn btn-success m-btn m-btn--pill m-btn--custom m-btn--air">
                                        Entrar
                                    </button>
                                 </div>
                              </li>
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </header>
         <div 
            class="m-login m-login--5 m-login--signup" 
            id="m_login" 
            style="background-image: url(https://keenthemes.com/metronic/preview/assets/app/media/img//bg/bg-3.jpg);">
            <div class="m-login__wrapper-1 m-portlet-full-height">
            </div>
            <div class="m-login__wrapper-2 m-portlet-full-height">
               <div class="m-login__contanier">
                  <div class="m-login__signup animated flipInX">
                     <div class="m-login__head">
                        <h3 class="m-login__title">Criar uma nova conta</h3>
                        <div class="m-login__desc">É gratuito e sempre será.</div>
                     </div>
                     <form class="m-login__form m-form" action="">
                        <div class="form-group m-form__group">
                           <input 
                                class="form-control m-input" 
                                type="text" 
                                placeholder="Nome completo" 
                                name="fullname">
                        </div>
                        <div class="form-group m-form__group">
                           <input 
                                class="form-control m-input" 
                                type="text" 
                                placeholder="Email" 
                                name="email" 
                                autocomplete="off">
                        </div>
                        <div class="form-group m-form__group">
                           <input 
                                class="form-control m-input" 
                                type="password" 
                                placeholder="Senha" 
                                name="password">
                        </div>
                        <div class="form-group m-form__group">
                           <input 
                                class="form-control m-input m-login__form-input--last" 
                                type="password" 
                                placeholder="Confirmar Senha" 
                                name="rpassword">
                        </div>
                        <div class="m-login__form-sub">
                           <label class="m-radio m-radio--bold m-radio--state-brand">
                           <input 
                                type="radio" 
                                name="example_3" 
                                value="1">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Marculino</font>&nbsp;</font><span></span>
                           </label>
                           <label class="m-radio m-radio--bold m-radio--state-brand">
                           <input 
                                type="radio" 
                                name="example_3" 
                                value="2">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Feminino</font></font><span></span>
                           </label>
                        </div>
                        <div class="m-login__form-sub">
                           <label class="m-checkbox m-checkbox--focus">
                           <input 
                                type="checkbox" 
                                name="agree">Eu concordo com os <a href="#" class="m-link m-link--focus">termos e condições</a>.
                           <span></span>
                           </label>
                           <span class="m-form__help"></span>
                        </div>
                        <div class="m-login__form-action">
                           <button id="m_login_signup_submit" class="btn btn-focus m-btn m-btn--pill m-btn--custom m-btn--air">Inscreva-se</button>
                           <button id="m_login_signup_cancel" class="btn btn-outline-focus m-btn m-btn--pill m-btn--custom">Cancelar</button>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <script type="text/javascript" src="./../../bundle.js"></script>
   </body>
</html>