<!DOCTYPE html>
<html>
    <head>
            <meta charset="utf-8">
            
            <title>Home | WorldStudio</title>
            <meta name="description" content="Latest updates and statistic charts"> 
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

            <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
			<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700%7CRoboto:300,400,500,600,700" media="all">
			

            <link href="./assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css">
            <link href="https://keenthemes.com/metronic/preview/assets/demo/default/base/style.bundle.css" rel="stylesheet" type="text/css">
            <link href="https://keenthemes.com/metronic/preview/assets/vendors/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css">
            <link rel="shortcut icon" href="https://keenthemes.com/metronic/preview/assets/demo/default/media/img/logo/favicon.ico">
	
	<style type="text/css">
		.m-wrapper {
			margin-bottom: 10px;
			margin-left: -256px;
		}
	</style>
	</head>

	<body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default" style="">
    	<div class="m-grid m-grid--hor m-grid--root m-page">
			<?= include 'menu.phtml'; ?>
			<?= include 'time-line.phtml'; ?>
		</div>
	</body>
</html>