<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Home | WorldStudio</title>
      <meta name="description" content="Latest updates and statistic charts">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
      <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700%7CRoboto:300,400,500,600,700" media="all">
      <link href="./assets/vendors/base/vendors.bundle.css" rel="stylesheet" type="text/css">
      <link href="https://keenthemes.com/metronic/preview/assets/demo/default/base/style.bundle.css" rel="stylesheet" type="text/css">
      <link href="https://keenthemes.com/metronic/preview/assets/vendors/custom/fullcalendar/fullcalendar.bundle.css" rel="stylesheet" type="text/css">
      <link rel="shortcut icon" href="https://keenthemes.com/metronic/preview/assets/demo/default/media/img/logo/favicon.ico">
      <style type="text/css">
         .m-wrapper {
         margin-bottom: 10px;
         margin-left: -256px;
         }
      </style>
   </head>
   <body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-dark m-aside-left--fixed m-aside-left--offcanvas m-footer--push m-aside--offcanvas-default" style="">
      <div class="m-grid m-grid--hor m-grid--root m-page">
         <?= include 'menu.phtml'; ?>
         <div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body">
            <div class="m-grid__item m-grid__item--fluid m-wrapper">
               <div class="m-subheader ">
                  <div class="d-flex align-items-center">
                     <div class="mr-auto">
                        <h3 class="m-subheader__title ">Dashboard</h3>
                     </div>
                     <div>
                        <span class="m-subheader__daterange" id="m_dashboard_daterangepicker">
                        <span class="m-subheader__daterange-label">
                        <span class="m-subheader__daterange-title">Today:</span>
                        <span class="m-subheader__daterange-date m--font-brand">Jan 30</span>
                        </span>
                        <a href="#" class="btn btn-sm btn-brand m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill">
                        <i class="la la-angle-down"></i>
                        </a>
                        </span>
                     </div>
                  </div>
               </div>
               <div class="m-content">
                  <div class="row">
                     <div class="col-xl-6 col-lg-12">
                        <div class="m-portlet  m-portlet--full-height ">
                           <div class="m-portlet__head">
                              <div class="m-portlet__head-caption">
                                 <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text">
                                       Ranking Brasil
                                    </h3>
                                 </div>
                              </div>
                              <div class="m-portlet__head-tools">
                                 <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push" m-dropdown-toggle="hover" aria-expanded="true">
                                       <a href="#" class="m-portlet__nav-link m-portlet__nav-link--icon m-portlet__nav-link--icon-xl m-dropdown__toggle">
                                       <i class="la la-ellipsis-h m--font-brand"></i>
                                       </a>
                                       <div class="m-dropdown__wrapper">
                                          <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
                                          <div class="m-dropdown__inner">
                                             <div class="m-dropdown__body">
                                                <div class="m-dropdown__content">
                                                   <ul class="m-nav">
                                                      <li class="m-nav__section m-nav__section--first">
                                                         <span class="m-nav__section-text">Quick Actions</span>
                                                      </li>
                                                      <li class="m-nav__item">
                                                         <a href="" class="m-nav__link">
                                                         <i class="m-nav__link-icon flaticon-share"></i>
                                                         <span class="m-nav__link-text">Activity</span>
                                                         </a>
                                                      </li>
                                                      <li class="m-nav__item">
                                                         <a href="" class="m-nav__link">
                                                         <i class="m-nav__link-icon flaticon-chat-1"></i>
                                                         <span class="m-nav__link-text">Messages</span>
                                                         </a>
                                                      </li>
                                                      <li class="m-nav__item">
                                                         <a href="" class="m-nav__link">
                                                         <i class="m-nav__link-icon flaticon-info"></i>
                                                         <span class="m-nav__link-text">FAQ</span>
                                                         </a>
                                                      </li>
                                                      <li class="m-nav__item">
                                                         <a href="" class="m-nav__link">
                                                         <i class="m-nav__link-icon flaticon-lifebuoy"></i>
                                                         <span class="m-nav__link-text">Support</span>
                                                         </a>
                                                      </li>
                                                      <li class="m-nav__separator m-nav__separator--fit">
                                                      </li>
                                                      <li class="m-nav__item">
                                                         <a href="#" class="btn btn-outline-danger m-btn m-btn--pill m-btn--wide btn-sm">Cancel</a>
                                                      </li>
                                                   </ul>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                    </li>
                                 </ul>
                              </div>
                           </div>
                           <div class="m-portlet__body">
                              <div class="m-scrollable m-scroller ps ps--active-y" data-scrollable="true" data-height="380" data-mobile-height="300" style="overflow: auto; width: 100%; height: 400px;">
                                 <div class="m-timeline-2">
                                    <div class="m-timeline-2__items  m--padding-top-25 m--padding-bottom-30">
                                       <div class="m-timeline-2__item">
                                          <span class="m-timeline-2__item-time">1º</span>	
                                          <div class="m-timeline-2__item-cricle">									 
                                             <i class="fa fa-genderless m--font-danger"></i>									 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold">
                                             studio D 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold" align="left">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                          </div>
                                       </div>
                                       <div class="m-timeline-2__item m--margin-top-30">
                                          <span class="m-timeline-2__item-time">2º</span>	
                                          <div class="m-timeline-2__item-cricle">																		 
                                             <i class="fa fa-genderless m--font-success"></i>									 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold">
                                             Espaço Moriá Coiffeurs 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold" align="left">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                          </div>
                                       </div>
                                       <div class="m-timeline-2__item m--margin-top-30">
                                          <span class="m-timeline-2__item-time">3º</span>	
                                          <div class="m-timeline-2__item-cricle">																		 
                                             <i class="fa fa-genderless m--font-brand"></i>									 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold">
                                             Fa,bella
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold" align="left">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                          </div>
                                       </div>
                                       <div class="m-timeline-2__item m--margin-top-30">
                                          <span class="m-timeline-2__item-time">4º</span>
                                          <div class="m-timeline-2__item-cricle">																		 
                                             <i class="fa fa-genderless m--font-warning"></i>									 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold">
                                             Navalha real
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold" align="left">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                          </div>
                                       </div>
                                       <div class="m-timeline-2__item m--margin-top-30">
                                          <span class="m-timeline-2__item-time">5º</span>
                                          <div class="m-timeline-2__item-cricle">	
                                             <i class="fa fa-genderless m--font-info"></i>									 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold">
                                             Bunker Barbearia
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold" align="left">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                          </div>
                                       </div>
                                       <div class="m-timeline-2__item m--margin-top-30">
                                          <span class="m-timeline-2__item-time">6º</span>
                                          <div class="m-timeline-2__item-cricle">	
                                             <i class="fa fa-genderless m--font-brand"></i>									 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold">
                                             MOSH STUDIOS 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold" align="left">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                          </div>
                                       </div>
                                       <div class="m-timeline-2__item m--margin-top-30">
                                          <span class="m-timeline-2__item-time">7º</span>
                                          <div class="m-timeline-2__item-cricle">	
                                             <i class="fa fa-genderless m--font-danger"></i>									 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold">
                                             Flap Studios 
                                          </div>
                                          <div class="m-timeline-2__item-text m-timeline-2__item-text--bold" align="left">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/1.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                             <img src="https://app.plom.com.br/theme/dist/html/default/assets/app/media/img/stars/0.png&#10;" width="20" height="20">
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div class="col-xl-6 col-lg-12">
                        <div class="m-portlet m-portlet--full-height ">
                           <div class="m-portlet__head">
                              <div class="m-portlet__head-caption">
                                 <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text">
                                       Ranking Mundial
                                    </h3>
                                 </div>
                              </div>
                              <div class="m-portlet__head-tools">
                                 <ul class="nav nav-pills nav-pills--brand m-nav-pills--align-right m-nav-pills--btn-pill m-nav-pills--btn-sm" role="tablist">
                                    <li class="nav-item m-tabs__item">
                                       <a class="nav-link m-tabs__link active" data-toggle="tab" href="#m_widget2_tab1_content" role="tab">
                                       Today
                                       </a>
                                    </li>
                                    <li class="nav-item m-tabs__item">
                                       <a class="nav-link m-tabs__link" data-toggle="tab" href="#m_widget2_tab2_content" role="tab">
                                       Month
                                       </a>
                                    </li>
                                 </ul>
                              </div>
                           </div>
                           <div class="m-portlet__body">
                              <div class="tab-content">
                                 <div class="tab-pane active" id="m_widget2_tab1_content">
                                    <div class="m-timeline-3" style="overflow: auto; width: 100%; height: 400px;">
                                       <div class="m-timeline-3__items">
                                          <div class="m-timeline-3__item m-timeline-3__item--info">
                                             <span class="m-timeline-3__item-time">1º</span> 
                                             <div class="m-timeline-3__item-desc">							 
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit amit,consectetur eiusmdd tempor 
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Bob
                                                </a>
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--warning">
                                             <span class="m-timeline-3__item-time">2º</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit amit
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Sean
                                                </a>	
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time">3º</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit amit eiusmdd tempor
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By James
                                                </a>	
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--success">
                                             <span class="m-timeline-3__item-time">4º</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor 
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By James
                                                </a>	
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--danger">
                                             <span class="m-timeline-3__item-time">5º</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit amit,consectetur eiusmdd
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Derrick
                                                </a>										 
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--info">
                                             <span class="m-timeline-3__item-time">6º</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit amit,consectetur
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Iman
                                                </a>
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time">7º</span>
                                             <div class="m-timeline-3__item-desc">
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit consectetur eiusmdd tempor
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Aziko
                                                </a>	
                                                </span>	
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time">8º</span>
                                             <div class="m-timeline-3__item-desc">
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit consectetur eiusmdd tempor
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Aziko
                                                </a>	
                                                </span>	
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time">9º</span>
                                             <div class="m-timeline-3__item-desc">
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit consectetur eiusmdd tempor
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Aziko
                                                </a>	
                                                </span>	
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time">10º</span>
                                             <div class="m-timeline-3__item-desc">
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit consectetur eiusmdd tempor
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Aziko
                                                </a>	
                                                </span>	
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time">11º</span>
                                             <div class="m-timeline-3__item-desc">
                                                <span class="m-timeline-3__item-text">
                                                Lorem ipsum dolor sit consectetur eiusmdd tempor
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Aziko
                                                </a>	
                                                </span>	
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="tab-pane" id="m_widget2_tab2_content">
                                    <div class="m-timeline-3">
                                       <div class="m-timeline-3__items">
                                          <div class="m-timeline-3__item m-timeline-3__item--info">
                                             <span class="m-timeline-3__item-time m--font-focus">09:00</span> 
                                             <div class="m-timeline-3__item-desc">							 
                                                <span class="m-timeline-3__item-text">
                                                Contrary to popular belief, Lorem Ipsum is not simply random text.
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Bob
                                                </a>
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--warning">
                                             <span class="m-timeline-3__item-time m--font-warning">10:00</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                There are many variations of passages of Lorem Ipsum available.
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Sean
                                                </a>	
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time m--font-primary">11:00</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Contrary to popular belief, Lorem Ipsum is not simply random text.
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By James
                                                </a>	
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--success">
                                             <span class="m-timeline-3__item-time m--font-success">12:00</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                The standard chunk of Lorem Ipsum used since the 1500s is reproduced.
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By James
                                                </a>	
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--danger">
                                             <span class="m-timeline-3__item-time m--font-warning">14:00</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Latin words, combined with a handful of model sentence structures.
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Derrick
                                                </a>										 
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--info">
                                             <span class="m-timeline-3__item-time m--font-info">15:00</span> 
                                             <div class="m-timeline-3__item-desc">							
                                                <span class="m-timeline-3__item-text">
                                                Contrary to popular belief, Lorem Ipsum is not simply random text.
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Iman
                                                </a>
                                                </span>		 
                                             </div>
                                          </div>
                                          <div class="m-timeline-3__item m-timeline-3__item--brand">
                                             <span class="m-timeline-3__item-time m--font-danger">17:00</span>
                                             <div class="m-timeline-3__item-desc">
                                                <span class="m-timeline-3__item-text">
                                                Lorem Ipsum is therefore always free from repetition, injected humour.
                                                </span><br>
                                                <span class="m-timeline-3__item-user-name">
                                                <a href="#" class="m-link m-link--metal m-timeline-3__item-link">
                                                By Aziko
                                                </a>	
                                                </span>	
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </body>
</html>